// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// VCS coverage exclude_file
module bank_65536x16(	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
  input  [15:0] R0_addr,
  input         R0_en,
                R0_clk,
  output [15:0] R0_data,
  input  [15:0] R1_addr,
  input         R1_en,
                R1_clk,
  output [15:0] R1_data,
  input  [15:0] W0_addr,
  input         W0_en,
                W0_clk,
  input  [15:0] W0_data
);

  reg [15:0] Memory[0:65535];	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
  reg        _R0_en_d0;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
  reg [15:0] _R0_addr_d0;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
  always @(posedge R0_clk) begin	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
    _R0_en_d0 <= R0_en;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
    _R0_addr_d0 <= R0_addr;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
  end // always @(posedge)
  reg        _R1_en_d0;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
  reg [15:0] _R1_addr_d0;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
  always @(posedge R1_clk) begin	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
    _R1_en_d0 <= R1_en;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
    _R1_addr_d0 <= R1_addr;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
    if (W0_en & 1'h1)	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
      Memory[W0_addr] <= W0_data;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
      reg [31:0] _RANDOM;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
      reg [31:0] _RANDOM_0;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
    initial begin	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
      `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
        for (logic [16:0] i = 17'h0; i < 17'h10000; i += 17'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
          Memory[i[15:0]] = _RANDOM_MEM[15:0];	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
        end	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
        _RANDOM = {`RANDOM};	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
        _RANDOM_0 = {`RANDOM};	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
        _R0_addr_d0 = _RANDOM[16:1];	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
        _R1_en_d0 = _RANDOM[17];	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
        _R1_addr_d0 = {_RANDOM[31:18], _RANDOM_0[1:0]};	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 16'bx;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
  assign R1_data = _R1_en_d0 ? Memory[_R1_addr_d0] : 16'bx;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :43:26
endmodule
