// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module BilinearSampler(	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
  input  clock,	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
  output io_valid,	// src/main/scala/scarf/compute/BilinearUnit.scala:23:14
  input  io_enable	// src/main/scala/scarf/compute/BilinearUnit.scala:23:14
);

  reg validP1;	// src/main/scala/scarf/compute/BilinearUnit.scala:67:24
  reg validP2;	// src/main/scala/scarf/compute/BilinearUnit.scala:78:26
  always @(posedge clock) begin	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
    validP1 <= io_enable;	// src/main/scala/scarf/compute/BilinearUnit.scala:67:24
    validP2 <= validP1;	// src/main/scala/scarf/compute/BilinearUnit.scala:67:24, :78:26
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
    initial begin	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
        end	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
        validP1 = _RANDOM[2'h3][2];	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7, :67:24
        validP2 = _RANDOM[2'h3][19];	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7, :67:24, :78:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid = validP2;	// src/main/scala/scarf/compute/BilinearUnit.scala:22:7, :78:26
endmodule
