// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module BilinearUnit(	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
  input  clock,	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
  output io_done,	// src/main/scala/scarf/compute/BilinearUnit.scala:93:14
         io_busy,	// src/main/scala/scarf/compute/BilinearUnit.scala:93:14
  input  io_enable	// src/main/scala/scarf/compute/BilinearUnit.scala:93:14
);

  wire _samplers_0_io_valid;	// src/main/scala/scarf/compute/BilinearUnit.scala:116:46
  reg  io_done_REG;	// src/main/scala/scarf/compute/BilinearUnit.scala:135:22
  always @(posedge clock)	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
    io_done_REG <= ~io_enable & _samplers_0_io_valid;	// src/main/scala/scarf/compute/BilinearUnit.scala:116:46, :135:{22,23,34}
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
    initial begin	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
        io_done_REG = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7, :135:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  BilinearSampler samplers_0 (	// src/main/scala/scarf/compute/BilinearUnit.scala:116:46
    .clock     (clock),
    .io_valid  (_samplers_0_io_valid),
    .io_enable (io_enable)
  );
  assign io_done = io_done_REG;	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7, :135:22
  assign io_busy = io_enable | _samplers_0_io_valid;	// src/main/scala/scarf/compute/BilinearUnit.scala:90:7, :116:46, :136:25
endmodule
