// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module ConfigRegs(	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
  input         clock,	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
                reset,	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
  input  [7:0]  io_writeAddr,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  input  [31:0] io_writeData,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  input         io_writeEn,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  input  [7:0]  io_readAddr,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [31:0] io_readData,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [7:0]  io_config_numDepthCandidates,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [8:0]  io_config_featureDim,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [9:0]  io_config_imageH,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_imageW,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [3:0]  io_config_tileSize,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [7:0]  io_config_cnnLayers,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [3:0]  io_config_transformerLayers,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [2:0]  io_config_shDegree,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output        io_config_hasDINOv2,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [5:0]  io_config_dinov2Layers,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [15:0] io_config_saesFeatureVarThresh,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_saesDepthStdThresh,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output        io_config_saesEnabled,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_fsdrEnabled,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [3:0]  io_config_fsdrHammingThresh,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [9:0]  io_config_fsdrDepthValidThresh,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [31:0] io_config_payloadBase,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [15:0] io_config_payloadTensorCount,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output [31:0] io_config_numGaussians,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_payloadFeatureOffset,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_payloadDepthOffset,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_payloadCandidateOffset,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_payloadProbabilityOffset,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_payloadFeatureBytes,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_payloadDepthBytes,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_payloadCandidateBytes,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_payloadProbabilityBytes,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_payloadSAESRouteOffset,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_config_payloadSAESRouteBytes,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
  output        io_config_payloadValid,	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
                io_configValid	// src/main/scala/scarf/control/ConfigRegs.scala:14:14
);

  reg  [7:0]  numDepthCandidates;	// src/main/scala/scarf/control/ConfigRegs.scala:24:35
  reg  [8:0]  featureDim;	// src/main/scala/scarf/control/ConfigRegs.scala:25:35
  reg  [9:0]  imageH;	// src/main/scala/scarf/control/ConfigRegs.scala:26:35
  reg  [9:0]  imageW;	// src/main/scala/scarf/control/ConfigRegs.scala:27:35
  reg  [3:0]  tileSize;	// src/main/scala/scarf/control/ConfigRegs.scala:28:35
  reg  [7:0]  cnnLayers;	// src/main/scala/scarf/control/ConfigRegs.scala:29:35
  reg  [3:0]  transformerLayers;	// src/main/scala/scarf/control/ConfigRegs.scala:30:35
  reg  [3:0]  normGroups;	// src/main/scala/scarf/control/ConfigRegs.scala:31:35
  reg  [2:0]  shDegree;	// src/main/scala/scarf/control/ConfigRegs.scala:32:35
  reg         hasDINOv2;	// src/main/scala/scarf/control/ConfigRegs.scala:33:35
  reg  [5:0]  dinov2Layers;	// src/main/scala/scarf/control/ConfigRegs.scala:34:35
  reg  [15:0] saesFeatureVar;	// src/main/scala/scarf/control/ConfigRegs.scala:35:35
  reg  [15:0] saesCrossCheck;	// src/main/scala/scarf/control/ConfigRegs.scala:36:35
  reg  [15:0] saesDepthStd;	// src/main/scala/scarf/control/ConfigRegs.scala:37:35
  reg         saesEnabled;	// src/main/scala/scarf/control/ConfigRegs.scala:38:35
  reg         fsdrEnabled;	// src/main/scala/scarf/control/ConfigRegs.scala:39:35
  reg  [9:0]  fsdrCacheSize;	// src/main/scala/scarf/control/ConfigRegs.scala:40:35
  reg  [3:0]  fsdrHammingThresh;	// src/main/scala/scarf/control/ConfigRegs.scala:41:35
  reg  [9:0]  fsdrDepthValidThresh;	// src/main/scala/scarf/control/ConfigRegs.scala:42:37
  reg  [31:0] payloadBase;	// src/main/scala/scarf/control/ConfigRegs.scala:43:35
  reg  [31:0] payloadBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35
  reg  [15:0] payloadTensorCount;	// src/main/scala/scarf/control/ConfigRegs.scala:45:35
  reg  [31:0] numGaussians;	// src/main/scala/scarf/control/ConfigRegs.scala:46:35
  reg  [31:0] payloadFeatureOffset;	// src/main/scala/scarf/control/ConfigRegs.scala:47:37
  reg  [31:0] payloadDepthOffset;	// src/main/scala/scarf/control/ConfigRegs.scala:48:35
  reg  [31:0] payloadCandidateOffset;	// src/main/scala/scarf/control/ConfigRegs.scala:49:39
  reg  [31:0] payloadProbabilityOffset;	// src/main/scala/scarf/control/ConfigRegs.scala:50:41
  reg  [31:0] payloadFeatureBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:51:36
  reg  [31:0] payloadDepthBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:52:34
  reg  [31:0] payloadCandidateBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:53:38
  reg  [31:0] payloadProbabilityBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:54:40
  reg  [31:0] payloadSAESRouteOffset;	// src/main/scala/scarf/control/ConfigRegs.scala:55:39
  reg  [31:0] payloadSAESRouteBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:56:38
  reg         payloadValid;	// src/main/scala/scarf/control/ConfigRegs.scala:57:35
  reg         configValidReg;	// src/main/scala/scarf/control/ConfigRegs.scala:58:35
  wire        _GEN = io_writeAddr == 8'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_0 = io_writeAddr == 8'h4;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_1 = io_writeAddr == 8'h8;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_2 = io_writeAddr == 8'hC;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_3 = io_writeAddr == 8'h10;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_4 = io_writeAddr == 8'h14;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_5 = io_writeAddr == 8'h18;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_6 = io_writeAddr == 8'h1C;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_7 = io_writeAddr == 8'h20;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_8 = io_writeAddr == 8'h24;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_9 = io_writeAddr == 8'h28;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_10 = io_writeAddr == 8'h2C;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_11 = io_writeAddr == 8'h30;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_12 = io_writeAddr == 8'h34;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_13 = io_writeAddr == 8'h38;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_14 = io_writeAddr == 8'h3C;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_15 = io_writeAddr == 8'h40;	// src/main/scala/scarf/control/ConfigRegs.scala:24:35, :61:26
  wire        _GEN_16 = io_writeAddr == 8'h44;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_17 = io_writeAddr == 8'h48;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_18 = io_writeAddr == 8'h4C;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_19 = io_writeAddr == 8'h50;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_20 = io_writeAddr == 8'h54;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_21 = io_writeAddr == 8'h58;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_22 = io_writeAddr == 8'h60;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_23 = io_writeAddr == 8'h64;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_24 = io_writeAddr == 8'h68;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_25 = io_writeAddr == 8'h6C;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_26 = io_writeAddr == 8'h70;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_27 = io_writeAddr == 8'h74;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_28 = io_writeAddr == 8'h78;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_29 = io_writeAddr == 8'h7C;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_30 = io_writeAddr == 8'h80;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_31 = io_writeAddr == 8'h84;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  wire        _GEN_32 = io_writeAddr == 8'h88;	// src/main/scala/scarf/control/ConfigRegs.scala:61:26
  always @(posedge clock) begin	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
    if (reset) begin	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
      numDepthCandidates <= 8'h40;	// src/main/scala/scarf/control/ConfigRegs.scala:24:35
      featureDim <= 9'h100;	// src/main/scala/scarf/control/ConfigRegs.scala:25:35
      imageH <= 10'h100;	// src/main/scala/scarf/control/ConfigRegs.scala:26:35
      imageW <= 10'h100;	// src/main/scala/scarf/control/ConfigRegs.scala:26:35, :27:35
      tileSize <= 4'h4;	// src/main/scala/scarf/control/ConfigRegs.scala:28:35
      cnnLayers <= 8'h6;	// src/main/scala/scarf/control/ConfigRegs.scala:29:35
      transformerLayers <= 4'h6;	// src/main/scala/scarf/control/ConfigRegs.scala:30:35
      normGroups <= 4'h8;	// src/main/scala/scarf/control/ConfigRegs.scala:31:35
      shDegree <= 3'h4;	// src/main/scala/scarf/control/ConfigRegs.scala:32:35
      hasDINOv2 <= 1'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:33:35
      dinov2Layers <= 6'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:34:35
      saesFeatureVar <= 16'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:35:35
      saesCrossCheck <= 16'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:35:35, :36:35
      saesDepthStd <= 16'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:35:35, :37:35
      saesEnabled <= 1'h1;	// src/main/scala/scarf/control/ConfigRegs.scala:38:35
      fsdrEnabled <= 1'h1;	// src/main/scala/scarf/control/ConfigRegs.scala:38:35, :39:35
      fsdrCacheSize <= 10'h200;	// src/main/scala/scarf/control/ConfigRegs.scala:40:35
      fsdrHammingThresh <= 4'h3;	// src/main/scala/scarf/control/ConfigRegs.scala:41:35
      fsdrDepthValidThresh <= 10'h66;	// src/main/scala/scarf/control/ConfigRegs.scala:42:37
      payloadBase <= 32'h80000000;	// src/main/scala/scarf/control/ConfigRegs.scala:43:35
      payloadBytes <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35
      payloadTensorCount <= 16'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:35:35, :45:35
      numGaussians <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :46:35
      payloadFeatureOffset <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :47:37
      payloadDepthOffset <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :48:35
      payloadCandidateOffset <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :49:39
      payloadProbabilityOffset <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :50:41
      payloadFeatureBytes <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :51:36
      payloadDepthBytes <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :52:34
      payloadCandidateBytes <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :53:38
      payloadProbabilityBytes <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :54:40
      payloadSAESRouteOffset <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :55:39
      payloadSAESRouteBytes <= 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :56:38
      payloadValid <= 1'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:33:35, :57:35
      configValidReg <= 1'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:33:35, :58:35
    end
    else begin	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
      if (io_writeEn & _GEN)	// src/main/scala/scarf/control/ConfigRegs.scala:24:35, :60:20, :61:26, :62:39
        numDepthCandidates <= io_writeData[7:0];	// src/main/scala/scarf/control/ConfigRegs.scala:24:35, :62:54
      if (~io_writeEn | _GEN | ~_GEN_0) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :60:20, :61:26
        featureDim <= io_writeData[8:0];	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :63:46
      if (~io_writeEn | _GEN | _GEN_0 | ~_GEN_1) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :26:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:26:35, :60:20, :61:26
        imageH <= io_writeData[9:0];	// src/main/scala/scarf/control/ConfigRegs.scala:26:35, :64:42
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | ~_GEN_2) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :27:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:27:35, :60:20, :61:26
        imageW <= io_writeData[9:0];	// src/main/scala/scarf/control/ConfigRegs.scala:27:35, :65:42
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | ~_GEN_3) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :28:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:28:35, :60:20, :61:26
        tileSize <= io_writeData[3:0];	// src/main/scala/scarf/control/ConfigRegs.scala:28:35, :66:44
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | ~_GEN_4) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :29:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:29:35, :60:20, :61:26
        cnnLayers <= io_writeData[7:0];	// src/main/scala/scarf/control/ConfigRegs.scala:29:35, :67:45
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | ~_GEN_5) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :30:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:30:35, :60:20, :61:26
        transformerLayers <= io_writeData[3:0];	// src/main/scala/scarf/control/ConfigRegs.scala:30:35, :68:53
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | ~_GEN_6) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :31:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:31:35, :60:20, :61:26
        normGroups <= io_writeData[3:0];	// src/main/scala/scarf/control/ConfigRegs.scala:31:35, :69:46
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | ~_GEN_7) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :32:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:32:35, :60:20, :61:26
        shDegree <= io_writeData[2:0];	// src/main/scala/scarf/control/ConfigRegs.scala:32:35, :70:44
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | ~_GEN_8) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :33:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:33:35, :60:20, :61:26
        hasDINOv2 <= io_writeData[0];	// src/main/scala/scarf/control/ConfigRegs.scala:33:35, :71:45
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | _GEN_23 | _GEN_24 | _GEN_25 | _GEN_26 | _GEN_27 | _GEN_28 | _GEN_29
          | _GEN_30 | ~_GEN_31) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :34:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:34:35, :60:20, :61:26
        dinov2Layers <= io_writeData[5:0];	// src/main/scala/scarf/control/ConfigRegs.scala:34:35, :94:48
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | ~_GEN_9) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :35:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:35:35, :60:20, :61:26
        saesFeatureVar <= io_writeData[15:0];	// src/main/scala/scarf/control/ConfigRegs.scala:35:35, :72:50
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | ~_GEN_10) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :36:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:36:35, :60:20, :61:26
        saesCrossCheck <= io_writeData[15:0];	// src/main/scala/scarf/control/ConfigRegs.scala:36:35, :73:50
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | ~_GEN_11) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :37:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:37:35, :60:20, :61:26
        saesDepthStd <= io_writeData[15:0];	// src/main/scala/scarf/control/ConfigRegs.scala:37:35, :74:48
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | ~_GEN_12) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :38:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:38:35, :60:20, :61:26
        saesEnabled <= io_writeData[0];	// src/main/scala/scarf/control/ConfigRegs.scala:38:35, :75:47
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12
          | ~_GEN_13) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :39:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:39:35, :60:20, :61:26
        fsdrEnabled <= io_writeData[0];	// src/main/scala/scarf/control/ConfigRegs.scala:39:35, :76:47
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | ~_GEN_14) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :40:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:40:35, :60:20, :61:26
        fsdrCacheSize <= io_writeData[9:0];	// src/main/scala/scarf/control/ConfigRegs.scala:40:35, :77:49
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | ~_GEN_15) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :41:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:41:35, :60:20, :61:26
        fsdrHammingThresh <= io_writeData[3:0];	// src/main/scala/scarf/control/ConfigRegs.scala:41:35, :78:53
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | ~_GEN_17) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :42:37, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:42:37, :60:20, :61:26
        fsdrDepthValidThresh <= io_writeData[9:0];	// src/main/scala/scarf/control/ConfigRegs.scala:42:37, :80:56
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | ~_GEN_18) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :43:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:43:35, :60:20, :61:26
        payloadBase <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:43:35
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | ~_GEN_19) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :44:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:44:35, :60:20, :61:26
        payloadBytes <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:44:35
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | ~_GEN_20) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :45:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:45:35, :60:20, :61:26
        payloadTensorCount <= io_writeData[15:0];	// src/main/scala/scarf/control/ConfigRegs.scala:45:35, :83:54
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20
          | ~_GEN_21) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :46:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:46:35, :60:20, :61:26
        numGaussians <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:46:35
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | ~_GEN_23) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :47:37, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:47:37, :60:20, :61:26
        payloadFeatureOffset <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:47:37
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | _GEN_23 | ~_GEN_24) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :48:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:48:35, :60:20, :61:26
        payloadDepthOffset <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:48:35
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | _GEN_23 | _GEN_24 | _GEN_25 | ~_GEN_26) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :49:39, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:49:39, :60:20, :61:26
        payloadCandidateOffset <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:49:39
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | _GEN_23 | _GEN_24 | ~_GEN_25) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :50:41, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:50:41, :60:20, :61:26
        payloadProbabilityOffset <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:50:41
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | _GEN_23 | _GEN_24 | _GEN_25 | _GEN_26 | ~_GEN_27) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :51:36, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:51:36, :60:20, :61:26
        payloadFeatureBytes <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:51:36
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | _GEN_23 | _GEN_24 | _GEN_25 | _GEN_26 | _GEN_27 | ~_GEN_28) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :52:34, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:52:34, :60:20, :61:26
        payloadDepthBytes <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:52:34
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | _GEN_23 | _GEN_24 | _GEN_25 | _GEN_26 | _GEN_27 | _GEN_28
          | ~_GEN_29) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :53:38, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:53:38, :60:20, :61:26
        payloadCandidateBytes <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:53:38
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | _GEN_23 | _GEN_24 | _GEN_25 | _GEN_26 | _GEN_27 | _GEN_28 | _GEN_29
          | ~_GEN_30) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :54:40, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:54:40, :60:20, :61:26
        payloadProbabilityBytes <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:54:40
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | _GEN_23 | _GEN_24 | _GEN_25 | _GEN_26 | _GEN_27 | _GEN_28 | _GEN_29
          | _GEN_30 | _GEN_31 | ~_GEN_32) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :55:39, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:55:39, :60:20, :61:26
        payloadSAESRouteOffset <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:55:39
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | _GEN_22 | _GEN_23 | _GEN_24 | _GEN_25 | _GEN_26 | _GEN_27 | _GEN_28 | _GEN_29
          | _GEN_30 | _GEN_31 | _GEN_32 | io_writeAddr != 8'h8C) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :56:38, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:56:38, :60:20, :61:26
        payloadSAESRouteBytes <= io_writeData;	// src/main/scala/scarf/control/ConfigRegs.scala:56:38
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21
          | ~_GEN_22) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :57:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:57:35, :60:20, :61:26
        payloadValid <= io_writeData[0];	// src/main/scala/scarf/control/ConfigRegs.scala:57:35, :85:48
      if (~io_writeEn | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
          | _GEN_14 | _GEN_15 | ~_GEN_16) begin	// src/main/scala/scarf/control/ConfigRegs.scala:25:35, :58:35, :60:20, :61:26
      end
      else	// src/main/scala/scarf/control/ConfigRegs.scala:58:35, :60:20, :61:26
        configValidReg <= io_writeData[0];	// src/main/scala/scarf/control/ConfigRegs.scala:58:35, :79:50
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:17];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
    initial begin	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
        for (logic [4:0] i = 5'h0; i < 5'h12; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
        end	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
        numDepthCandidates = _RANDOM[5'h0][7:0];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :24:35
        featureDim = _RANDOM[5'h0][16:8];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :24:35, :25:35
        imageH = _RANDOM[5'h0][26:17];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :24:35, :26:35
        imageW = {_RANDOM[5'h0][31:27], _RANDOM[5'h1][4:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :24:35, :27:35
        tileSize = _RANDOM[5'h1][8:5];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :27:35, :28:35
        cnnLayers = _RANDOM[5'h1][16:9];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :27:35, :29:35
        transformerLayers = _RANDOM[5'h1][20:17];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :27:35, :30:35
        normGroups = _RANDOM[5'h1][24:21];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :27:35, :31:35
        shDegree = _RANDOM[5'h1][27:25];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :27:35, :32:35
        hasDINOv2 = _RANDOM[5'h1][28];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :27:35, :33:35
        dinov2Layers = {_RANDOM[5'h1][31:29], _RANDOM[5'h2][2:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :27:35, :34:35
        saesFeatureVar = _RANDOM[5'h2][18:3];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :34:35, :35:35
        saesCrossCheck = {_RANDOM[5'h2][31:19], _RANDOM[5'h3][2:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :34:35, :36:35
        saesDepthStd = _RANDOM[5'h3][18:3];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :36:35, :37:35
        saesEnabled = _RANDOM[5'h3][19];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :36:35, :38:35
        fsdrEnabled = _RANDOM[5'h3][20];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :36:35, :39:35
        fsdrCacheSize = _RANDOM[5'h3][30:21];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :36:35, :40:35
        fsdrHammingThresh = {_RANDOM[5'h3][31], _RANDOM[5'h4][2:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :36:35, :41:35
        fsdrDepthValidThresh = _RANDOM[5'h4][12:3];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :41:35, :42:37
        payloadBase = {_RANDOM[5'h4][31:13], _RANDOM[5'h5][12:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :41:35, :43:35
        payloadBytes = {_RANDOM[5'h5][31:13], _RANDOM[5'h6][12:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :43:35, :44:35
        payloadTensorCount = _RANDOM[5'h6][28:13];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :44:35, :45:35
        numGaussians = {_RANDOM[5'h6][31:29], _RANDOM[5'h7][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :44:35, :46:35
        payloadFeatureOffset = {_RANDOM[5'h7][31:29], _RANDOM[5'h8][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :46:35, :47:37
        payloadDepthOffset = {_RANDOM[5'h8][31:29], _RANDOM[5'h9][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :47:37, :48:35
        payloadCandidateOffset = {_RANDOM[5'h9][31:29], _RANDOM[5'hA][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :48:35, :49:39
        payloadProbabilityOffset = {_RANDOM[5'hA][31:29], _RANDOM[5'hB][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :49:39, :50:41
        payloadFeatureBytes = {_RANDOM[5'hB][31:29], _RANDOM[5'hC][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :50:41, :51:36
        payloadDepthBytes = {_RANDOM[5'hC][31:29], _RANDOM[5'hD][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :51:36, :52:34
        payloadCandidateBytes = {_RANDOM[5'hD][31:29], _RANDOM[5'hE][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :52:34, :53:38
        payloadProbabilityBytes = {_RANDOM[5'hE][31:29], _RANDOM[5'hF][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :53:38, :54:40
        payloadSAESRouteOffset = {_RANDOM[5'hF][31:29], _RANDOM[5'h10][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :54:40, :55:39
        payloadSAESRouteBytes = {_RANDOM[5'h10][31:29], _RANDOM[5'h11][28:0]};	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :55:39, :56:38
        payloadValid = _RANDOM[5'h11][29];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :56:38, :57:35
        configValidReg = _RANDOM[5'h11][30];	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :56:38, :58:35
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/control/ConfigRegs.scala:13:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_readData =
    io_readAddr == 8'h0
      ? {24'h0, numDepthCandidates}
      : io_readAddr == 8'h4
          ? {23'h0, featureDim}
          : io_readAddr == 8'h8
              ? {22'h0, imageH}
              : io_readAddr == 8'hC
                  ? {22'h0, imageW}
                  : io_readAddr == 8'h10
                      ? {28'h0, tileSize}
                      : io_readAddr == 8'h14
                          ? {24'h0, cnnLayers}
                          : io_readAddr == 8'h18
                              ? {28'h0, transformerLayers}
                              : io_readAddr == 8'h1C
                                  ? {28'h0, normGroups}
                                  : io_readAddr == 8'h20
                                      ? {29'h0, shDegree}
                                      : io_readAddr == 8'h24
                                          ? {31'h0, hasDINOv2}
                                          : io_readAddr == 8'h28
                                              ? {16'h0, saesFeatureVar}
                                              : io_readAddr == 8'h2C
                                                  ? {16'h0, saesCrossCheck}
                                                  : io_readAddr == 8'h30
                                                      ? {16'h0, saesDepthStd}
                                                      : io_readAddr == 8'h34
                                                          ? {31'h0, saesEnabled}
                                                          : io_readAddr == 8'h38
                                                              ? {31'h0, fsdrEnabled}
                                                              : io_readAddr == 8'h3C
                                                                  ? {22'h0, fsdrCacheSize}
                                                                  : io_readAddr == 8'h40
                                                                      ? {28'h0,
                                                                         fsdrHammingThresh}
                                                                      : io_readAddr == 8'h44
                                                                          ? {31'h0,
                                                                             configValidReg}
                                                                          : io_readAddr == 8'h48
                                                                              ? {22'h0,
                                                                                 fsdrDepthValidThresh}
                                                                              : io_readAddr == 8'h4C
                                                                                  ? payloadBase
                                                                                  : io_readAddr == 8'h50
                                                                                      ? payloadBytes
                                                                                      : io_readAddr == 8'h54
                                                                                          ? {16'h0,
                                                                                             payloadTensorCount}
                                                                                          : io_readAddr == 8'h58
                                                                                              ? numGaussians
                                                                                              : io_readAddr == 8'h60
                                                                                                  ? {31'h0,
                                                                                                     payloadValid}
                                                                                                  : io_readAddr == 8'h64
                                                                                                      ? payloadFeatureOffset
                                                                                                      : io_readAddr == 8'h68
                                                                                                          ? payloadDepthOffset
                                                                                                          : io_readAddr == 8'h6C
                                                                                                              ? payloadProbabilityOffset
                                                                                                              : io_readAddr == 8'h70
                                                                                                                  ? payloadCandidateOffset
                                                                                                                  : io_readAddr == 8'h74
                                                                                                                      ? payloadFeatureBytes
                                                                                                                      : io_readAddr == 8'h78
                                                                                                                          ? payloadDepthBytes
                                                                                                                          : io_readAddr == 8'h7C
                                                                                                                              ? payloadCandidateBytes
                                                                                                                              : io_readAddr == 8'h80
                                                                                                                                  ? payloadProbabilityBytes
                                                                                                                                  : io_readAddr == 8'h84
                                                                                                                                      ? {26'h0,
                                                                                                                                         dinov2Layers}
                                                                                                                                      : io_readAddr == 8'h88
                                                                                                                                          ? payloadSAESRouteOffset
                                                                                                                                          : io_readAddr == 8'h8C
                                                                                                                                              ? payloadSAESRouteBytes
                                                                                                                                              : 32'h0;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :24:35, :25:35, :26:35, :27:35, :28:35, :29:35, :30:35, :31:35, :32:35, :33:35, :34:35, :35:35, :36:35, :37:35, :38:35, :39:35, :40:35, :41:35, :42:37, :43:35, :44:35, :45:35, :46:35, :47:37, :48:35, :49:39, :50:41, :51:36, :52:34, :53:38, :54:40, :55:39, :56:38, :57:35, :58:35, :61:26, :100:15, :101:23, :102:{30,36}, :103:{30,36}, :104:{30,36}, :105:{30,36}, :106:{30,36}, :107:{30,36}, :108:{30,36}, :109:{30,36}, :110:{30,36}, :111:{30,36}, :112:{30,36}, :113:{30,36}, :114:{30,36}, :115:{30,36}, :116:{30,36}, :117:{30,36}, :118:{30,36}, :119:{30,36}, :120:{30,36}, :121:30, :122:30, :123:{30,36}, :124:30, :125:{30,36}, :126:30, :127:30, :128:30, :129:30, :130:30, :131:30, :132:30, :133:30, :134:{30,36}, :135:30, :136:30
  assign io_config_numDepthCandidates = numDepthCandidates;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :24:35
  assign io_config_featureDim = featureDim;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :25:35
  assign io_config_imageH = imageH;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :26:35
  assign io_config_imageW = imageW;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :27:35
  assign io_config_tileSize = tileSize;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :28:35
  assign io_config_cnnLayers = cnnLayers;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :29:35
  assign io_config_transformerLayers = transformerLayers;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :30:35
  assign io_config_shDegree = shDegree;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :32:35
  assign io_config_hasDINOv2 = hasDINOv2;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :33:35
  assign io_config_dinov2Layers = dinov2Layers;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :34:35
  assign io_config_saesFeatureVarThresh = saesFeatureVar;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :35:35
  assign io_config_saesDepthStdThresh = saesDepthStd;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :37:35
  assign io_config_saesEnabled = saesEnabled;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :38:35
  assign io_config_fsdrEnabled = fsdrEnabled;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :39:35
  assign io_config_fsdrHammingThresh = fsdrHammingThresh;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :41:35
  assign io_config_fsdrDepthValidThresh = fsdrDepthValidThresh;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :42:37
  assign io_config_payloadBase = payloadBase;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :43:35
  assign io_config_payloadTensorCount = payloadTensorCount;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :45:35
  assign io_config_numGaussians = numGaussians;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :46:35
  assign io_config_payloadFeatureOffset = payloadFeatureOffset;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :47:37
  assign io_config_payloadDepthOffset = payloadDepthOffset;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :48:35
  assign io_config_payloadCandidateOffset = payloadCandidateOffset;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :49:39
  assign io_config_payloadProbabilityOffset = payloadProbabilityOffset;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :50:41
  assign io_config_payloadFeatureBytes = payloadFeatureBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :51:36
  assign io_config_payloadDepthBytes = payloadDepthBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :52:34
  assign io_config_payloadCandidateBytes = payloadCandidateBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :53:38
  assign io_config_payloadProbabilityBytes = payloadProbabilityBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :54:40
  assign io_config_payloadSAESRouteOffset = payloadSAESRouteOffset;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :55:39
  assign io_config_payloadSAESRouteBytes = payloadSAESRouteBytes;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :56:38
  assign io_config_payloadValid = payloadValid;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :57:35
  assign io_configValid = configValidReg;	// src/main/scala/scarf/control/ConfigRegs.scala:13:7, :58:35
endmodule
