// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module CovBuilder(	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
  input         clock,	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
                reset,	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
  input  [15:0] io_quatW,	// src/main/scala/scarf/ggu/CovBuilder.scala:20:14
                io_quatX,	// src/main/scala/scarf/ggu/CovBuilder.scala:20:14
                io_quatY,	// src/main/scala/scarf/ggu/CovBuilder.scala:20:14
                io_quatZ,	// src/main/scala/scarf/ggu/CovBuilder.scala:20:14
                io_scaleX,	// src/main/scala/scarf/ggu/CovBuilder.scala:20:14
                io_scaleY,	// src/main/scala/scarf/ggu/CovBuilder.scala:20:14
                io_scaleZ,	// src/main/scala/scarf/ggu/CovBuilder.scala:20:14
  input         io_start,	// src/main/scala/scarf/ggu/CovBuilder.scala:20:14
  output        io_done,	// src/main/scala/scarf/ggu/CovBuilder.scala:20:14
  output [31:0] io_cov_0	// src/main/scala/scarf/ggu/CovBuilder.scala:20:14
);

  reg  [2:0]  state;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22
  reg  [31:0] R_0;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:18
  reg  [31:0] R_1;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:18
  reg  [31:0] R_2;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:18
  reg  [31:0] s2_0;	// src/main/scala/scarf/ggu/CovBuilder.scala:43:19
  reg  [31:0] s2_1;	// src/main/scala/scarf/ggu/CovBuilder.scala:43:19
  reg  [31:0] s2_2;	// src/main/scala/scarf/ggu/CovBuilder.scala:43:19
  reg  [31:0] covReg_0;	// src/main/scala/scarf/ggu/CovBuilder.scala:45:23
  reg  [2:0]  casez_tmp;	// src/main/scala/scarf/ggu/CovBuilder.scala:51:17, :53:22
  always_comb begin	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:22, :60:13, :91:13, :105:13, :109:13
    casez (state)	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:22, :60:13, :91:13, :105:13, :109:13
      3'b000:
        casez_tmp = io_start ? 3'h1 : state;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:{22,30}, :60:13, :91:13, :105:13, :109:13
      3'b001:
        casez_tmp = 3'h2;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:22, :60:13, :91:13, :105:13, :109:13
      3'b010:
        casez_tmp = 3'h3;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:22, :60:13, :91:13, :105:13, :109:13
      3'b011:
        casez_tmp = 3'h4;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :47:25, :51:17, :53:22, :60:13, :91:13, :105:13, :109:13
      3'b100:
        casez_tmp = 3'h0;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:22, :60:13, :91:13, :105:13, :109:13
      3'b101:
        casez_tmp = state;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:22, :60:13, :91:13, :105:13, :109:13
      3'b110:
        casez_tmp = state;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:22, :60:13, :91:13, :105:13, :109:13
      default:
        casez_tmp = state;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:22, :60:13, :91:13, :105:13, :109:13
    endcase	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:22, :60:13, :91:13, :105:13, :109:13
  end // always_comb
  wire [30:0] _GEN = {15'h0, io_quatY};	// src/main/scala/scarf/ggu/CovBuilder.scala:70:19
  wire [30:0] _GEN_0 = {15'h0, io_quatZ};	// src/main/scala/scarf/ggu/CovBuilder.scala:70:19, :71:19
  wire [30:0] _GEN_1 = {15'h0, io_quatX};	// src/main/scala/scarf/ggu/CovBuilder.scala:70:19, :72:19
  wire [30:0] _GEN_2 = {15'h0, io_quatW};	// src/main/scala/scarf/ggu/CovBuilder.scala:70:19, :76:19
  wire [31:0] _GEN_3 = {16'h0, io_scaleX};	// src/main/scala/scarf/ggu/CovBuilder.scala:57:27
  wire [31:0] _GEN_4 = {16'h0, io_scaleY};	// src/main/scala/scarf/ggu/CovBuilder.scala:57:27, :58:27
  wire [31:0] _GEN_5 = {16'h0, io_scaleZ};	// src/main/scala/scarf/ggu/CovBuilder.scala:57:27, :59:27
  wire        _GEN_6 = state == 3'h0;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17
  wire        _GEN_7 = state == 3'h1;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:30
  wire        _GEN_8 = state == 3'h2;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :60:13
  always @(posedge clock) begin	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
    if (reset) begin	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
      state <= 3'h0;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22
      R_0 <= 32'h0;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:{18,26}
      R_1 <= 32'h0;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:{18,26}
      R_2 <= 32'h0;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:{18,26}
      s2_0 <= 32'h0;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:26, :43:19
      s2_1 <= 32'h0;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:26, :43:19
      s2_2 <= 32'h0;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:26, :43:19
      covReg_0 <= 32'h0;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:26, :45:23
    end
    else begin	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
      state <= casez_tmp;	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :51:17, :53:22
      if (_GEN_6 | _GEN_7 | ~_GEN_8) begin	// src/main/scala/scarf/ggu/CovBuilder.scala:41:18, :51:17
      end
      else begin	// src/main/scala/scarf/ggu/CovBuilder.scala:41:18, :51:17
        R_0 <= 32'h8000 - {_GEN * _GEN + _GEN_0 * _GEN_0, 1'h0};	// src/main/scala/scarf/ggu/CovBuilder.scala:41:18, :70:19, :71:19, :81:{19,31}
        R_1 <= {_GEN_1 * _GEN - _GEN_2 * _GEN_0, 1'h0};	// src/main/scala/scarf/ggu/CovBuilder.scala:41:18, :70:19, :71:19, :72:19, :76:19, :77:19, :81:31, :82:{12,25}
        R_2 <= {_GEN_1 * _GEN_0 + _GEN_2 * _GEN, 1'h0};	// src/main/scala/scarf/ggu/CovBuilder.scala:41:18, :70:19, :71:19, :72:19, :73:19, :76:19, :81:31, :83:{12,25}
      end
      if (_GEN_6 | ~_GEN_7) begin	// src/main/scala/scarf/ggu/CovBuilder.scala:43:19, :51:17
      end
      else begin	// src/main/scala/scarf/ggu/CovBuilder.scala:43:19, :51:17
        s2_0 <= _GEN_3 * _GEN_3;	// src/main/scala/scarf/ggu/CovBuilder.scala:43:19, :57:27
        s2_1 <= _GEN_4 * _GEN_4;	// src/main/scala/scarf/ggu/CovBuilder.scala:43:19, :58:27
        s2_2 <= _GEN_5 * _GEN_5;	// src/main/scala/scarf/ggu/CovBuilder.scala:43:19, :59:27
      end
      if (_GEN_6 | _GEN_7 | _GEN_8 | state != 3'h3) begin	// src/main/scala/scarf/ggu/CovBuilder.scala:38:22, :45:23, :51:17, :91:13
      end
      else	// src/main/scala/scarf/ggu/CovBuilder.scala:45:23, :51:17
        covReg_0 <= R_0 * s2_0 * R_0 + R_1 * s2_1 * R_1 + R_2 * s2_2 * R_2;	// src/main/scala/scarf/ggu/CovBuilder.scala:41:18, :43:19, :45:23, :100:42, :101:42, :102:42, :103:36
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:13];	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
    initial begin	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
        for (logic [3:0] i = 4'h0; i < 4'hE; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
        end	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
        state = _RANDOM[4'h0][2:0];	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7, :38:22
        R_0 = {_RANDOM[4'h0][31:3], _RANDOM[4'h1][2:0]};	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7, :38:22, :41:18
        R_1 = {_RANDOM[4'h1][31:3], _RANDOM[4'h2][2:0]};	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7, :41:18
        R_2 = {_RANDOM[4'h2][31:3], _RANDOM[4'h3][2:0]};	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7, :41:18
        s2_0 = {_RANDOM[4'h9][31:3], _RANDOM[4'hA][2:0]};	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7, :43:19
        s2_1 = {_RANDOM[4'hA][31:3], _RANDOM[4'hB][2:0]};	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7, :43:19
        s2_2 = {_RANDOM[4'hB][31:3], _RANDOM[4'hC][2:0]};	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7, :43:19
        covReg_0 = {_RANDOM[4'hC][31:3], _RANDOM[4'hD][2:0]};	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7, :43:19, :45:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_done = state == 3'h4;	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7, :38:22, :47:25
  assign io_cov_0 = covReg_0;	// src/main/scala/scarf/ggu/CovBuilder.scala:19:7, :45:23
endmodule
