// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module DRAMInterface(	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
  input          clock,	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
                 reset,	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
                 io_readReq_valid,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  input  [31:0]  io_readReq_bits_addr,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  output         io_readResp_valid,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  output [127:0] io_readResp_bits_data,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  input          io_writeReq_valid,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  input  [31:0]  io_writeReq_bits_addr,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  input  [127:0] io_writeReq_bits_data,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  output [31:0]  io_axiArAddr,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  output         io_axiArValid,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  input          io_axiArReady,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  input  [127:0] io_axiRData,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  input          io_axiRValid,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  output         io_axiRReady,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  input          io_axiRLast,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  output [31:0]  io_axiAwAddr,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  output         io_axiAwValid,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  input          io_axiAwReady,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  output [127:0] io_axiWData,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  output         io_axiWValid,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  input          io_axiWReady,	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
  output         io_axiWLast	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
);

  reg  [1:0]  rdState;	// src/main/scala/scarf/memory/DRAMInterface.scala:48:24
  reg  [31:0] rdAddr;	// src/main/scala/scarf/memory/DRAMInterface.scala:49:24
  wire        io_axiRReady_0 = rdState == 2'h2;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24, :54:32
  reg  [1:0]  wrState;	// src/main/scala/scarf/memory/DRAMInterface.scala:85:24
  reg  [31:0] wrAddr;	// src/main/scala/scarf/memory/DRAMInterface.scala:86:24
  reg  [7:0]  wrCount;	// src/main/scala/scarf/memory/DRAMInterface.scala:88:24
  wire        io_axiWValid_0 = wrState == 2'h2 & io_writeReq_valid;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :85:24, :97:{28,40}
  wire        io_axiWLast_0 = wrCount == 8'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14, :88:24, :98:28
  wire        _GEN = wrState == 2'h1;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :85:24, :100:19
  wire        _GEN_0 = wrState == 2'h2;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :85:24, :100:19
  wire        _GEN_1 = io_axiWReady & io_axiWValid_0;	// src/main/scala/scarf/memory/DRAMInterface.scala:97:40, :113:25
  wire        _GEN_2 = rdState == 2'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24, :62:19
  wire        _GEN_3 = wrState == 2'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :85:24, :100:19
  always @(posedge clock) begin	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
    if (reset) begin	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
      rdState <= 2'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24
      rdAddr <= 32'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:49:24
      wrState <= 2'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :85:24
      wrAddr <= 32'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:49:24, :86:24
      wrCount <= 8'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14, :88:24
    end
    else begin	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
      if (_GEN_2) begin	// src/main/scala/scarf/memory/DRAMInterface.scala:62:19
        if (io_readReq_valid)	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
          rdState <= 2'h1;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24
      end
      else if (rdState == 2'h1) begin	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24, :62:19
        if (io_axiArReady)	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
          rdState <= 2'h2;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24
      end
      else if (rdState == 2'h2 & io_axiRValid & io_axiRLast)	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24, :62:19, :75:47, :78:{27,37}
        rdState <= 2'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24
      if (_GEN_2 & io_readReq_valid)	// src/main/scala/scarf/memory/DRAMInterface.scala:49:24, :62:19, :64:30, :65:17
        rdAddr <= io_readReq_bits_addr;	// src/main/scala/scarf/memory/DRAMInterface.scala:49:24
      if (_GEN_3) begin	// src/main/scala/scarf/memory/DRAMInterface.scala:100:19
        if (io_writeReq_valid) begin	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
          wrState <= 2'h1;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :85:24
          wrCount <= 8'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14, :88:24
        end
      end
      else begin	// src/main/scala/scarf/memory/DRAMInterface.scala:100:19
        if (_GEN) begin	// src/main/scala/scarf/memory/DRAMInterface.scala:100:19
          if (io_axiAwReady)	// src/main/scala/scarf/memory/DRAMInterface.scala:19:14
            wrState <= 2'h2;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :85:24
        end
        else if (_GEN_0 & _GEN_1 & io_axiWLast_0)	// src/main/scala/scarf/memory/DRAMInterface.scala:85:24, :98:28, :100:19, :113:{25,42}, :115:33, :116:23
          wrState <= 2'h0;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :85:24
        if (_GEN | ~(_GEN_0 & _GEN_1)) begin	// src/main/scala/scarf/memory/DRAMInterface.scala:88:24, :100:19, :113:{25,42}, :114:17
        end
        else	// src/main/scala/scarf/memory/DRAMInterface.scala:88:24, :100:19
          wrCount <= wrCount + 8'h1;	// src/main/scala/scarf/memory/DRAMInterface.scala:88:24, :114:28
      end
      if (_GEN_3 & io_writeReq_valid)	// src/main/scala/scarf/memory/DRAMInterface.scala:86:24, :100:19, :102:31, :103:17
        wrAddr <= io_writeReq_bits_addr;	// src/main/scala/scarf/memory/DRAMInterface.scala:86:24
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
    initial begin	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
        end	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
        rdState = _RANDOM[2'h0][1:0];	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24
        rdAddr = {_RANDOM[2'h0][31:2], _RANDOM[2'h1][1:0]};	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24, :49:24
        wrState = _RANDOM[2'h1][19:18];	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :49:24, :85:24
        wrAddr = {_RANDOM[2'h1][31:20], _RANDOM[2'h2][19:0]};	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :49:24, :86:24
        wrCount = {_RANDOM[2'h2][31:28], _RANDOM[2'h3][3:0]};	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :86:24, :88:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_readResp_valid = io_axiRReady_0 & io_axiRValid;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :54:{32,44}
  assign io_readResp_bits_data = io_axiRData;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
  assign io_axiArAddr = rdAddr;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :49:24
  assign io_axiArValid = rdState == 2'h1;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :48:24, :59:28
  assign io_axiRReady = io_axiRReady_0;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :54:32
  assign io_axiAwAddr = wrAddr;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :86:24
  assign io_axiAwValid = wrState == 2'h1;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :85:24, :95:28
  assign io_axiWData = io_writeReq_bits_data;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7
  assign io_axiWValid = io_axiWValid_0;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :97:40
  assign io_axiWLast = io_axiWLast_0;	// src/main/scala/scarf/memory/DRAMInterface.scala:18:7, :98:28
endmodule
