// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module FeatureBuffer(	// src/main/scala/scarf/memory/FeatureBuffer.scala:15:7
  input         clock,	// src/main/scala/scarf/memory/FeatureBuffer.scala:15:7
  input  [16:0] io_addrA,	// src/main/scala/scarf/memory/FeatureBuffer.scala:21:14
  input  [15:0] io_dinA,	// src/main/scala/scarf/memory/FeatureBuffer.scala:21:14
  output [15:0] io_doutA,	// src/main/scala/scarf/memory/FeatureBuffer.scala:21:14
  input         io_wenA,	// src/main/scala/scarf/memory/FeatureBuffer.scala:21:14
                io_renA,	// src/main/scala/scarf/memory/FeatureBuffer.scala:21:14
  input  [16:0] io_addrB,	// src/main/scala/scarf/memory/FeatureBuffer.scala:21:14
  output [15:0] io_doutB,	// src/main/scala/scarf/memory/FeatureBuffer.scala:21:14
  input         io_renB,	// src/main/scala/scarf/memory/FeatureBuffer.scala:21:14
                io_bankSwap	// src/main/scala/scarf/memory/FeatureBuffer.scala:21:14
);

  wire [15:0] _bank1_ext_R0_data;	// src/main/scala/scarf/memory/FeatureBuffer.scala:43:26
  wire [15:0] _bank1_ext_R1_data;	// src/main/scala/scarf/memory/FeatureBuffer.scala:43:26
  wire [15:0] _bank0_ext_R0_data;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26
  wire [15:0] _bank0_ext_R1_data;	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26
  wire [16:0] addrA_bank = io_addrA % 17'h10000;	// src/main/scala/scarf/memory/FeatureBuffer.scala:48:29
  wire [16:0] addrB_bank = io_addrB % 17'h10000;	// src/main/scala/scarf/memory/FeatureBuffer.scala:48:29, :49:29
  bank_65536x16 bank0_ext (	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26
    .R0_addr (addrB_bank[15:0]),	// src/main/scala/scarf/memory/FeatureBuffer.scala:49:29, :71:43
    .R0_en   (io_renB),
    .R0_clk  (clock),
    .R0_data (_bank0_ext_R0_data),
    .R1_addr (addrA_bank[15:0]),	// src/main/scala/scarf/memory/FeatureBuffer.scala:48:29, :62:43
    .R1_en   (io_renA),
    .R1_clk  (clock),
    .R1_data (_bank0_ext_R1_data),
    .W0_addr (addrA_bank[15:0]),	// src/main/scala/scarf/memory/FeatureBuffer.scala:48:29, :58:35
    .W0_en   (io_wenA & ~io_bankSwap),	// src/main/scala/scarf/memory/FeatureBuffer.scala:42:26, :50:20, :57:17, :58:22
    .W0_clk  (clock),
    .W0_data (io_dinA)
  );
  bank_65536x16 bank1_ext (	// src/main/scala/scarf/memory/FeatureBuffer.scala:43:26
    .R0_addr (addrB_bank[15:0]),	// src/main/scala/scarf/memory/FeatureBuffer.scala:49:29, :71:67
    .R0_en   (io_renB),
    .R0_clk  (clock),
    .R0_data (_bank1_ext_R0_data),
    .R1_addr (addrA_bank[15:0]),	// src/main/scala/scarf/memory/FeatureBuffer.scala:48:29, :62:67
    .R1_en   (io_renA),
    .R1_clk  (clock),
    .R1_data (_bank1_ext_R1_data),
    .W0_addr (addrA_bank[15:0]),	// src/main/scala/scarf/memory/FeatureBuffer.scala:48:29, :58:35
    .W0_en   (io_wenA & io_bankSwap),	// src/main/scala/scarf/memory/FeatureBuffer.scala:43:26, :57:17, :58:22
    .W0_clk  (clock),
    .W0_data (io_dinA)
  );
  assign io_doutA =
    io_renA ? (io_bankSwap ? _bank1_ext_R1_data : _bank0_ext_R1_data) : 16'h0;	// src/main/scala/scarf/memory/FeatureBuffer.scala:15:7, :21:14, :42:26, :43:26, :53:12, :61:17, :62:{14,20}
  assign io_doutB =
    io_renB ? (io_bankSwap ? _bank0_ext_R0_data : _bank1_ext_R0_data) : 16'h0;	// src/main/scala/scarf/memory/FeatureBuffer.scala:15:7, :21:14, :42:26, :43:26, :54:12, :70:17, :71:{14,20}
endmodule
