// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module FSDRController(	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
  input         clock,	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
                reset,	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
                io_start,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  output        io_done,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  input  [7:0]  io_config_numDepthCandidates,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  input         io_config_fsdrEnabled,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  input  [9:0]  io_config_fsdrDepthValidThresh,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  output        io_hashStart,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  input         io_hashDone,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  input  [15:0] io_hashResult,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  output        io_cacheLookupEn,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  output [15:0] io_cacheLookupSig,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  input         io_cacheHit,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  input  [15:0] io_cacheHitDepth,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
                io_localDepthMean,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  input  [7:0]  io_localDepthCount,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  output        io_cacheInsertEn,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  output [15:0] io_cacheInsertSig,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
                io_cacheInsertDepth,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  output        io_useNarrowSearch,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  output [7:0]  io_narrowCandidates,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  input  [15:0] io_computedDepth,	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
  input         io_featureInformative	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
);

  wire        _localValidity_io_valid;	// src/main/scala/scarf/fsdr/FSDRController.scala:60:29
  reg  [3:0]  state;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22
  reg  [15:0] currentSig;	// src/main/scala/scarf/fsdr/FSDRController.scala:57:29
  reg         isNarrow;	// src/main/scala/scarf/fsdr/FSDRController.scala:58:29
  wire        _GEN = state == 4'h0;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :80:17, :133:13
  wire        _GEN_0 = state == 4'h1;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :80:17, :83:15
  wire        _GEN_1 = state == 4'h2;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :80:17, :94:15
  wire        _GEN_2 = state == 4'h3;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :80:17, :100:13
  wire        _GEN_3 = state == 4'h4;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :80:17, :106:21
  wire        _GEN_4 = state == 4'h5;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :80:17, :109:18
  wire        _GEN_5 = state == 4'h6;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :80:17, :113:13
  wire        _GEN_6 = _GEN_3 | _GEN_4;	// src/main/scala/scarf/fsdr/FSDRController.scala:73:22, :80:17
  wire        _GEN_7 = io_start & io_config_fsdrEnabled;	// src/main/scala/scarf/fsdr/FSDRController.scala:82:21
  wire        _GEN_8 = io_cacheHit & _localValidity_io_valid & io_featureInformative;	// src/main/scala/scarf/fsdr/FSDRController.scala:60:29, :103:50
  wire        _GEN_9 = state == 4'h7;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :80:17, :122:13
  wire        _GEN_10 = state == 4'h8;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :80:17, :126:50, :127:15, :129:15
  always @(posedge clock) begin	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
    if (reset) begin	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
      state <= 4'h0;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :133:13
      currentSig <= 16'h0;	// src/main/scala/scarf/fsdr/FSDRController.scala:57:29
      isNarrow <= 1'h0;	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :58:29
    end
    else begin	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
      if (_GEN) begin	// src/main/scala/scarf/fsdr/FSDRController.scala:80:17
        if (_GEN_7)	// src/main/scala/scarf/fsdr/FSDRController.scala:82:21
          state <= 4'h1;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :83:15
        else if (io_start & ~io_config_fsdrEnabled)	// src/main/scala/scarf/fsdr/FSDRController.scala:86:{27,30}
          state <= 4'h8;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :126:50, :127:15, :129:15
        isNarrow <= ~_GEN_7 & isNarrow;	// src/main/scala/scarf/fsdr/FSDRController.scala:58:29, :82:{21,47}, :85:18
      end
      else begin	// src/main/scala/scarf/fsdr/FSDRController.scala:80:17
        if (_GEN_0) begin	// src/main/scala/scarf/fsdr/FSDRController.scala:80:17
          if (io_hashDone)	// src/main/scala/scarf/fsdr/FSDRController.scala:19:14
            state <= 4'h2;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :94:15
        end
        else if (_GEN_1)	// src/main/scala/scarf/fsdr/FSDRController.scala:80:17
          state <= 4'h3;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :100:13
        else if (_GEN_2)	// src/main/scala/scarf/fsdr/FSDRController.scala:80:17
          state <= {3'h2, ~_GEN_8};	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :103:{50,76}, :106:21, :109:18
        else if (_GEN_6)	// src/main/scala/scarf/fsdr/FSDRController.scala:73:22, :80:17
          state <= 4'h6;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :113:13
        else if (_GEN_5)	// src/main/scala/scarf/fsdr/FSDRController.scala:80:17
          state <= 4'h7;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :122:13
        else if (_GEN_9)	// src/main/scala/scarf/fsdr/FSDRController.scala:80:17
          state <= 4'h8;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :126:50, :127:15, :129:15
        else if (_GEN_10)	// src/main/scala/scarf/fsdr/FSDRController.scala:80:17
          state <= 4'h0;	// src/main/scala/scarf/fsdr/FSDRController.scala:55:22, :133:13
        if (~(_GEN_0 | _GEN_1)) begin	// src/main/scala/scarf/fsdr/FSDRController.scala:58:29, :80:17
          if (_GEN_2)	// src/main/scala/scarf/fsdr/FSDRController.scala:80:17
            isNarrow <= _GEN_8;	// src/main/scala/scarf/fsdr/FSDRController.scala:58:29, :103:50
          else	// src/main/scala/scarf/fsdr/FSDRController.scala:80:17
            isNarrow <= (_GEN_3 | _GEN_4 | _GEN_5 | _GEN_9 | ~_GEN_10) & isNarrow;	// src/main/scala/scarf/fsdr/FSDRController.scala:58:29, :80:17, :134:16
        end
      end
      if (_GEN | ~(_GEN_0 & io_hashDone)) begin	// src/main/scala/scarf/fsdr/FSDRController.scala:57:29, :80:17, :92:25, :93:20
      end
      else	// src/main/scala/scarf/fsdr/FSDRController.scala:57:29, :80:17
        currentSig <= io_hashResult;	// src/main/scala/scarf/fsdr/FSDRController.scala:57:29
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
    initial begin	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
        state = _RANDOM[/*Zero width*/ 1'b0][3:0];	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :55:22
        currentSig = _RANDOM[/*Zero width*/ 1'b0][27:12];	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :55:22, :57:29
        isNarrow = _RANDOM[/*Zero width*/ 1'b0][28];	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :55:22, :58:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FSDRLocalDepthValidity localValidity (	// src/main/scala/scarf/fsdr/FSDRController.scala:60:29
    .io_cachedDepth     (io_cacheHitDepth),
    .io_localDepthMean  (io_localDepthMean),
    .io_localDepthCount (io_localDepthCount),
    .io_gammaQ10        (io_config_fsdrDepthValidThresh),
    .io_valid           (_localValidity_io_valid)
  );
  assign io_done = state == 4'h8;	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :55:22, :66:20, :126:50, :127:15, :129:15
  assign io_hashStart = ~_GEN & _GEN_0;	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :70:22, :80:17
  assign io_cacheLookupEn = ~(_GEN | _GEN_0) & _GEN_1;	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :71:22, :80:17
  assign io_cacheLookupSig = currentSig;	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :57:29
  assign io_cacheInsertEn = ~(_GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_6) & _GEN_5;	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :73:22, :80:17
  assign io_cacheInsertSig = currentSig;	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :57:29
  assign io_cacheInsertDepth = io_computedDepth;	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7
  assign io_useNarrowSearch = isNarrow;	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :58:29
  assign io_narrowCandidates = {2'h0, io_config_numDepthCandidates[7:2]};	// src/main/scala/scarf/fsdr/FSDRController.scala:18:7, :78:{24,56}
endmodule
