// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module FSDRLocalDepthValidity(	// src/main/scala/scarf/fsdr/FSDRLocalDepthValidity.scala:13:7
  input  [15:0] io_cachedDepth,	// src/main/scala/scarf/fsdr/FSDRLocalDepthValidity.scala:14:14
                io_localDepthMean,	// src/main/scala/scarf/fsdr/FSDRLocalDepthValidity.scala:14:14
  input  [7:0]  io_localDepthCount,	// src/main/scala/scarf/fsdr/FSDRLocalDepthValidity.scala:14:14
  input  [9:0]  io_gammaQ10,	// src/main/scala/scarf/fsdr/FSDRLocalDepthValidity.scala:14:14
  output        io_valid	// src/main/scala/scarf/fsdr/FSDRLocalDepthValidity.scala:14:14
);

  assign io_valid =
    io_localDepthCount < 8'h3 | io_localDepthMean == 16'h0
    | {io_cachedDepth >= io_localDepthMean
         ? io_cachedDepth - io_localDepthMean
         : io_localDepthMean - io_cachedDepth,
       10'h0} <= {10'h0, io_localDepthMean} * {16'h0, io_gammaQ10};	// src/main/scala/scarf/fsdr/FSDRLocalDepthValidity.scala:13:7, :22:23, :23:20, :24:20, :25:23, :27:37, :28:45, :29:34, :30:{23,31}, :31:22
endmodule
