// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module GGUArray(	// src/main/scala/scarf/ggu/GGUArray.scala:118:7
  input         clock,	// src/main/scala/scarf/ggu/GGUArray.scala:118:7
                reset,	// src/main/scala/scarf/ggu/GGUArray.scala:118:7
  input  [9:0]  io_pixelX_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_3,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_4,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_5,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_10,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_12,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_13,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_14,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_15,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_16,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_17,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_18,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_19,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_20,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_21,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_22,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_23,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_24,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_25,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_26,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_27,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_28,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_29,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_30,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelX_31,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_3,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_4,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_5,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_10,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_12,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_13,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_14,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_15,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_16,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_17,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_18,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_19,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_20,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_21,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_22,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_23,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_24,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_25,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_26,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_27,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_28,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_29,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_30,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_pixelY_31,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
  input  [15:0] io_depth_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_3,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_4,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_5,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_10,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_12,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_13,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_14,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_15,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_16,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_17,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_18,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_19,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_20,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_21,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_22,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_23,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_24,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_25,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_26,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_27,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_28,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_29,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_30,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_depth_31,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_3,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_4,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_5,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_10,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_12,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_13,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_14,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_15,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_16,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_17,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_18,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_19,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_20,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_21,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_22,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_23,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_24,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_25,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_26,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_27,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_28,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_29,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_30,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleX_31,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_3,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_4,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_5,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_10,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_12,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_13,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_14,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_15,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_16,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_17,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_18,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_19,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_20,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_21,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_22,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_23,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_24,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_25,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_26,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_27,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_28,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_29,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_30,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleY_31,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_3,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_4,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_5,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_10,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_12,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_13,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_14,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_15,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_16,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_17,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_18,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_19,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_20,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_21,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_22,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_23,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_24,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_25,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_26,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_27,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_28,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_29,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_30,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_scaleZ_31,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_3,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_4,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_5,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_10,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_12,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_13,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_14,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_15,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_16,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_17,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_18,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_19,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_20,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_21,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_22,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_23,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_24,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_25,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_26,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_27,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_28,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_29,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_30,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatW_31,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_3,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_4,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_5,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_10,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_12,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_13,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_14,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_15,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_16,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_17,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_18,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_19,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_20,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_21,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_22,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_23,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_24,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_25,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_26,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_27,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_28,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_29,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_30,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatX_31,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_3,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_4,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_5,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_10,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_12,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_13,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_14,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_15,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_16,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_17,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_18,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_19,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_20,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_21,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_22,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_23,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_24,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_25,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_26,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_27,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_28,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_29,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_30,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatY_31,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_3,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_4,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_5,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_10,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_12,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_13,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_14,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_15,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_16,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_17,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_18,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_19,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_20,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_21,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_22,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_23,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_24,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_25,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_26,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_27,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_28,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_29,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_30,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_quatZ_31,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
  input  [2:0]  io_shDegree,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
  input  [31:0] io_cx,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_cy,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_extrinsics_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_extrinsics_1,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_extrinsics_2,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_extrinsics_6,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_extrinsics_7,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_extrinsics_8,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_extrinsics_9,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_extrinsics_11,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
  input         io_start,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
  output        io_done,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
  output [31:0] io_posX_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_posZ_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
                io_cov_0_0,	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
  output [15:0] io_opacityOut_0	// src/main/scala/scarf/ggu/GGUArray.scala:119:14
);

  wire _pes_31_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_30_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_29_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_28_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_27_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_26_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_25_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_24_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_23_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_22_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_21_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_20_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_19_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_18_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_17_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_16_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_15_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_14_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_13_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_12_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_11_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_10_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_9_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_8_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_7_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_6_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_5_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_4_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_3_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_2_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_1_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  wire _pes_0_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
  GGUPE pes_0 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (10'h0),	// src/main/scala/scarf/ggu/GGUArray.scala:119:14, :152:36
    .io_pixelY        (10'h0),	// src/main/scala/scarf/ggu/GGUArray.scala:119:14, :152:36
    .io_depth         (io_depth_0),
    .io_scaleX        (io_scaleX_0),
    .io_scaleY        (io_scaleY_0),
    .io_scaleZ        (io_scaleZ_0),
    .io_quatW         (io_quatW_0),
    .io_quatX         (io_quatX_0),
    .io_quatY         (io_quatY_0),
    .io_quatZ         (io_quatZ_0),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_0_io_done),
    .io_posX          (io_posX_0),
    .io_posZ          (io_posZ_0),
    .io_cov_0         (io_cov_0_0),
    .io_opacityOut    (io_opacityOut_0)
  );
  GGUPE pes_1 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_1),
    .io_pixelY        (io_pixelY_1),
    .io_depth         (io_depth_1),
    .io_scaleX        (io_scaleX_1),
    .io_scaleY        (io_scaleY_1),
    .io_scaleZ        (io_scaleZ_1),
    .io_quatW         (io_quatW_1),
    .io_quatX         (io_quatX_1),
    .io_quatY         (io_quatY_1),
    .io_quatZ         (io_quatZ_1),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_1_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_2 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_2),
    .io_pixelY        (io_pixelY_2),
    .io_depth         (io_depth_2),
    .io_scaleX        (io_scaleX_2),
    .io_scaleY        (io_scaleY_2),
    .io_scaleZ        (io_scaleZ_2),
    .io_quatW         (io_quatW_2),
    .io_quatX         (io_quatX_2),
    .io_quatY         (io_quatY_2),
    .io_quatZ         (io_quatZ_2),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_2_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_3 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_3),
    .io_pixelY        (io_pixelY_3),
    .io_depth         (io_depth_3),
    .io_scaleX        (io_scaleX_3),
    .io_scaleY        (io_scaleY_3),
    .io_scaleZ        (io_scaleZ_3),
    .io_quatW         (io_quatW_3),
    .io_quatX         (io_quatX_3),
    .io_quatY         (io_quatY_3),
    .io_quatZ         (io_quatZ_3),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_3_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_4 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_4),
    .io_pixelY        (io_pixelY_4),
    .io_depth         (io_depth_4),
    .io_scaleX        (io_scaleX_4),
    .io_scaleY        (io_scaleY_4),
    .io_scaleZ        (io_scaleZ_4),
    .io_quatW         (io_quatW_4),
    .io_quatX         (io_quatX_4),
    .io_quatY         (io_quatY_4),
    .io_quatZ         (io_quatZ_4),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_4_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_5 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_5),
    .io_pixelY        (io_pixelY_5),
    .io_depth         (io_depth_5),
    .io_scaleX        (io_scaleX_5),
    .io_scaleY        (io_scaleY_5),
    .io_scaleZ        (io_scaleZ_5),
    .io_quatW         (io_quatW_5),
    .io_quatX         (io_quatX_5),
    .io_quatY         (io_quatY_5),
    .io_quatZ         (io_quatZ_5),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_5_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_6 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_6),
    .io_pixelY        (io_pixelY_6),
    .io_depth         (io_depth_6),
    .io_scaleX        (io_scaleX_6),
    .io_scaleY        (io_scaleY_6),
    .io_scaleZ        (io_scaleZ_6),
    .io_quatW         (io_quatW_6),
    .io_quatX         (io_quatX_6),
    .io_quatY         (io_quatY_6),
    .io_quatZ         (io_quatZ_6),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_6_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_7 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_7),
    .io_pixelY        (io_pixelY_7),
    .io_depth         (io_depth_7),
    .io_scaleX        (io_scaleX_7),
    .io_scaleY        (io_scaleY_7),
    .io_scaleZ        (io_scaleZ_7),
    .io_quatW         (io_quatW_7),
    .io_quatX         (io_quatX_7),
    .io_quatY         (io_quatY_7),
    .io_quatZ         (io_quatZ_7),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_7_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_8 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_8),
    .io_pixelY        (io_pixelY_8),
    .io_depth         (io_depth_8),
    .io_scaleX        (io_scaleX_8),
    .io_scaleY        (io_scaleY_8),
    .io_scaleZ        (io_scaleZ_8),
    .io_quatW         (io_quatW_8),
    .io_quatX         (io_quatX_8),
    .io_quatY         (io_quatY_8),
    .io_quatZ         (io_quatZ_8),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_8_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_9 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_9),
    .io_pixelY        (io_pixelY_9),
    .io_depth         (io_depth_9),
    .io_scaleX        (io_scaleX_9),
    .io_scaleY        (io_scaleY_9),
    .io_scaleZ        (io_scaleZ_9),
    .io_quatW         (io_quatW_9),
    .io_quatX         (io_quatX_9),
    .io_quatY         (io_quatY_9),
    .io_quatZ         (io_quatZ_9),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_9_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_10 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_10),
    .io_pixelY        (io_pixelY_10),
    .io_depth         (io_depth_10),
    .io_scaleX        (io_scaleX_10),
    .io_scaleY        (io_scaleY_10),
    .io_scaleZ        (io_scaleZ_10),
    .io_quatW         (io_quatW_10),
    .io_quatX         (io_quatX_10),
    .io_quatY         (io_quatY_10),
    .io_quatZ         (io_quatZ_10),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_10_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_11 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_11),
    .io_pixelY        (io_pixelY_11),
    .io_depth         (io_depth_11),
    .io_scaleX        (io_scaleX_11),
    .io_scaleY        (io_scaleY_11),
    .io_scaleZ        (io_scaleZ_11),
    .io_quatW         (io_quatW_11),
    .io_quatX         (io_quatX_11),
    .io_quatY         (io_quatY_11),
    .io_quatZ         (io_quatZ_11),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_11_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_12 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_12),
    .io_pixelY        (io_pixelY_12),
    .io_depth         (io_depth_12),
    .io_scaleX        (io_scaleX_12),
    .io_scaleY        (io_scaleY_12),
    .io_scaleZ        (io_scaleZ_12),
    .io_quatW         (io_quatW_12),
    .io_quatX         (io_quatX_12),
    .io_quatY         (io_quatY_12),
    .io_quatZ         (io_quatZ_12),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_12_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_13 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_13),
    .io_pixelY        (io_pixelY_13),
    .io_depth         (io_depth_13),
    .io_scaleX        (io_scaleX_13),
    .io_scaleY        (io_scaleY_13),
    .io_scaleZ        (io_scaleZ_13),
    .io_quatW         (io_quatW_13),
    .io_quatX         (io_quatX_13),
    .io_quatY         (io_quatY_13),
    .io_quatZ         (io_quatZ_13),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_13_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_14 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_14),
    .io_pixelY        (io_pixelY_14),
    .io_depth         (io_depth_14),
    .io_scaleX        (io_scaleX_14),
    .io_scaleY        (io_scaleY_14),
    .io_scaleZ        (io_scaleZ_14),
    .io_quatW         (io_quatW_14),
    .io_quatX         (io_quatX_14),
    .io_quatY         (io_quatY_14),
    .io_quatZ         (io_quatZ_14),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_14_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_15 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_15),
    .io_pixelY        (io_pixelY_15),
    .io_depth         (io_depth_15),
    .io_scaleX        (io_scaleX_15),
    .io_scaleY        (io_scaleY_15),
    .io_scaleZ        (io_scaleZ_15),
    .io_quatW         (io_quatW_15),
    .io_quatX         (io_quatX_15),
    .io_quatY         (io_quatY_15),
    .io_quatZ         (io_quatZ_15),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_15_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_16 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_16),
    .io_pixelY        (io_pixelY_16),
    .io_depth         (io_depth_16),
    .io_scaleX        (io_scaleX_16),
    .io_scaleY        (io_scaleY_16),
    .io_scaleZ        (io_scaleZ_16),
    .io_quatW         (io_quatW_16),
    .io_quatX         (io_quatX_16),
    .io_quatY         (io_quatY_16),
    .io_quatZ         (io_quatZ_16),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_16_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_17 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_17),
    .io_pixelY        (io_pixelY_17),
    .io_depth         (io_depth_17),
    .io_scaleX        (io_scaleX_17),
    .io_scaleY        (io_scaleY_17),
    .io_scaleZ        (io_scaleZ_17),
    .io_quatW         (io_quatW_17),
    .io_quatX         (io_quatX_17),
    .io_quatY         (io_quatY_17),
    .io_quatZ         (io_quatZ_17),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_17_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_18 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_18),
    .io_pixelY        (io_pixelY_18),
    .io_depth         (io_depth_18),
    .io_scaleX        (io_scaleX_18),
    .io_scaleY        (io_scaleY_18),
    .io_scaleZ        (io_scaleZ_18),
    .io_quatW         (io_quatW_18),
    .io_quatX         (io_quatX_18),
    .io_quatY         (io_quatY_18),
    .io_quatZ         (io_quatZ_18),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_18_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_19 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_19),
    .io_pixelY        (io_pixelY_19),
    .io_depth         (io_depth_19),
    .io_scaleX        (io_scaleX_19),
    .io_scaleY        (io_scaleY_19),
    .io_scaleZ        (io_scaleZ_19),
    .io_quatW         (io_quatW_19),
    .io_quatX         (io_quatX_19),
    .io_quatY         (io_quatY_19),
    .io_quatZ         (io_quatZ_19),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_19_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_20 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_20),
    .io_pixelY        (io_pixelY_20),
    .io_depth         (io_depth_20),
    .io_scaleX        (io_scaleX_20),
    .io_scaleY        (io_scaleY_20),
    .io_scaleZ        (io_scaleZ_20),
    .io_quatW         (io_quatW_20),
    .io_quatX         (io_quatX_20),
    .io_quatY         (io_quatY_20),
    .io_quatZ         (io_quatZ_20),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_20_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_21 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_21),
    .io_pixelY        (io_pixelY_21),
    .io_depth         (io_depth_21),
    .io_scaleX        (io_scaleX_21),
    .io_scaleY        (io_scaleY_21),
    .io_scaleZ        (io_scaleZ_21),
    .io_quatW         (io_quatW_21),
    .io_quatX         (io_quatX_21),
    .io_quatY         (io_quatY_21),
    .io_quatZ         (io_quatZ_21),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_21_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_22 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_22),
    .io_pixelY        (io_pixelY_22),
    .io_depth         (io_depth_22),
    .io_scaleX        (io_scaleX_22),
    .io_scaleY        (io_scaleY_22),
    .io_scaleZ        (io_scaleZ_22),
    .io_quatW         (io_quatW_22),
    .io_quatX         (io_quatX_22),
    .io_quatY         (io_quatY_22),
    .io_quatZ         (io_quatZ_22),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_22_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_23 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_23),
    .io_pixelY        (io_pixelY_23),
    .io_depth         (io_depth_23),
    .io_scaleX        (io_scaleX_23),
    .io_scaleY        (io_scaleY_23),
    .io_scaleZ        (io_scaleZ_23),
    .io_quatW         (io_quatW_23),
    .io_quatX         (io_quatX_23),
    .io_quatY         (io_quatY_23),
    .io_quatZ         (io_quatZ_23),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_23_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_24 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_24),
    .io_pixelY        (io_pixelY_24),
    .io_depth         (io_depth_24),
    .io_scaleX        (io_scaleX_24),
    .io_scaleY        (io_scaleY_24),
    .io_scaleZ        (io_scaleZ_24),
    .io_quatW         (io_quatW_24),
    .io_quatX         (io_quatX_24),
    .io_quatY         (io_quatY_24),
    .io_quatZ         (io_quatZ_24),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_24_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_25 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_25),
    .io_pixelY        (io_pixelY_25),
    .io_depth         (io_depth_25),
    .io_scaleX        (io_scaleX_25),
    .io_scaleY        (io_scaleY_25),
    .io_scaleZ        (io_scaleZ_25),
    .io_quatW         (io_quatW_25),
    .io_quatX         (io_quatX_25),
    .io_quatY         (io_quatY_25),
    .io_quatZ         (io_quatZ_25),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_25_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_26 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_26),
    .io_pixelY        (io_pixelY_26),
    .io_depth         (io_depth_26),
    .io_scaleX        (io_scaleX_26),
    .io_scaleY        (io_scaleY_26),
    .io_scaleZ        (io_scaleZ_26),
    .io_quatW         (io_quatW_26),
    .io_quatX         (io_quatX_26),
    .io_quatY         (io_quatY_26),
    .io_quatZ         (io_quatZ_26),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_26_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_27 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_27),
    .io_pixelY        (io_pixelY_27),
    .io_depth         (io_depth_27),
    .io_scaleX        (io_scaleX_27),
    .io_scaleY        (io_scaleY_27),
    .io_scaleZ        (io_scaleZ_27),
    .io_quatW         (io_quatW_27),
    .io_quatX         (io_quatX_27),
    .io_quatY         (io_quatY_27),
    .io_quatZ         (io_quatZ_27),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_27_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_28 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_28),
    .io_pixelY        (io_pixelY_28),
    .io_depth         (io_depth_28),
    .io_scaleX        (io_scaleX_28),
    .io_scaleY        (io_scaleY_28),
    .io_scaleZ        (io_scaleZ_28),
    .io_quatW         (io_quatW_28),
    .io_quatX         (io_quatX_28),
    .io_quatY         (io_quatY_28),
    .io_quatZ         (io_quatZ_28),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_28_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_29 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_29),
    .io_pixelY        (io_pixelY_29),
    .io_depth         (io_depth_29),
    .io_scaleX        (io_scaleX_29),
    .io_scaleY        (io_scaleY_29),
    .io_scaleZ        (io_scaleZ_29),
    .io_quatW         (io_quatW_29),
    .io_quatX         (io_quatX_29),
    .io_quatY         (io_quatY_29),
    .io_quatZ         (io_quatZ_29),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_29_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_30 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_30),
    .io_pixelY        (io_pixelY_30),
    .io_depth         (io_depth_30),
    .io_scaleX        (io_scaleX_30),
    .io_scaleY        (io_scaleY_30),
    .io_scaleZ        (io_scaleZ_30),
    .io_quatW         (io_quatW_30),
    .io_quatX         (io_quatX_30),
    .io_quatY         (io_quatY_30),
    .io_quatZ         (io_quatZ_30),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_30_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  GGUPE pes_31 (	// src/main/scala/scarf/ggu/GGUArray.scala:152:36
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX_31),
    .io_pixelY        (io_pixelY_31),
    .io_depth         (io_depth_31),
    .io_scaleX        (io_scaleX_31),
    .io_scaleY        (io_scaleY_31),
    .io_scaleZ        (io_scaleZ_31),
    .io_quatW         (io_quatW_31),
    .io_quatX         (io_quatX_31),
    .io_quatY         (io_quatY_31),
    .io_quatZ         (io_quatZ_31),
    .io_shDegree      (io_shDegree),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (io_start),
    .io_done          (_pes_31_io_done),
    .io_posX          (/* unused */),
    .io_posZ          (/* unused */),
    .io_cov_0         (/* unused */),
    .io_opacityOut    (/* unused */)
  );
  assign io_done =
    _pes_0_io_done & _pes_1_io_done & _pes_2_io_done & _pes_3_io_done & _pes_4_io_done
    & _pes_5_io_done & _pes_6_io_done & _pes_7_io_done & _pes_8_io_done & _pes_9_io_done
    & _pes_10_io_done & _pes_11_io_done & _pes_12_io_done & _pes_13_io_done
    & _pes_14_io_done & _pes_15_io_done & _pes_16_io_done & _pes_17_io_done
    & _pes_18_io_done & _pes_19_io_done & _pes_20_io_done & _pes_21_io_done
    & _pes_22_io_done & _pes_23_io_done & _pes_24_io_done & _pes_25_io_done
    & _pes_26_io_done & _pes_27_io_done & _pes_28_io_done & _pes_29_io_done
    & _pes_30_io_done & _pes_31_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:118:7, :152:36, :183:42
endmodule
