// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module GGUPE(	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
  input         clock,	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
                reset,	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
  input  [9:0]  io_pixelX,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_pixelY,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
  input  [15:0] io_depth,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_scaleX,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_scaleY,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_scaleZ,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_quatW,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_quatX,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_quatY,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_quatZ,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
  input  [2:0]  io_shDegree,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
  input  [31:0] io_cx,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_cy,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_extrinsics_0,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_extrinsics_1,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_extrinsics_2,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_extrinsics_6,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_extrinsics_7,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_extrinsics_8,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_extrinsics_9,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_extrinsics_11,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
  input         io_start,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
  output        io_done,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
  output [31:0] io_posX,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_posZ,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
                io_cov_0,	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
  output [15:0] io_opacityOut	// src/main/scala/scarf/ggu/GGUArray.scala:15:14
);

  wire       _shOpGen_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:51:23
  wire       _covBld_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:50:23
  wire       _posCalc_io_done;	// src/main/scala/scarf/ggu/GGUArray.scala:49:23
  reg  [2:0] state;	// src/main/scala/scarf/ggu/GGUArray.scala:54:22
  reg  [2:0] casez_tmp;	// src/main/scala/scarf/ggu/GGUArray.scala:94:17, :96:22
  always_comb begin	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :94:17, :96:22, :99:29, :102:28, :105:29, :108:13
    casez (state)	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :94:17, :96:22, :99:29, :102:28, :105:29, :108:13
      3'b000:
        casez_tmp = io_start ? 3'h1 : state;	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :65:34, :94:17, :96:{22,30}, :99:29, :102:28, :105:29, :108:13
      3'b001:
        casez_tmp = _posCalc_io_done ? 3'h2 : state;	// src/main/scala/scarf/ggu/GGUArray.scala:49:23, :54:22, :75:29, :94:17, :96:22, :99:{29,37}, :102:28, :105:29, :108:13
      3'b010:
        casez_tmp = _covBld_io_done ? 3'h3 : state;	// src/main/scala/scarf/ggu/GGUArray.scala:50:23, :54:22, :82:33, :94:17, :96:22, :99:29, :102:{28,36}, :105:29, :108:13
      3'b011:
        casez_tmp = _shOpGen_io_done ? 3'h4 : state;	// src/main/scala/scarf/ggu/GGUArray.scala:51:23, :54:22, :91:26, :94:17, :96:22, :99:29, :102:28, :105:{29,37}, :108:13
      3'b100:
        casez_tmp = 3'h0;	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :94:17, :96:22, :99:29, :102:28, :105:29, :108:13
      3'b101:
        casez_tmp = state;	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :94:17, :96:22, :99:29, :102:28, :105:29, :108:13
      3'b110:
        casez_tmp = state;	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :94:17, :96:22, :99:29, :102:28, :105:29, :108:13
      default:
        casez_tmp = state;	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :94:17, :96:22, :99:29, :102:28, :105:29, :108:13
    endcase	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :94:17, :96:22, :99:29, :102:28, :105:29, :108:13
  end // always_comb
  always @(posedge clock) begin	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
    if (reset)	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
      state <= 3'h0;	// src/main/scala/scarf/ggu/GGUArray.scala:54:22
    else	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
      state <= casez_tmp;	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :94:17, :96:22
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
    initial begin	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
        state = _RANDOM[/*Zero width*/ 1'b0][2:0];	// src/main/scala/scarf/ggu/GGUArray.scala:14:7, :54:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/ggu/GGUArray.scala:14:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  PositionCalc posCalc (	// src/main/scala/scarf/ggu/GGUArray.scala:49:23
    .clock            (clock),
    .reset            (reset),
    .io_pixelX        (io_pixelX),
    .io_pixelY        (io_pixelY),
    .io_depth         (io_depth),
    .io_cx            (io_cx),
    .io_cy            (io_cy),
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (state == 3'h1),	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :65:34
    .io_done          (_posCalc_io_done),
    .io_posX          (io_posX),
    .io_posZ          (io_posZ)
  );
  CovBuilder covBld (	// src/main/scala/scarf/ggu/GGUArray.scala:50:23
    .clock     (clock),
    .reset     (reset),
    .io_quatW  (io_quatW),
    .io_quatX  (io_quatX),
    .io_quatY  (io_quatY),
    .io_quatZ  (io_quatZ),
    .io_scaleX (io_scaleX),
    .io_scaleY (io_scaleY),
    .io_scaleZ (io_scaleZ),
    .io_start  (state == 3'h2),	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :75:29
    .io_done   (_covBld_io_done),
    .io_cov_0  (io_cov_0)
  );
  SHOPGenerator shOpGen (	// src/main/scala/scarf/ggu/GGUArray.scala:51:23
    .clock         (clock),
    .reset         (reset),
    .io_shDegree   (io_shDegree),
    .io_start      (state == 3'h3),	// src/main/scala/scarf/ggu/GGUArray.scala:54:22, :82:33
    .io_done       (_shOpGen_io_done),
    .io_opacityOut (io_opacityOut)
  );
  assign io_done = state == 3'h4;	// src/main/scala/scarf/ggu/GGUArray.scala:14:7, :54:22, :91:26
endmodule
