// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// VCS coverage exclude_file
module mem_1365x768(	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
  input  [10:0]  R0_addr,
  input          R0_en,
                 R0_clk,
  output [767:0] R0_data,
  input  [10:0]  W0_addr,
  input          W0_en,
                 W0_clk,
  input  [767:0] W0_data
);

  reg [767:0] Memory[0:1364];	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
  reg         _R0_en_d0;	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
  reg [10:0]  _R0_addr_d0;	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
  always @(posedge R0_clk) begin	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
    _R0_en_d0 <= R0_en;	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
    _R0_addr_d0 <= R0_addr;	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
    if (W0_en & 1'h1)	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
      Memory[W0_addr] <= W0_data;	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
      reg [31:0] _RANDOM;	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
    `endif // RANDOMIZE_REG_INIT
    reg [767:0] _RANDOM_MEM;	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
    initial begin	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
      `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
        for (logic [10:0] i = 11'h0; i < 11'h555; i += 11'h1) begin
          for (logic [9:0] j = 10'h0; j < 10'h300; j += 10'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
          end	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
          Memory[i] = _RANDOM_MEM;	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
        end	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
        _RANDOM = {`RANDOM};	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
        _R0_addr_d0 = _RANDOM[11:1];	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 768'bx;	// src/main/scala/scarf/memory/WeightBuffer.scala:34:24
endmodule
