// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module MMCU(	// src/main/scala/scarf/compute/MMCU.scala:65:7
  input         clock,	// src/main/scala/scarf/compute/MMCU.scala:65:7
                reset,	// src/main/scala/scarf/compute/MMCU.scala:65:7
                io_start,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  output        io_done,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_busy,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  input  [1:0]  io_mode,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  input  [15:0] io_M,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_K,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_N,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  input  [9:0]  io_inChannels,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_outChannels,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  output [31:0] io_aAddr,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  input  [15:0] io_aData_0,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_1,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_2,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_3,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_4,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_5,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_6,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_7,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_8,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_9,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_10,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_11,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_12,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_13,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_14,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_15,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_16,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_17,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_18,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_19,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_20,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_21,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_22,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_23,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_24,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_25,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_26,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_27,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_28,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_29,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_30,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_31,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_32,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_33,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_34,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_35,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_36,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_37,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_38,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_39,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_40,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_41,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_42,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_43,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_44,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_45,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_46,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_aData_47,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  output [31:0] io_bAddr,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  input  [15:0] io_bData_0,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  output [31:0] io_cAddr,	// src/main/scala/scarf/compute/MMCU.scala:66:14
                io_cData_0,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  output        io_cWr,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  input  [15:0] io_biasData_0,	// src/main/scala/scarf/compute/MMCU.scala:66:14
  output [31:0] io_weightAddr	// src/main/scala/scarf/compute/MMCU.scala:66:14
);

  wire [31:0] _array_io_results_0_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_1_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_2_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_3_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_4_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_5_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_6_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_7_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_8_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_9_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_10_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_11_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_12_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_13_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_14_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_15_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_16_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_17_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_18_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_19_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_20_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_21_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_22_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_23_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_24_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_25_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_26_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_27_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_28_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_29_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_30_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_31_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_32_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_33_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_34_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_35_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_36_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_37_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_38_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_39_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_40_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_41_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_42_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_43_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_44_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_45_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_46_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  wire [31:0] _array_io_results_47_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21
  reg  [1:0]  state;	// src/main/scala/scarf/compute/MMCU.scala:102:22
  reg  [9:0]  mTile;	// src/main/scala/scarf/compute/MMCU.scala:105:22
  reg  [9:0]  nTile;	// src/main/scala/scarf/compute/MMCU.scala:106:22
  reg  [15:0] kStep;	// src/main/scala/scarf/compute/MMCU.scala:107:22
  wire        _io_weightAddr_T = io_mode == 2'h0;	// src/main/scala/scarf/compute/MMCU.scala:113:23, :253:17
  wire [15:0] _GEN = {6'h0, io_outChannels};	// src/main/scala/scarf/compute/MMCU.scala:114:23, :133:25
  wire [15:0] effM = _io_weightAddr_T ? _GEN : io_M;	// src/main/scala/scarf/compute/MMCU.scala:113:{14,23}, :114:23
  wire [15:0] _effK_T_3 =
    _io_weightAddr_T ? {2'h0, {4'h0, io_inChannels} * 14'h3} * 16'h3 : io_K;	// src/main/scala/scarf/compute/MMCU.scala:113:23, :116:14, :117:{20,36}, :253:17
  wire [15:0] effN = _io_weightAddr_T ? _GEN : io_N;	// src/main/scala/scarf/compute/MMCU.scala:113:23, :114:23, :119:14
  wire [15:0] totalKSteps = (_effK_T_3 + 16'h2F) / 16'h30;	// src/main/scala/scarf/compute/MMCU.scala:116:14, :123:{27,48}, :125:{27,48}
  reg  [31:0] outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_1_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_2_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_3_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_4_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_5_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_6_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_7_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_8_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_9_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_10_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_11_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_12_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_13_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_14_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_15_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_16_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_17_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_18_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_19_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_20_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_21_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_22_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_23_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_24_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_25_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_26_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_27_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_28_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_29_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_30_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_31_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_32_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_33_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_34_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_35_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_36_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_37_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_38_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_39_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_40_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_41_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_42_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_43_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_44_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_45_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_46_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [31:0] outBufReg_47_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22
  reg  [9:0]  snapMTile;	// src/main/scala/scarf/compute/MMCU.scala:129:26
  reg  [9:0]  snapNTile;	// src/main/scala/scarf/compute/MMCU.scala:130:26
  reg  [5:0]  snapRows;	// src/main/scala/scarf/compute/MMCU.scala:133:25
  reg         dmaActive;	// src/main/scala/scarf/compute/MMCU.scala:136:26
  reg  [5:0]  dmaRow;	// src/main/scala/scarf/compute/MMCU.scala:137:26
  wire [15:0] _GEN_0 = {6'h0, mTile};	// src/main/scala/scarf/compute/MMCU.scala:105:22, :133:25, :139:36
  reg         doneReg;	// src/main/scala/scarf/compute/MMCU.scala:147:24
  reg         busyReg;	// src/main/scala/scarf/compute/MMCU.scala:148:24
  wire [25:0] _GEN_1 = {16'h0, mTile};	// src/main/scala/scarf/compute/MMCU.scala:105:22, :107:22, :153:21
  wire [21:0] _io_bAddr_T = {6'h0, kStep} * 22'h30;	// src/main/scala/scarf/compute/MMCU.scala:107:22, :133:25, :153:36
  wire [31:0] _GEN_2 = {16'h0, effN};	// src/main/scala/scarf/compute/MMCU.scala:107:22, :119:14, :154:35
  wire [15:0] _GEN_3 = {6'h0, nTile};	// src/main/scala/scarf/compute/MMCU.scala:106:22, :133:25, :154:50
  wire [31:0] _io_bAddr_T_3 = {10'h0, _io_bAddr_T} * _GEN_2 + {16'h0, _GEN_3 * 16'h30};	// src/main/scala/scarf/compute/MMCU.scala:105:22, :107:22, :123:48, :153:36, :154:{35,42,50}
  reg  [31:0] casez_tmp;	// src/main/scala/scarf/compute/MMCU.scala:185:33
  always_comb begin	// src/main/scala/scarf/compute/MMCU.scala:185:33
    casez (dmaRow)	// src/main/scala/scarf/compute/MMCU.scala:137:26, :185:33
      6'b000000:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b000001:
        casez_tmp = outBufReg_1_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b000010:
        casez_tmp = outBufReg_2_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b000011:
        casez_tmp = outBufReg_3_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b000100:
        casez_tmp = outBufReg_4_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b000101:
        casez_tmp = outBufReg_5_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b000110:
        casez_tmp = outBufReg_6_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b000111:
        casez_tmp = outBufReg_7_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b001000:
        casez_tmp = outBufReg_8_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b001001:
        casez_tmp = outBufReg_9_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b001010:
        casez_tmp = outBufReg_10_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b001011:
        casez_tmp = outBufReg_11_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b001100:
        casez_tmp = outBufReg_12_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b001101:
        casez_tmp = outBufReg_13_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b001110:
        casez_tmp = outBufReg_14_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b001111:
        casez_tmp = outBufReg_15_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b010000:
        casez_tmp = outBufReg_16_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b010001:
        casez_tmp = outBufReg_17_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b010010:
        casez_tmp = outBufReg_18_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b010011:
        casez_tmp = outBufReg_19_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b010100:
        casez_tmp = outBufReg_20_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b010101:
        casez_tmp = outBufReg_21_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b010110:
        casez_tmp = outBufReg_22_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b010111:
        casez_tmp = outBufReg_23_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b011000:
        casez_tmp = outBufReg_24_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b011001:
        casez_tmp = outBufReg_25_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b011010:
        casez_tmp = outBufReg_26_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b011011:
        casez_tmp = outBufReg_27_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b011100:
        casez_tmp = outBufReg_28_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b011101:
        casez_tmp = outBufReg_29_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b011110:
        casez_tmp = outBufReg_30_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b011111:
        casez_tmp = outBufReg_31_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b100000:
        casez_tmp = outBufReg_32_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b100001:
        casez_tmp = outBufReg_33_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b100010:
        casez_tmp = outBufReg_34_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b100011:
        casez_tmp = outBufReg_35_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b100100:
        casez_tmp = outBufReg_36_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b100101:
        casez_tmp = outBufReg_37_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b100110:
        casez_tmp = outBufReg_38_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b100111:
        casez_tmp = outBufReg_39_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b101000:
        casez_tmp = outBufReg_40_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b101001:
        casez_tmp = outBufReg_41_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b101010:
        casez_tmp = outBufReg_42_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b101011:
        casez_tmp = outBufReg_43_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b101100:
        casez_tmp = outBufReg_44_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b101101:
        casez_tmp = outBufReg_45_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b101110:
        casez_tmp = outBufReg_46_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b101111:
        casez_tmp = outBufReg_47_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b110000:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b110001:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b110010:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b110011:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b110100:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b110101:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b110110:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b110111:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b111000:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b111001:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b111010:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b111011:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b111100:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b111101:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      6'b111110:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
      default:
        casez_tmp = outBufReg_0_0;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :185:33
    endcase	// src/main/scala/scarf/compute/MMCU.scala:137:26, :185:33
  end // always_comb
  wire        _GEN_4 = state == 2'h0;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :195:17, :253:17
  wire        _GEN_5 = state == 2'h1;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :195:17, :203:17
  wire        _GEN_6 = state == 2'h2;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :195:17, :216:15
  wire        _GEN_7 = _GEN_3 == (effN + 16'h2F) / 16'h30 - 16'h1;	// src/main/scala/scarf/compute/MMCU.scala:119:14, :123:{27,48}, :124:{27,48}, :154:50, :233:{20,36}
  wire        _GEN_8 = _GEN_7 & _GEN_0 == (effM + 16'h2F) / 16'h30 - 16'h1;	// src/main/scala/scarf/compute/MMCU.scala:113:14, :123:{27,48}, :139:36, :233:{20,43}, :236:{22,38,45}, :237:19, :239:19, :243:17
  wire        _GEN_9 = (&state) & ~dmaActive;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :136:26, :147:24, :195:17, :221:12, :250:24, :251:17
  reg  [1:0]  casez_tmp_0;	// src/main/scala/scarf/compute/MMCU.scala:195:17, :198:22
  always_comb begin	// src/main/scala/scarf/compute/MMCU.scala:195:17, :198:22, :215:41, :221:24
    casez (state)	// src/main/scala/scarf/compute/MMCU.scala:102:22, :195:17, :198:22, :215:41, :221:24
      2'b00:
        casez_tmp_0 = io_start ? 2'h1 : state;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :195:17, :198:22, :203:17, :215:41, :221:24
      2'b01:
        casez_tmp_0 = kStep == totalKSteps - 16'h1 ? 2'h2 : state;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :107:22, :125:48, :195:17, :198:22, :215:{18,34,41}, :216:15, :221:24
      2'b10:
        casez_tmp_0 = dmaActive ? state : {_GEN_8, 1'h1};	// src/main/scala/scarf/compute/MMCU.scala:66:14, :102:22, :136:26, :195:17, :198:22, :215:41, :221:24, :233:43, :236:45, :237:19, :239:19, :243:17
      default:
        casez_tmp_0 = _GEN_9 ? 2'h0 : state;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :147:24, :195:17, :198:22, :215:41, :221:24, :250:24, :251:17, :253:17
    endcase	// src/main/scala/scarf/compute/MMCU.scala:102:22, :195:17, :198:22, :215:41, :221:24
  end // always_comb
  wire        _GEN_10 = _GEN_5 | _GEN_6;	// src/main/scala/scarf/compute/MMCU.scala:147:24, :195:17
  wire [15:0] _remainingRows_T_1 = effM - _GEN_0 * 16'h30;	// src/main/scala/scarf/compute/MMCU.scala:113:14, :123:48, :139:{28,36}
  wire        _GEN_11 = dmaRow == snapRows - 6'h1;	// src/main/scala/scarf/compute/MMCU.scala:133:25, :137:26, :189:{17,31}
  wire        _GEN_12 = _GEN_6 & ~dmaActive;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :136:26, :195:17, :221:{12,24}, :223:27
  wire        _GEN_13 = _GEN_4 | _GEN_5;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :195:17
  wire        _GEN_14 = _GEN_13 | ~_GEN_12;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :195:17, :221:24, :223:27
  always @(posedge clock) begin	// src/main/scala/scarf/compute/MMCU.scala:65:7
    if (reset) begin	// src/main/scala/scarf/compute/MMCU.scala:65:7
      state <= 2'h0;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :253:17
      mTile <= 10'h0;	// src/main/scala/scarf/compute/MMCU.scala:105:22
      nTile <= 10'h0;	// src/main/scala/scarf/compute/MMCU.scala:105:22, :106:22
      kStep <= 16'h0;	// src/main/scala/scarf/compute/MMCU.scala:107:22
      snapMTile <= 10'h0;	// src/main/scala/scarf/compute/MMCU.scala:105:22, :129:26
      snapNTile <= 10'h0;	// src/main/scala/scarf/compute/MMCU.scala:105:22, :130:26
      snapRows <= 6'h0;	// src/main/scala/scarf/compute/MMCU.scala:133:25
      dmaActive <= 1'h0;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :136:26
      dmaRow <= 6'h0;	// src/main/scala/scarf/compute/MMCU.scala:133:25, :137:26
      doneReg <= 1'h0;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :147:24
      busyReg <= 1'h0;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :148:24
    end
    else begin	// src/main/scala/scarf/compute/MMCU.scala:65:7
      state <= casez_tmp_0;	// src/main/scala/scarf/compute/MMCU.scala:102:22, :195:17, :198:22
      if (_GEN_4) begin	// src/main/scala/scarf/compute/MMCU.scala:195:17
        if (io_start) begin	// src/main/scala/scarf/compute/MMCU.scala:66:14
          mTile <= 10'h0;	// src/main/scala/scarf/compute/MMCU.scala:105:22
          nTile <= 10'h0;	// src/main/scala/scarf/compute/MMCU.scala:105:22, :106:22
          kStep <= 16'h0;	// src/main/scala/scarf/compute/MMCU.scala:107:22
        end
        doneReg <= ~io_start & doneReg;	// src/main/scala/scarf/compute/MMCU.scala:147:24, :198:22, :202:17
        busyReg <= io_start;	// src/main/scala/scarf/compute/MMCU.scala:148:24
      end
      else begin	// src/main/scala/scarf/compute/MMCU.scala:195:17
        if (_GEN_5 | ~(_GEN_6 & ~dmaActive & _GEN_7)) begin	// src/main/scala/scarf/compute/MMCU.scala:105:22, :136:26, :195:17, :221:{12,24}, :233:{20,43}, :235:17
        end
        else	// src/main/scala/scarf/compute/MMCU.scala:105:22, :195:17
          mTile <= mTile + 10'h1;	// src/main/scala/scarf/compute/MMCU.scala:105:22, :232:24, :235:26
        if (_GEN_5 | ~_GEN_12) begin	// src/main/scala/scarf/compute/MMCU.scala:106:22, :128:22, :195:17, :221:24, :223:27
        end
        else if (_GEN_7)	// src/main/scala/scarf/compute/MMCU.scala:233:20
          nTile <= 10'h0;	// src/main/scala/scarf/compute/MMCU.scala:105:22, :106:22
        else	// src/main/scala/scarf/compute/MMCU.scala:233:20
          nTile <= nTile + 10'h1;	// src/main/scala/scarf/compute/MMCU.scala:106:22, :232:24
        if (_GEN_5)	// src/main/scala/scarf/compute/MMCU.scala:195:17
          kStep <= kStep + 16'h1;	// src/main/scala/scarf/compute/MMCU.scala:107:22, :214:22
        else if (~_GEN_12 | _GEN_8) begin	// src/main/scala/scarf/compute/MMCU.scala:107:22, :128:22, :195:17, :221:24, :223:27, :233:43, :236:45, :237:19, :239:19, :243:17
        end
        else	// src/main/scala/scarf/compute/MMCU.scala:107:22, :195:17, :221:24, :233:43
          kStep <= 16'h0;	// src/main/scala/scarf/compute/MMCU.scala:107:22
        doneReg <= ~_GEN_10 & _GEN_9 | doneReg;	// src/main/scala/scarf/compute/MMCU.scala:147:24, :195:17, :250:24, :251:17
        busyReg <= (_GEN_10 | ~_GEN_9) & busyReg;	// src/main/scala/scarf/compute/MMCU.scala:147:24, :148:24, :195:17, :250:24, :251:17, :252:17
      end
      if (_GEN_14) begin	// src/main/scala/scarf/compute/MMCU.scala:128:22, :133:25, :195:17
      end
      else begin	// src/main/scala/scarf/compute/MMCU.scala:133:25, :195:17
        snapMTile <= mTile;	// src/main/scala/scarf/compute/MMCU.scala:105:22, :129:26
        snapNTile <= nTile;	// src/main/scala/scarf/compute/MMCU.scala:106:22, :130:26
        snapRows <= _remainingRows_T_1 > 16'h2F ? 6'h30 : _remainingRows_T_1[5:0];	// src/main/scala/scarf/compute/MMCU.scala:123:{27,48}, :133:25, :139:28, :141:20, :142:19, :144:18
      end
      dmaActive <= ~_GEN_13 & _GEN_12 | ~(dmaActive & _GEN_11) & dmaActive;	// src/main/scala/scarf/compute/MMCU.scala:128:22, :136:26, :178:19, :189:{17,39}, :190:17, :195:17, :221:24, :223:27
      if (_GEN_14) begin	// src/main/scala/scarf/compute/MMCU.scala:128:22, :178:19, :195:17
        if (dmaActive) begin	// src/main/scala/scarf/compute/MMCU.scala:136:26
          if (_GEN_11)	// src/main/scala/scarf/compute/MMCU.scala:189:17
            dmaRow <= 6'h0;	// src/main/scala/scarf/compute/MMCU.scala:133:25, :137:26
          else	// src/main/scala/scarf/compute/MMCU.scala:189:17
            dmaRow <= dmaRow + 6'h1;	// src/main/scala/scarf/compute/MMCU.scala:137:26, :188:22
        end
      end
      else	// src/main/scala/scarf/compute/MMCU.scala:178:19, :195:17
        dmaRow <= 6'h0;	// src/main/scala/scarf/compute/MMCU.scala:133:25, :137:26
    end
    if (_GEN_14) begin	// src/main/scala/scarf/compute/MMCU.scala:128:22, :195:17
    end
    else begin	// src/main/scala/scarf/compute/MMCU.scala:128:22, :195:17
      outBufReg_0_0 <= _array_io_results_0_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_1_0 <= _array_io_results_1_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_2_0 <= _array_io_results_2_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_3_0 <= _array_io_results_3_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_4_0 <= _array_io_results_4_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_5_0 <= _array_io_results_5_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_6_0 <= _array_io_results_6_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_7_0 <= _array_io_results_7_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_8_0 <= _array_io_results_8_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_9_0 <= _array_io_results_9_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_10_0 <= _array_io_results_10_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_11_0 <= _array_io_results_11_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_12_0 <= _array_io_results_12_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_13_0 <= _array_io_results_13_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_14_0 <= _array_io_results_14_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_15_0 <= _array_io_results_15_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_16_0 <= _array_io_results_16_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_17_0 <= _array_io_results_17_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_18_0 <= _array_io_results_18_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_19_0 <= _array_io_results_19_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_20_0 <= _array_io_results_20_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_21_0 <= _array_io_results_21_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_22_0 <= _array_io_results_22_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_23_0 <= _array_io_results_23_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_24_0 <= _array_io_results_24_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_25_0 <= _array_io_results_25_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_26_0 <= _array_io_results_26_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_27_0 <= _array_io_results_27_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_28_0 <= _array_io_results_28_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_29_0 <= _array_io_results_29_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_30_0 <= _array_io_results_30_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_31_0 <= _array_io_results_31_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_32_0 <= _array_io_results_32_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_33_0 <= _array_io_results_33_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_34_0 <= _array_io_results_34_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_35_0 <= _array_io_results_35_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_36_0 <= _array_io_results_36_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_37_0 <= _array_io_results_37_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_38_0 <= _array_io_results_38_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_39_0 <= _array_io_results_39_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_40_0 <= _array_io_results_40_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_41_0 <= _array_io_results_41_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_42_0 <= _array_io_results_42_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_43_0 <= _array_io_results_43_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_44_0 <= _array_io_results_44_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_45_0 <= _array_io_results_45_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_46_0 <= _array_io_results_46_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
      outBufReg_47_0 <= _array_io_results_47_0;	// src/main/scala/scarf/compute/MMCU.scala:100:21, :128:22
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/compute/MMCU.scala:65:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/compute/MMCU.scala:65:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/compute/MMCU.scala:65:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2306];	// src/main/scala/scarf/compute/MMCU.scala:65:7
    initial begin	// src/main/scala/scarf/compute/MMCU.scala:65:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/compute/MMCU.scala:65:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/compute/MMCU.scala:65:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/compute/MMCU.scala:65:7
        for (logic [11:0] i = 12'h0; i < 12'h903; i += 12'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/scarf/compute/MMCU.scala:65:7
        end	// src/main/scala/scarf/compute/MMCU.scala:65:7
        state = _RANDOM[12'h0][1:0];	// src/main/scala/scarf/compute/MMCU.scala:65:7, :102:22
        mTile = _RANDOM[12'h0][11:2];	// src/main/scala/scarf/compute/MMCU.scala:65:7, :102:22, :105:22
        nTile = _RANDOM[12'h0][21:12];	// src/main/scala/scarf/compute/MMCU.scala:65:7, :102:22, :106:22
        kStep = {_RANDOM[12'h0][31:22], _RANDOM[12'h1][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :102:22, :107:22
        outBufReg_0_0 = {_RANDOM[12'h1][31:6], _RANDOM[12'h2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :107:22, :128:22
        outBufReg_1_0 = {_RANDOM[12'h31][31:6], _RANDOM[12'h32][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_2_0 = {_RANDOM[12'h61][31:6], _RANDOM[12'h62][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_3_0 = {_RANDOM[12'h91][31:6], _RANDOM[12'h92][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_4_0 = {_RANDOM[12'hC1][31:6], _RANDOM[12'hC2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_5_0 = {_RANDOM[12'hF1][31:6], _RANDOM[12'hF2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_6_0 = {_RANDOM[12'h121][31:6], _RANDOM[12'h122][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_7_0 = {_RANDOM[12'h151][31:6], _RANDOM[12'h152][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_8_0 = {_RANDOM[12'h181][31:6], _RANDOM[12'h182][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_9_0 = {_RANDOM[12'h1B1][31:6], _RANDOM[12'h1B2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_10_0 = {_RANDOM[12'h1E1][31:6], _RANDOM[12'h1E2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_11_0 = {_RANDOM[12'h211][31:6], _RANDOM[12'h212][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_12_0 = {_RANDOM[12'h241][31:6], _RANDOM[12'h242][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_13_0 = {_RANDOM[12'h271][31:6], _RANDOM[12'h272][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_14_0 = {_RANDOM[12'h2A1][31:6], _RANDOM[12'h2A2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_15_0 = {_RANDOM[12'h2D1][31:6], _RANDOM[12'h2D2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_16_0 = {_RANDOM[12'h301][31:6], _RANDOM[12'h302][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_17_0 = {_RANDOM[12'h331][31:6], _RANDOM[12'h332][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_18_0 = {_RANDOM[12'h361][31:6], _RANDOM[12'h362][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_19_0 = {_RANDOM[12'h391][31:6], _RANDOM[12'h392][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_20_0 = {_RANDOM[12'h3C1][31:6], _RANDOM[12'h3C2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_21_0 = {_RANDOM[12'h3F1][31:6], _RANDOM[12'h3F2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_22_0 = {_RANDOM[12'h421][31:6], _RANDOM[12'h422][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_23_0 = {_RANDOM[12'h451][31:6], _RANDOM[12'h452][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_24_0 = {_RANDOM[12'h481][31:6], _RANDOM[12'h482][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_25_0 = {_RANDOM[12'h4B1][31:6], _RANDOM[12'h4B2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_26_0 = {_RANDOM[12'h4E1][31:6], _RANDOM[12'h4E2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_27_0 = {_RANDOM[12'h511][31:6], _RANDOM[12'h512][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_28_0 = {_RANDOM[12'h541][31:6], _RANDOM[12'h542][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_29_0 = {_RANDOM[12'h571][31:6], _RANDOM[12'h572][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_30_0 = {_RANDOM[12'h5A1][31:6], _RANDOM[12'h5A2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_31_0 = {_RANDOM[12'h5D1][31:6], _RANDOM[12'h5D2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_32_0 = {_RANDOM[12'h601][31:6], _RANDOM[12'h602][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_33_0 = {_RANDOM[12'h631][31:6], _RANDOM[12'h632][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_34_0 = {_RANDOM[12'h661][31:6], _RANDOM[12'h662][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_35_0 = {_RANDOM[12'h691][31:6], _RANDOM[12'h692][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_36_0 = {_RANDOM[12'h6C1][31:6], _RANDOM[12'h6C2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_37_0 = {_RANDOM[12'h6F1][31:6], _RANDOM[12'h6F2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_38_0 = {_RANDOM[12'h721][31:6], _RANDOM[12'h722][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_39_0 = {_RANDOM[12'h751][31:6], _RANDOM[12'h752][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_40_0 = {_RANDOM[12'h781][31:6], _RANDOM[12'h782][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_41_0 = {_RANDOM[12'h7B1][31:6], _RANDOM[12'h7B2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_42_0 = {_RANDOM[12'h7E1][31:6], _RANDOM[12'h7E2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_43_0 = {_RANDOM[12'h811][31:6], _RANDOM[12'h812][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_44_0 = {_RANDOM[12'h841][31:6], _RANDOM[12'h842][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_45_0 = {_RANDOM[12'h871][31:6], _RANDOM[12'h872][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_46_0 = {_RANDOM[12'h8A1][31:6], _RANDOM[12'h8A2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        outBufReg_47_0 = {_RANDOM[12'h8D1][31:6], _RANDOM[12'h8D2][5:0]};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :128:22
        snapMTile = _RANDOM[12'h901][15:6];	// src/main/scala/scarf/compute/MMCU.scala:65:7, :129:26
        snapNTile = _RANDOM[12'h901][25:16];	// src/main/scala/scarf/compute/MMCU.scala:65:7, :129:26, :130:26
        snapRows = _RANDOM[12'h901][31:26];	// src/main/scala/scarf/compute/MMCU.scala:65:7, :129:26, :133:25
        dmaActive = _RANDOM[12'h902][0];	// src/main/scala/scarf/compute/MMCU.scala:65:7, :136:26
        dmaRow = _RANDOM[12'h902][6:1];	// src/main/scala/scarf/compute/MMCU.scala:65:7, :136:26, :137:26
        doneReg = _RANDOM[12'h902][7];	// src/main/scala/scarf/compute/MMCU.scala:65:7, :136:26, :147:24
        busyReg = _RANDOM[12'h902][8];	// src/main/scala/scarf/compute/MMCU.scala:65:7, :136:26, :148:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/compute/MMCU.scala:65:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/compute/MMCU.scala:65:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  OutputStationaryArray array (	// src/main/scala/scarf/compute/MMCU.scala:100:21
    .clock           (clock),
    .reset           (reset),
    .io_aRow_0       (io_aData_0),
    .io_aRow_1       (io_aData_1),
    .io_aRow_2       (io_aData_2),
    .io_aRow_3       (io_aData_3),
    .io_aRow_4       (io_aData_4),
    .io_aRow_5       (io_aData_5),
    .io_aRow_6       (io_aData_6),
    .io_aRow_7       (io_aData_7),
    .io_aRow_8       (io_aData_8),
    .io_aRow_9       (io_aData_9),
    .io_aRow_10      (io_aData_10),
    .io_aRow_11      (io_aData_11),
    .io_aRow_12      (io_aData_12),
    .io_aRow_13      (io_aData_13),
    .io_aRow_14      (io_aData_14),
    .io_aRow_15      (io_aData_15),
    .io_aRow_16      (io_aData_16),
    .io_aRow_17      (io_aData_17),
    .io_aRow_18      (io_aData_18),
    .io_aRow_19      (io_aData_19),
    .io_aRow_20      (io_aData_20),
    .io_aRow_21      (io_aData_21),
    .io_aRow_22      (io_aData_22),
    .io_aRow_23      (io_aData_23),
    .io_aRow_24      (io_aData_24),
    .io_aRow_25      (io_aData_25),
    .io_aRow_26      (io_aData_26),
    .io_aRow_27      (io_aData_27),
    .io_aRow_28      (io_aData_28),
    .io_aRow_29      (io_aData_29),
    .io_aRow_30      (io_aData_30),
    .io_aRow_31      (io_aData_31),
    .io_aRow_32      (io_aData_32),
    .io_aRow_33      (io_aData_33),
    .io_aRow_34      (io_aData_34),
    .io_aRow_35      (io_aData_35),
    .io_aRow_36      (io_aData_36),
    .io_aRow_37      (io_aData_37),
    .io_aRow_38      (io_aData_38),
    .io_aRow_39      (io_aData_39),
    .io_aRow_40      (io_aData_40),
    .io_aRow_41      (io_aData_41),
    .io_aRow_42      (io_aData_42),
    .io_aRow_43      (io_aData_43),
    .io_aRow_44      (io_aData_44),
    .io_aRow_45      (io_aData_45),
    .io_aRow_46      (io_aData_46),
    .io_aRow_47      (io_aData_47),
    .io_bCol_0       (io_bData_0),
    .io_results_0_0  (_array_io_results_0_0),
    .io_results_1_0  (_array_io_results_1_0),
    .io_results_2_0  (_array_io_results_2_0),
    .io_results_3_0  (_array_io_results_3_0),
    .io_results_4_0  (_array_io_results_4_0),
    .io_results_5_0  (_array_io_results_5_0),
    .io_results_6_0  (_array_io_results_6_0),
    .io_results_7_0  (_array_io_results_7_0),
    .io_results_8_0  (_array_io_results_8_0),
    .io_results_9_0  (_array_io_results_9_0),
    .io_results_10_0 (_array_io_results_10_0),
    .io_results_11_0 (_array_io_results_11_0),
    .io_results_12_0 (_array_io_results_12_0),
    .io_results_13_0 (_array_io_results_13_0),
    .io_results_14_0 (_array_io_results_14_0),
    .io_results_15_0 (_array_io_results_15_0),
    .io_results_16_0 (_array_io_results_16_0),
    .io_results_17_0 (_array_io_results_17_0),
    .io_results_18_0 (_array_io_results_18_0),
    .io_results_19_0 (_array_io_results_19_0),
    .io_results_20_0 (_array_io_results_20_0),
    .io_results_21_0 (_array_io_results_21_0),
    .io_results_22_0 (_array_io_results_22_0),
    .io_results_23_0 (_array_io_results_23_0),
    .io_results_24_0 (_array_io_results_24_0),
    .io_results_25_0 (_array_io_results_25_0),
    .io_results_26_0 (_array_io_results_26_0),
    .io_results_27_0 (_array_io_results_27_0),
    .io_results_28_0 (_array_io_results_28_0),
    .io_results_29_0 (_array_io_results_29_0),
    .io_results_30_0 (_array_io_results_30_0),
    .io_results_31_0 (_array_io_results_31_0),
    .io_results_32_0 (_array_io_results_32_0),
    .io_results_33_0 (_array_io_results_33_0),
    .io_results_34_0 (_array_io_results_34_0),
    .io_results_35_0 (_array_io_results_35_0),
    .io_results_36_0 (_array_io_results_36_0),
    .io_results_37_0 (_array_io_results_37_0),
    .io_results_38_0 (_array_io_results_38_0),
    .io_results_39_0 (_array_io_results_39_0),
    .io_results_40_0 (_array_io_results_40_0),
    .io_results_41_0 (_array_io_results_41_0),
    .io_results_42_0 (_array_io_results_42_0),
    .io_results_43_0 (_array_io_results_43_0),
    .io_results_44_0 (_array_io_results_44_0),
    .io_results_45_0 (_array_io_results_45_0),
    .io_results_46_0 (_array_io_results_46_0),
    .io_results_47_0 (_array_io_results_47_0),
    .io_enable       (~_GEN_4 & _GEN_5),	// src/main/scala/scarf/compute/MMCU.scala:174:19, :195:17
    .io_clear        (_GEN_4 ? io_start : ~_GEN_5 & _GEN_6 & ~dmaActive)	// src/main/scala/scarf/compute/MMCU.scala:136:26, :175:19, :195:17, :198:22, :221:12
  );
  assign io_done = doneReg;	// src/main/scala/scarf/compute/MMCU.scala:65:7, :147:24
  assign io_busy = busyReg;	// src/main/scala/scarf/compute/MMCU.scala:65:7, :148:24
  assign io_aAddr = {6'h0, _GEN_1 * {10'h0, _effK_T_3} + {4'h0, _io_bAddr_T}};	// src/main/scala/scarf/compute/MMCU.scala:65:7, :105:22, :116:14, :117:20, :133:25, :153:{12,21,28,36}
  assign io_bAddr = _io_bAddr_T_3;	// src/main/scala/scarf/compute/MMCU.scala:65:7, :154:42
  assign io_cAddr =
    dmaActive
      ? {16'h0, {6'h0, snapMTile} * 16'h30} * _GEN_2 + {16'h0, {6'h0, snapNTile} * 16'h30}
        + {10'h0, {16'h0, dmaRow} * {6'h0, effN}}
      : 32'h0;	// src/main/scala/scarf/compute/MMCU.scala:65:7, :105:22, :107:22, :119:14, :123:48, :129:26, :130:26, :133:25, :136:26, :137:26, :154:35, :155:28, :163:13, :178:19, :181:{15,28,42,49,75}, :182:25
  assign io_cData_0 = dmaActive ? casez_tmp + {16'h0, io_biasData_0} : 32'h0;	// src/main/scala/scarf/compute/MMCU.scala:65:7, :107:22, :136:26, :163:13, :164:47, :178:19, :184:20, :185:33
  assign io_cWr = dmaActive;	// src/main/scala/scarf/compute/MMCU.scala:65:7, :136:26
  assign io_weightAddr =
    _io_weightAddr_T
      ? {6'h0, _GEN_1 * {10'h0, totalKSteps} + {10'h0, kStep}} * 32'h30
      : _io_bAddr_T_3;	// src/main/scala/scarf/compute/MMCU.scala:65:7, :105:22, :107:22, :113:23, :125:48, :133:25, :153:21, :154:42, :156:23, :157:{12,26,35}
endmodule
