// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module NormUnit(	// src/main/scala/scarf/compute/NormUnit.scala:29:7
  input         clock,	// src/main/scala/scarf/compute/NormUnit.scala:29:7
                reset,	// src/main/scala/scarf/compute/NormUnit.scala:29:7
                io_start,	// src/main/scala/scarf/compute/NormUnit.scala:30:14
  input  [9:0]  io_channels,	// src/main/scala/scarf/compute/NormUnit.scala:30:14
  input  [15:0] io_dataIn,	// src/main/scala/scarf/compute/NormUnit.scala:30:14
  output [15:0] io_dataOut,	// src/main/scala/scarf/compute/NormUnit.scala:30:14
  input  [15:0] io_gammaIn,	// src/main/scala/scarf/compute/NormUnit.scala:30:14
                io_betaIn,	// src/main/scala/scarf/compute/NormUnit.scala:30:14
  input         io_inValid,	// src/main/scala/scarf/compute/NormUnit.scala:30:14
  output        io_outValid	// src/main/scala/scarf/compute/NormUnit.scala:30:14
);

  reg  [2:0]  state;	// src/main/scala/scarf/compute/NormUnit.scala:48:22
  reg  [31:0] sumAcc;	// src/main/scala/scarf/compute/NormUnit.scala:51:25
  reg  [31:0] sqSumAcc;	// src/main/scala/scarf/compute/NormUnit.scala:53:25
  reg  [15:0] count;	// src/main/scala/scarf/compute/NormUnit.scala:54:25
  reg  [31:0] meanReg;	// src/main/scala/scarf/compute/NormUnit.scala:55:25
  reg  [31:0] varReg;	// src/main/scala/scarf/compute/NormUnit.scala:56:25
  reg  [31:0] rsqrtReg;	// src/main/scala/scarf/compute/NormUnit.scala:58:25
  reg  [1:0]  newtonIter;	// src/main/scala/scarf/compute/NormUnit.scala:60:27
  wire        _GEN = state == 3'h0;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17
  wire        _GEN_0 = state == 3'h1;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17
  wire        _GEN_1 = count == {6'h0, io_channels} - 16'h1 & io_inValid;	// src/main/scala/scarf/compute/NormUnit.scala:54:25, :64:13, :94:{18,32,38}
  wire        _GEN_2 = state == 3'h2;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17
  wire        _GEN_3 = state == 3'h3;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17
  wire        _GEN_4 = newtonIter == 2'h0;	// src/main/scala/scarf/compute/NormUnit.scala:60:27, :120:23
  wire        _GEN_5 = newtonIter == 2'h1;	// src/main/scala/scarf/compute/NormUnit.scala:60:27, :124:20, :125:29
  wire        _GEN_6 = _GEN_4 | _GEN_5;	// src/main/scala/scarf/compute/NormUnit.scala:48:22, :120:{23,32}, :125:{29,38}, :133:15
  wire        _GEN_7 = state == 3'h4;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17
  wire        _GEN_8 = _GEN_7 & io_inValid;	// src/main/scala/scarf/compute/NormUnit.scala:73:15, :76:17, :139:24, :144:21
  wire        _GEN_9 = _GEN | _GEN_0 | _GEN_2 | _GEN_3;	// src/main/scala/scarf/compute/NormUnit.scala:73:15, :76:17
  reg  [2:0]  casez_tmp;	// src/main/scala/scarf/compute/NormUnit.scala:76:17, :80:22
  always_comb begin	// src/main/scala/scarf/compute/NormUnit.scala:48:22, :76:17, :80:22, :94:53, :108:53, :120:32, :148:53, :156:15
    casez (state)	// src/main/scala/scarf/compute/NormUnit.scala:48:22, :76:17, :80:22, :94:53, :108:53, :120:32, :148:53, :156:15
      3'b000:
        casez_tmp = io_start ? 3'h1 : state;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17, :80:22, :81:18, :94:53, :108:53, :120:32, :148:53, :156:15
      3'b001:
        casez_tmp = _GEN_1 ? 3'h2 : state;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17, :80:22, :94:{38,53}, :96:17, :108:53, :120:32, :148:53, :156:15
      3'b010:
        casez_tmp = _GEN_1 ? 3'h3 : state;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17, :80:22, :94:{38,53}, :108:53, :110:16, :120:32, :148:53, :156:15
      3'b011:
        casez_tmp = _GEN_6 ? state : 3'h4;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17, :80:22, :94:53, :108:53, :120:32, :125:38, :133:15, :148:53, :156:15
      3'b100:
        casez_tmp = _GEN_1 ? 3'h5 : state;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17, :80:22, :94:{38,53}, :108:53, :120:32, :148:53, :149:15, :156:15
      3'b101:
        casez_tmp = 3'h0;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :76:17, :80:22, :94:53, :108:53, :120:32, :148:53, :156:15
      3'b110:
        casez_tmp = state;	// src/main/scala/scarf/compute/NormUnit.scala:48:22, :76:17, :80:22, :94:53, :108:53, :120:32, :148:53, :156:15
      default:
        casez_tmp = state;	// src/main/scala/scarf/compute/NormUnit.scala:48:22, :76:17, :80:22, :94:53, :108:53, :120:32, :148:53, :156:15
    endcase	// src/main/scala/scarf/compute/NormUnit.scala:48:22, :76:17, :80:22, :94:53, :108:53, :120:32, :148:53, :156:15
  end // always_comb
  wire [31:0] _GEN_10 = {16'h0, io_dataIn};	// src/main/scala/scarf/compute/NormUnit.scala:54:25, :91:{26,41}
  wire [31:0] _diff_T_1 = _GEN_10 - meanReg;	// src/main/scala/scarf/compute/NormUnit.scala:55:25, :91:{26,41}, :103:{33,56}
  wire [31:0] _varPlusEps_T = varReg + 32'h3C23D70A;	// src/main/scala/scarf/compute/NormUnit.scala:56:25, :119:31
  wire [31:0] _rsqrtReg_T_4 =
    rsqrtReg * (32'h18000 - _varPlusEps_T * rsqrtReg * rsqrtReg);	// src/main/scala/scarf/compute/NormUnit.scala:58:25, :119:31, :128:31, :129:66, :130:24
  wire [31:0] _GEN_11 = {22'h0, io_channels};	// src/main/scala/scarf/compute/NormUnit.scala:95:27
  wire        _GEN_12 = _GEN | _GEN_0;	// src/main/scala/scarf/compute/NormUnit.scala:56:25, :76:17
  always @(posedge clock) begin	// src/main/scala/scarf/compute/NormUnit.scala:29:7
    if (reset) begin	// src/main/scala/scarf/compute/NormUnit.scala:29:7
      state <= 3'h0;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22
      sumAcc <= 32'h0;	// src/main/scala/scarf/compute/NormUnit.scala:51:25
      sqSumAcc <= 32'h0;	// src/main/scala/scarf/compute/NormUnit.scala:51:25, :53:25
      count <= 16'h0;	// src/main/scala/scarf/compute/NormUnit.scala:54:25
      meanReg <= 32'h0;	// src/main/scala/scarf/compute/NormUnit.scala:51:25, :55:25
      varReg <= 32'h0;	// src/main/scala/scarf/compute/NormUnit.scala:51:25, :56:25
      rsqrtReg <= 32'h0;	// src/main/scala/scarf/compute/NormUnit.scala:51:25, :58:25
      newtonIter <= 2'h0;	// src/main/scala/scarf/compute/NormUnit.scala:60:27
    end
    else begin	// src/main/scala/scarf/compute/NormUnit.scala:29:7
      state <= casez_tmp;	// src/main/scala/scarf/compute/NormUnit.scala:48:22, :76:17, :80:22
      if (_GEN) begin	// src/main/scala/scarf/compute/NormUnit.scala:76:17
        if (io_start) begin	// src/main/scala/scarf/compute/NormUnit.scala:30:14
          sumAcc <= 32'h0;	// src/main/scala/scarf/compute/NormUnit.scala:51:25
          sqSumAcc <= 32'h0;	// src/main/scala/scarf/compute/NormUnit.scala:51:25, :53:25
          count <= 16'h0;	// src/main/scala/scarf/compute/NormUnit.scala:54:25
        end
      end
      else begin	// src/main/scala/scarf/compute/NormUnit.scala:76:17
        if (_GEN_0 & io_inValid)	// src/main/scala/scarf/compute/NormUnit.scala:51:25, :76:17, :90:24, :91:16
          sumAcc <= _GEN_10 + sumAcc;	// src/main/scala/scarf/compute/NormUnit.scala:51:25, :91:{26,41}
        if (_GEN_0 | ~(_GEN_2 & io_inValid)) begin	// src/main/scala/scarf/compute/NormUnit.scala:53:25, :76:17, :102:24, :105:18
        end
        else	// src/main/scala/scarf/compute/NormUnit.scala:53:25, :76:17
          sqSumAcc <= sqSumAcc + _diff_T_1 * _diff_T_1;	// src/main/scala/scarf/compute/NormUnit.scala:53:25, :103:{33,56}, :104:24, :105:30
        if (_GEN_0) begin	// src/main/scala/scarf/compute/NormUnit.scala:76:17
          if (_GEN_1)	// src/main/scala/scarf/compute/NormUnit.scala:94:38
            count <= 16'h0;	// src/main/scala/scarf/compute/NormUnit.scala:54:25
          else if (io_inValid)	// src/main/scala/scarf/compute/NormUnit.scala:30:14
            count <= count + 16'h1;	// src/main/scala/scarf/compute/NormUnit.scala:54:25, :92:25
        end
        else if (_GEN_2) begin	// src/main/scala/scarf/compute/NormUnit.scala:76:17
          if (_GEN_1)	// src/main/scala/scarf/compute/NormUnit.scala:94:38
            count <= 16'h0;	// src/main/scala/scarf/compute/NormUnit.scala:54:25
          else if (io_inValid)	// src/main/scala/scarf/compute/NormUnit.scala:30:14
            count <= count + 16'h1;	// src/main/scala/scarf/compute/NormUnit.scala:54:25, :92:25, :106:24
        end
        else if (_GEN_3) begin	// src/main/scala/scarf/compute/NormUnit.scala:76:17
          if (~_GEN_6)	// src/main/scala/scarf/compute/NormUnit.scala:48:22, :120:32, :125:38, :133:15
            count <= 16'h0;	// src/main/scala/scarf/compute/NormUnit.scala:54:25
        end
        else if (_GEN_8)	// src/main/scala/scarf/compute/NormUnit.scala:73:15, :76:17, :139:24, :144:21
          count <= count + 16'h1;	// src/main/scala/scarf/compute/NormUnit.scala:54:25, :92:25, :146:24
      end
      if (_GEN | ~(_GEN_0 & _GEN_1)) begin	// src/main/scala/scarf/compute/NormUnit.scala:55:25, :76:17, :94:{38,53}, :95:17
      end
      else	// src/main/scala/scarf/compute/NormUnit.scala:55:25, :76:17
        meanReg <= sumAcc / _GEN_11;	// src/main/scala/scarf/compute/NormUnit.scala:51:25, :55:25, :95:27
      if (_GEN_12 | ~(_GEN_2 & _GEN_1)) begin	// src/main/scala/scarf/compute/NormUnit.scala:56:25, :76:17, :94:38, :108:53, :109:16
      end
      else	// src/main/scala/scarf/compute/NormUnit.scala:56:25, :76:17
        varReg <= sqSumAcc / _GEN_11;	// src/main/scala/scarf/compute/NormUnit.scala:53:25, :56:25, :95:27, :109:28
      if (_GEN | _GEN_0 | _GEN_2 | ~_GEN_3) begin	// src/main/scala/scarf/compute/NormUnit.scala:58:25, :76:17
      end
      else if (_GEN_4)	// src/main/scala/scarf/compute/NormUnit.scala:120:23
        rsqrtReg <= (|_varPlusEps_T) ? 32'h8000 : 32'h80000000;	// src/main/scala/scarf/compute/NormUnit.scala:58:25, :119:31, :121:{24,36}, :123:16
      else if (_GEN_5)	// src/main/scala/scarf/compute/NormUnit.scala:125:29
        rsqrtReg <= {1'h0, _rsqrtReg_T_4[31:1]};	// src/main/scala/scarf/compute/NormUnit.scala:58:25, :64:32, :130:{18,24,40,70}
      if (~_GEN_12) begin	// src/main/scala/scarf/compute/NormUnit.scala:56:25, :76:17
        if (_GEN_2) begin	// src/main/scala/scarf/compute/NormUnit.scala:76:17
          if (_GEN_1)	// src/main/scala/scarf/compute/NormUnit.scala:94:38
            newtonIter <= 2'h0;	// src/main/scala/scarf/compute/NormUnit.scala:60:27
        end
        else if (_GEN_3) begin	// src/main/scala/scarf/compute/NormUnit.scala:76:17
          if (_GEN_4)	// src/main/scala/scarf/compute/NormUnit.scala:120:23
            newtonIter <= 2'h1;	// src/main/scala/scarf/compute/NormUnit.scala:60:27, :124:20
          else if (_GEN_5)	// src/main/scala/scarf/compute/NormUnit.scala:125:29
            newtonIter <= 2'h2;	// src/main/scala/scarf/compute/NormUnit.scala:60:27, :96:17
        end
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/compute/NormUnit.scala:29:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/compute/NormUnit.scala:29:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/compute/NormUnit.scala:29:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:5];	// src/main/scala/scarf/compute/NormUnit.scala:29:7
    initial begin	// src/main/scala/scarf/compute/NormUnit.scala:29:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/compute/NormUnit.scala:29:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/compute/NormUnit.scala:29:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/compute/NormUnit.scala:29:7
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/scarf/compute/NormUnit.scala:29:7
        end	// src/main/scala/scarf/compute/NormUnit.scala:29:7
        state = _RANDOM[3'h0][2:0];	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22
        sumAcc = {_RANDOM[3'h0][31:3], _RANDOM[3'h1][2:0]};	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :48:22, :51:25
        sqSumAcc = {_RANDOM[3'h1][31:3], _RANDOM[3'h2][2:0]};	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :51:25, :53:25
        count = _RANDOM[3'h2][18:3];	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :53:25, :54:25
        meanReg = {_RANDOM[3'h2][31:19], _RANDOM[3'h3][18:0]};	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :53:25, :55:25
        varReg = {_RANDOM[3'h3][31:19], _RANDOM[3'h4][18:0]};	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :55:25, :56:25
        rsqrtReg = {_RANDOM[3'h4][31:19], _RANDOM[3'h5][18:0]};	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :56:25, :58:25
        newtonIter = _RANDOM[3'h5][20:19];	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :58:25, :60:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/compute/NormUnit.scala:29:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/compute/NormUnit.scala:29:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_dataOut =
    _GEN_9 | ~_GEN_8
      ? 16'h0
      : (io_dataIn - meanReg[15:0]) * rsqrtReg[15:0] * io_gammaIn + io_betaIn;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :54:25, :55:25, :58:25, :73:15, :76:17, :127:21, :139:24, :141:{37,60}, :143:64, :144:{21,31}
  assign io_outValid = ~_GEN_9 & _GEN_7 & io_inValid;	// src/main/scala/scarf/compute/NormUnit.scala:29:7, :73:15, :74:15, :76:17
endmodule
