// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module OutputStationaryArray(	// src/main/scala/scarf/compute/MMCU.scala:39:7
  input         clock,	// src/main/scala/scarf/compute/MMCU.scala:39:7
                reset,	// src/main/scala/scarf/compute/MMCU.scala:39:7
  input  [15:0] io_aRow_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_1,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_2,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_3,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_4,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_5,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_6,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_7,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_8,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_9,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_10,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_11,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_12,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_13,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_14,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_15,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_16,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_17,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_18,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_19,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_20,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_21,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_22,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_23,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_24,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_25,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_26,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_27,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_28,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_29,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_30,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_31,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_32,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_33,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_34,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_35,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_36,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_37,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_38,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_39,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_40,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_41,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_42,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_43,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_44,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_45,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_46,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_aRow_47,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_bCol_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
  output [31:0] io_results_0_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_1_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_2_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_3_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_4_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_5_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_6_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_7_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_8_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_9_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_10_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_11_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_12_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_13_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_14_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_15_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_16_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_17_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_18_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_19_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_20_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_21_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_22_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_23_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_24_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_25_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_26_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_27_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_28_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_29_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_30_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_31_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_32_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_33_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_34_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_35_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_36_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_37_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_38_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_39_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_40_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_41_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_42_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_43_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_44_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_45_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_46_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_results_47_0,	// src/main/scala/scarf/compute/MMCU.scala:40:14
  input         io_enable,	// src/main/scala/scarf/compute/MMCU.scala:40:14
                io_clear	// src/main/scala/scarf/compute/MMCU.scala:40:14
);

  OSPE pes_0_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_0),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_0_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_1_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_1),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_1_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_2_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_2),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_2_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_3_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_3),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_3_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_4_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_4),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_4_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_5_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_5),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_5_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_6_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_6),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_6_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_7_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_7),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_7_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_8_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_8),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_8_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_9_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_9),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_9_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_10_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_10),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_10_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_11_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_11),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_11_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_12_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_12),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_12_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_13_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_13),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_13_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_14_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_14),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_14_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_15_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_15),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_15_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_16_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_16),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_16_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_17_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_17),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_17_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_18_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_18),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_18_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_19_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_19),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_19_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_20_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_20),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_20_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_21_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_21),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_21_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_22_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_22),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_22_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_23_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_23),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_23_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_24_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_24),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_24_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_25_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_25),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_25_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_26_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_26),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_26_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_27_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_27),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_27_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_28_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_28),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_28_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_29_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_29),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_29_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_30_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_30),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_30_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_31_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_31),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_31_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_32_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_32),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_32_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_33_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_33),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_33_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_34_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_34),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_34_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_35_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_35),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_35_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_36_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_36),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_36_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_37_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_37),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_37_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_38_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_38),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_38_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_39_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_39),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_39_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_40_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_40),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_40_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_41_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_41),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_41_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_42_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_42),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_42_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_43_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_43),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_43_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_44_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_44),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_44_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_45_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_45),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_45_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_46_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_46),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_46_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
  OSPE pes_47_0 (	// src/main/scala/scarf/compute/MMCU.scala:49:11
    .clock     (clock),
    .reset     (reset),
    .io_aIn    (io_aRow_47),
    .io_bIn    (io_bCol_0),
    .io_accOut (io_results_47_0),
    .io_enable (io_enable),
    .io_clear  (io_clear)
  );
endmodule
