// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module PipelineController(	// src/main/scala/scarf/control/PipelineController.scala:17:7
  input         clock,	// src/main/scala/scarf/control/PipelineController.scala:17:7
                reset,	// src/main/scala/scarf/control/PipelineController.scala:17:7
                io_start,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  output        io_done,	// src/main/scala/scarf/control/PipelineController.scala:18:14
                io_busy,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input  [7:0]  io_config_numDepthCandidates,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input  [8:0]  io_config_featureDim,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input  [9:0]  io_config_imageH,	// src/main/scala/scarf/control/PipelineController.scala:18:14
                io_config_imageW,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input  [3:0]  io_config_tileSize,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input  [7:0]  io_config_cnnLayers,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input  [3:0]  io_config_transformerLayers,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input         io_config_hasDINOv2,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input  [5:0]  io_config_dinov2Layers,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input         io_config_saesEnabled,	// src/main/scala/scarf/control/PipelineController.scala:18:14
                io_config_fsdrEnabled,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input  [31:0] io_config_numGaussians,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input         io_config_payloadValid,	// src/main/scala/scarf/control/PipelineController.scala:18:14
                io_configValid,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  output        io_mmcuStart,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input         io_mmcuDone,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  output        io_bilinearStart,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input         io_bilinearDone,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  output        io_gguStart,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input         io_gguDone,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  output        io_tilePayloadStart,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input         io_tilePayloadReady,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  output [31:0] io_workGroupIndex,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input  [1:0]  io_saesLevel,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input         io_saesClassifyDone,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  output        io_saesClassifyStart,	// src/main/scala/scarf/control/PipelineController.scala:18:14
                io_fsdrStart,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input         io_fsdrDone,	// src/main/scala/scarf/control/PipelineController.scala:18:14
                io_fsdrUseNarrow,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  input  [7:0]  io_fsdrNarrowCands,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  output [7:0]  io_costVolCandidates,	// src/main/scala/scarf/control/PipelineController.scala:18:14
  output [4:0]  io_saesRetainedDescriptors,	// src/main/scala/scarf/control/PipelineController.scala:18:14
                io_state	// src/main/scala/scarf/control/PipelineController.scala:18:14
);

  reg  [4:0]  state;	// src/main/scala/scarf/control/PipelineController.scala:63:22
  reg         costVolMmcuDoneSeen;	// src/main/scala/scarf/control/PipelineController.scala:68:36
  reg         costVolBilinearDoneSeen;	// src/main/scala/scarf/control/PipelineController.scala:69:40
  reg         costVolBilinearLaunchPending;	// src/main/scala/scarf/control/PipelineController.scala:70:45
  reg  [7:0]  costVolPass;	// src/main/scala/scarf/control/PipelineController.scala:71:28
  reg  [31:0] gaussianBatch;	// src/main/scala/scarf/control/PipelineController.scala:75:30
  reg  [7:0]  cnnLayer;	// src/main/scala/scarf/control/PipelineController.scala:104:25
  reg  [3:0]  txLayer;	// src/main/scala/scarf/control/PipelineController.scala:105:25
  reg  [5:0]  dinov2Layer;	// src/main/scala/scarf/control/PipelineController.scala:106:28
  reg  [1:0]  saesResult;	// src/main/scala/scarf/control/PipelineController.scala:107:27
  reg  [7:0]  fsdrTileCandidates;	// src/main/scala/scarf/control/PipelineController.scala:111:35
  reg         tilePayloadAwaiting;	// src/main/scala/scarf/control/PipelineController.scala:115:36
  reg         mmcuLaunchPending;	// src/main/scala/scarf/control/PipelineController.scala:119:34
  reg         mmcuAwaitingDone;	// src/main/scala/scarf/control/PipelineController.scala:120:33
  reg  [4:0]  prevState;	// src/main/scala/scarf/control/PipelineController.scala:131:26
  wire        stateEntry = state != prevState;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :131:26, :132:26
  wire        _io_bilinearStart_T = state == 5'h8;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :136:11, :306:15
  wire        mmcuTaskState =
    state == 5'h2 | state == 5'h3 | state == 5'h4 | _io_bilinearStart_T | state == 5'h9
    | state == 5'hA | state == 5'hB | state == 5'hC | state == 5'hD;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :133:29, :134:11, :135:11, :136:11, :137:11, :138:11, :139:11, :140:{11,36}, :141:11, :157:72, :214:16, :222:19, :315:17, :327:36, :330:36, :338:36
  reg  [4:0]  casez_tmp;	// src/main/scala/scarf/control/PipelineController.scala:157:72
  always_comb begin	// src/main/scala/scarf/control/PipelineController.scala:157:72
    casez (saesResult)	// src/main/scala/scarf/control/PipelineController.scala:107:27, :157:72
      2'b00:
        casez_tmp = 5'h10;	// src/main/scala/scarf/control/PipelineController.scala:157:72
      2'b01:
        casez_tmp = 5'h4;	// src/main/scala/scarf/control/PipelineController.scala:157:72
      2'b10:
        casez_tmp = 5'hC;	// src/main/scala/scarf/control/PipelineController.scala:157:72
      default:
        casez_tmp = 5'h10;	// src/main/scala/scarf/control/PipelineController.scala:157:72
    endcase	// src/main/scala/scarf/control/PipelineController.scala:107:27, :157:72
  end // always_comb
  wire        _GEN = state == 5'h8;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :174:{14,41}, :178:17, :179:26, :306:15
  wire        _GEN_0 = state == 5'h5;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :192:{14,44}, :193:25, :194:26, :253:17
  wire        _GEN_1 = state == 5'h0;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17, :373:31
  wire        _GEN_2 = state == 5'h1;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17, :203:15
  wire        _GEN_3 = state == 5'h2;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17, :214:16
  wire        _GEN_4 = state == 5'h3;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17, :222:19
  wire        _GEN_5 = state == 5'h4;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :157:72, :200:17
  wire        _GEN_6 = _GEN_3 | _GEN_4 | _GEN_5;	// src/main/scala/scarf/control/PipelineController.scala:153:24, :200:17
  wire        _GEN_7 = state == 5'h6;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17
  wire        _GEN_8 = _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_0;	// src/main/scala/scarf/control/PipelineController.scala:154:24, :192:{14,44}, :193:25, :194:26, :200:17
  wire        _GEN_9 = state == 5'h7;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17
  wire        _GEN_10 = state == 5'h9;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17, :315:17
  wire        _GEN_11 = state == 5'hA;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17, :327:36
  wire        _GEN_12 = state == 5'hB;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17, :330:36
  wire        _GEN_13 = state == 5'hC;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :157:72, :200:17
  wire        _GEN_14 = state == 5'hD;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17, :338:36
  wire        _GEN_15 = state == 5'hE;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17, :341:36
  wire [9:0]  _GEN_16 = {6'h0, io_config_tileSize};	// src/main/scala/scarf/control/PipelineController.scala:82:36, :106:28
  wire [9:0]  _numTileCols_T_4 = (io_config_imageW + _GEN_16 - 10'h1) / _GEN_16;	// src/main/scala/scarf/control/PipelineController.scala:82:36, :83:{57,64}
  wire [9:0]  _numTileRows_T_4 = (io_config_imageH + _GEN_16 - 10'h1) / _GEN_16;	// src/main/scala/scarf/control/PipelineController.scala:82:{36,57,64}
  wire [15:0] _imageTileCount_T =
    {8'h0, _numTileRows_T_4[7:0]} * {8'h0, _numTileCols_T_4[7:0]};	// src/main/scala/scarf/control/PipelineController.scala:71:28, :82:{15,64}, :83:{15,64}, :84:37
  wire [31:0] _payloadGaussianBatches_T = io_config_numGaussians + 32'h1F;	// src/main/scala/scarf/control/PipelineController.scala:86:30
  wire [31:0] _GEN_17 = {5'h0, _payloadGaussianBatches_T[31:5]};	// src/main/scala/scarf/control/PipelineController.scala:86:{30,64,73}, :373:31
  wire [16:0] _GEN_18 = {1'h0, _imageTileCount_T} + 17'hF;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :84:{37,55}, :87:44
  wire [7:0]  _payloadDepthGroups_T = io_config_numDepthCandidates + 8'h3;	// src/main/scala/scarf/control/PipelineController.scala:88:59
  wire [8:0]  _payloadFeatureGroups_T = io_config_featureDim + 9'h3;	// src/main/scala/scarf/control/PipelineController.scala:89:53
  wire [33:0] _payloadGaussianWork_T_1 =
    {7'h0, _payloadGaussianBatches_T[31:5]} * 34'h3 + 34'h7;	// src/main/scala/scarf/control/PipelineController.scala:86:{30,64}, :94:{31,38}
  wire [65:0] _payloadDepthWork_T_2 =
    {2'h0, {51'h0, _GEN_18[16:4]} * {58'h0, _payloadDepthGroups_T[7:2]}} * 66'h3 + 66'h7;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :84:55, :87:{44,52}, :88:{59,66,75}, :91:{26,47,54,75}
  wire [62:0] _payloadBaseWork_T_2 =
    {50'h0, _GEN_18[16:4]} + {57'h0, _payloadDepthGroups_T[7:2]}
    + _payloadDepthWork_T_2[65:3]
    + {31'h0,
       {1'h0, _payloadGaussianWork_T_1[33:3]} + (_GEN_17 < 32'h8 ? _GEN_17 : 32'h8)}
    + {26'h0, {30'h0, _payloadFeatureGroups_T[8:2]} * 37'h16};	// src/main/scala/scarf/control/PipelineController.scala:63:22, :84:55, :86:73, :87:{44,52,61}, :88:{59,66,75}, :89:{53,60}, :91:{54,61,75}, :92:26, :94:{38,45,54,59}, :95:{10,34}, :96:50, :97:{43,65}, :98:27
  wire [7:0]  fsdrCandidates =
    io_fsdrUseNarrow ? io_fsdrNarrowCands : io_config_numDepthCandidates;	// src/main/scala/scarf/control/PipelineController.scala:293:33
  wire        _GEN_19 = state == 5'hF;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :200:17, :347:32
  wire [31:0] _gaussianBatch_T = gaussianBatch + 32'h1;	// src/main/scala/scarf/control/PipelineController.scala:75:30, :354:38
  wire        mmcuCompletion = ~stateEntry & mmcuAwaitingDone & io_mmcuDone;	// src/main/scala/scarf/control/PipelineController.scala:120:33, :132:26, :142:{24,56}
  wire        _GEN_20 = state == prevState;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :131:26, :132:26, :166:26, :167:23, :169:33
  wire        _GEN_21 = mmcuTaskState & ~_GEN_20;	// src/main/scala/scarf/control/PipelineController.scala:132:26, :140:36, :163:24, :164:23, :166:26, :167:23, :169:33
  wire        _GEN_22 = mmcuTaskState & _GEN_20 & (mmcuLaunchPending | mmcuAwaitingDone);	// src/main/scala/scarf/control/PipelineController.scala:119:34, :120:33, :132:26, :140:36, :163:24, :165:22, :166:26, :167:23, :169:33, :171:22
  wire        _GEN_23 = _GEN & _GEN_20;	// src/main/scala/scarf/control/PipelineController.scala:71:28, :132:26, :166:26, :167:23, :169:33, :174:{14,41}, :178:17, :179:26, :183:17
  wire        _GEN_24 = mmcuCompletion | costVolMmcuDoneSeen;	// src/main/scala/scarf/control/PipelineController.scala:68:36, :142:56, :188:{26,48}
  wire        _GEN_25 = io_bilinearDone | costVolBilinearDoneSeen;	// src/main/scala/scarf/control/PipelineController.scala:69:40, :189:{27,53}
  wire        _GEN_26 = cnnLayer >= io_config_cnnLayers - 8'h1;	// src/main/scala/scarf/control/PipelineController.scala:104:25, :221:{23,46}
  wire        _GEN_27 = txLayer >= io_config_transformerLayers - 4'h1;	// src/main/scala/scarf/control/PipelineController.scala:105:25, :235:{22,53}
  wire        _GEN_28 = dinov2Layer >= io_config_dinov2Layers - 6'h1;	// src/main/scala/scarf/control/PipelineController.scala:106:28, :252:{26,52}
  wire        _GEN_29 =
    (costVolBilinearDoneSeen | io_bilinearDone) & (costVolMmcuDoneSeen | mmcuCompletion);	// src/main/scala/scarf/control/PipelineController.scala:68:36, :69:40, :142:56, :312:{37,57}, :313:33
  wire [7:0]  _costVolPass_T = costVolPass + 8'h1;	// src/main/scala/scarf/control/PipelineController.scala:71:28, :144:29, :314:26
  wire [7:0]  _costVolPassCount_T_3 = fsdrTileCandidates + 8'h1F;	// src/main/scala/scarf/control/PipelineController.scala:111:35, :147:25
  wire        _GEN_30 =
    _costVolPass_T >= (fsdrTileCandidates == 8'h0
                         ? 8'h1
                         : {5'h0, _costVolPassCount_T_3[7:5]});	// src/main/scala/scarf/control/PipelineController.scala:71:28, :111:35, :144:29, :145:24, :147:{25,61}, :314:{26,32}, :373:31
  wire        _GEN_31 = _GEN & _GEN_29;	// src/main/scala/scarf/control/PipelineController.scala:174:{14,41}, :178:17, :179:26, :200:17, :312:57, :313:53, :314:53
  wire        _GEN_32 = _GEN_0 | _GEN_7 | _GEN_9;	// src/main/scala/scarf/control/PipelineController.scala:174:41, :192:{14,44}, :193:25, :194:26, :200:17
  wire        _GEN_33 = _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_32;	// src/main/scala/scarf/control/PipelineController.scala:174:41, :200:17
  wire        _GEN_34 = _GEN_1 | _GEN_2;	// src/main/scala/scarf/control/PipelineController.scala:163:24, :200:17
  wire        _GEN_35 = _GEN_30 & _GEN_23;	// src/main/scala/scarf/control/PipelineController.scala:71:28, :132:26, :174:{14,41}, :175:25, :178:17, :179:26, :180:25, :183:17, :188:26, :314:{32,53}, :318:31
  always @(posedge clock) begin	// src/main/scala/scarf/control/PipelineController.scala:17:7
    if (reset) begin	// src/main/scala/scarf/control/PipelineController.scala:17:7
      state <= 5'h0;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :373:31
      costVolMmcuDoneSeen <= 1'h0;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :68:36
      costVolBilinearDoneSeen <= 1'h0;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :69:40
      costVolBilinearLaunchPending <= 1'h0;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :70:45
      costVolPass <= 8'h0;	// src/main/scala/scarf/control/PipelineController.scala:71:28
      gaussianBatch <= 32'h0;	// src/main/scala/scarf/control/PipelineController.scala:75:30
      cnnLayer <= 8'h0;	// src/main/scala/scarf/control/PipelineController.scala:71:28, :104:25
      txLayer <= 4'h0;	// src/main/scala/scarf/control/PipelineController.scala:105:25
      dinov2Layer <= 6'h0;	// src/main/scala/scarf/control/PipelineController.scala:106:28
      saesResult <= 2'h0;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :107:27
      fsdrTileCandidates <= 8'h0;	// src/main/scala/scarf/control/PipelineController.scala:71:28, :111:35
      tilePayloadAwaiting <= 1'h0;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :115:36
      mmcuLaunchPending <= 1'h0;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :119:34
      mmcuAwaitingDone <= 1'h0;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :120:33
      prevState <= 5'h0;	// src/main/scala/scarf/control/PipelineController.scala:131:26, :373:31
    end
    else begin	// src/main/scala/scarf/control/PipelineController.scala:17:7
      if (_GEN_1) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
        if (io_start & io_configValid)	// src/main/scala/scarf/control/PipelineController.scala:202:21
          state <= 5'h1;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :203:15
      end
      else if (_GEN_2) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
        state <= 5'h2;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :214:16
        gaussianBatch <= 32'h0;	// src/main/scala/scarf/control/PipelineController.scala:75:30
        cnnLayer <= 8'h0;	// src/main/scala/scarf/control/PipelineController.scala:71:28, :104:25
        txLayer <= 4'h0;	// src/main/scala/scarf/control/PipelineController.scala:105:25
        dinov2Layer <= 6'h0;	// src/main/scala/scarf/control/PipelineController.scala:106:28
        fsdrTileCandidates <= io_config_numDepthCandidates;	// src/main/scala/scarf/control/PipelineController.scala:111:35
      end
      else begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
        if (_GEN_3) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
          if (mmcuCompletion & _GEN_26) begin	// src/main/scala/scarf/control/PipelineController.scala:63:22, :142:56, :219:28, :221:{23,53}, :222:19
            state <= 5'h3;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :222:19
            txLayer <= 4'h0;	// src/main/scala/scarf/control/PipelineController.scala:105:25
          end
        end
        else begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
          if (_GEN_4) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (mmcuCompletion & _GEN_27)	// src/main/scala/scarf/control/PipelineController.scala:63:22, :142:56, :233:28, :235:{22,60}, :236:17
              state <= {4'h2, ~(io_config_hasDINOv2 & (|io_config_dinov2Layers))};	// src/main/scala/scarf/control/PipelineController.scala:63:22, :236:{17,23}, :237:{33,59}
          end
          else if (_GEN_5) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (mmcuCompletion & _GEN_28)	// src/main/scala/scarf/control/PipelineController.scala:63:22, :142:56, :250:28, :252:{26,59}, :253:17
              state <= 5'h5;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :253:17
          end
          else if (_GEN_0) begin	// src/main/scala/scarf/control/PipelineController.scala:192:{14,44}, :193:25, :194:26
            if (~stateEntry & tilePayloadAwaiting & io_tilePayloadReady)	// src/main/scala/scarf/control/PipelineController.scala:115:36, :132:26, :142:24, :265:47
              state <=
                {1'h0,
                 io_config_saesEnabled ? 4'h6 : io_config_fsdrEnabled ? 4'h7 : 4'h8};	// src/main/scala/scarf/control/PipelineController.scala:63:22, :95:34, :266:{15,21}, :269:14
          end
          else if (_GEN_7) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (io_saesClassifyDone)	// src/main/scala/scarf/control/PipelineController.scala:18:14
              state <= {1'h0, io_config_fsdrEnabled ? 4'h7 : 4'h8};	// src/main/scala/scarf/control/PipelineController.scala:63:22, :95:34, :269:14, :283:{15,21}
          end
          else if (_GEN_9) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (io_fsdrDone)	// src/main/scala/scarf/control/PipelineController.scala:18:14
              state <= 5'h8;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :306:15
          end
          else if (_GEN) begin	// src/main/scala/scarf/control/PipelineController.scala:174:{14,41}, :178:17, :179:26
            if (_GEN_29 & _GEN_30)	// src/main/scala/scarf/control/PipelineController.scala:63:22, :312:57, :313:53, :314:{32,53}, :315:17
              state <= 5'h9;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :315:17
          end
          else if (_GEN_10) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (mmcuCompletion)	// src/main/scala/scarf/control/PipelineController.scala:142:56
              state <= 5'hA;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :327:36
          end
          else if (_GEN_11) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (mmcuCompletion)	// src/main/scala/scarf/control/PipelineController.scala:142:56
              state <= 5'hB;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :330:36
          end
          else if (_GEN_12) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (mmcuCompletion)	// src/main/scala/scarf/control/PipelineController.scala:142:56
              state <= 5'hC;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :157:72
          end
          else if (_GEN_13) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (mmcuCompletion)	// src/main/scala/scarf/control/PipelineController.scala:142:56
              state <= 5'hD;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :338:36
          end
          else if (_GEN_14) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (mmcuCompletion)	// src/main/scala/scarf/control/PipelineController.scala:142:56
              state <= 5'hE;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :341:36
          end
          else if (_GEN_15) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (io_gguDone)	// src/main/scala/scarf/control/PipelineController.scala:18:14
              state <= 5'hF;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :347:32
          end
          else if (_GEN_19)	// src/main/scala/scarf/control/PipelineController.scala:200:17
            state <=
              {31'h0,
               _gaussianBatch_T} >= (io_config_payloadValid & (|io_config_numGaussians)
                                       ? (_payloadBaseWork_T_2 == 63'h0
                                            ? 63'h1
                                            : _payloadBaseWork_T_2)
                                       : {47'h0, _imageTileCount_T})
                ? 5'h10
                : 5'h5;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :84:37, :97:65, :98:27, :99:{28,54}, :100:{8,25}, :122:20, :253:17, :354:38, :365:{32,51}, :366:15, :368:15
          else if (state == 5'h10 & ~io_start)	// src/main/scala/scarf/control/PipelineController.scala:63:22, :122:20, :200:17, :373:{12,23,31}
            state <= 5'h0;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :373:31
          if (_GEN_4 & mmcuCompletion)	// src/main/scala/scarf/control/PipelineController.scala:105:25, :142:56, :200:17, :233:28, :234:17
            txLayer <= txLayer + 4'h1;	// src/main/scala/scarf/control/PipelineController.scala:105:25, :203:15, :234:28
        end
        if (_GEN_3 | _GEN_4 | _GEN_5 | _GEN_0 | _GEN_7 | _GEN_9 | _GEN | _GEN_10 | _GEN_11
            | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | ~_GEN_19) begin	// src/main/scala/scarf/control/PipelineController.scala:75:30, :174:{14,41}, :178:17, :179:26, :192:{14,44}, :193:25, :194:26, :200:17
        end
        else	// src/main/scala/scarf/control/PipelineController.scala:75:30, :200:17
          gaussianBatch <= _gaussianBatch_T;	// src/main/scala/scarf/control/PipelineController.scala:75:30, :354:38
        if (_GEN_3 & mmcuCompletion)	// src/main/scala/scarf/control/PipelineController.scala:104:25, :142:56, :200:17, :219:28, :220:18
          cnnLayer <= cnnLayer + 8'h1;	// src/main/scala/scarf/control/PipelineController.scala:104:25, :144:29, :220:30
        if (_GEN_3 | _GEN_4 | ~(_GEN_5 & mmcuCompletion)) begin	// src/main/scala/scarf/control/PipelineController.scala:106:28, :142:56, :200:17, :250:28, :251:21
        end
        else	// src/main/scala/scarf/control/PipelineController.scala:106:28, :200:17
          dinov2Layer <= dinov2Layer + 6'h1;	// src/main/scala/scarf/control/PipelineController.scala:106:28, :251:36
        if (~_GEN_6) begin	// src/main/scala/scarf/control/PipelineController.scala:153:24, :200:17
          if (_GEN_0)	// src/main/scala/scarf/control/PipelineController.scala:192:{14,44}, :193:25, :194:26
            fsdrTileCandidates <= io_config_numDepthCandidates;	// src/main/scala/scarf/control/PipelineController.scala:111:35
          else if (_GEN_7) begin	// src/main/scala/scarf/control/PipelineController.scala:200:17
            if (io_saesClassifyDone & ~io_config_fsdrEnabled & (|io_saesLevel)
                & io_config_numDepthCandidates > 8'h20)	// src/main/scala/scarf/control/PipelineController.scala:111:35, :275:33, :279:{14,53}, :280:{40,48}, :281:30
              fsdrTileCandidates <= io_config_numDepthCandidates - 8'h20;	// src/main/scala/scarf/control/PipelineController.scala:111:35, :281:62
          end
          else if (_GEN_9 & io_fsdrDone)	// src/main/scala/scarf/control/PipelineController.scala:111:35, :200:17, :292:25, :301:28
            fsdrTileCandidates <=
              saesResult == 2'h1 & fsdrCandidates > 8'h20
                ? fsdrCandidates - 8'h20
                : fsdrCandidates;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :107:27, :111:35, :280:40, :293:33, :301:34, :302:{22,40,58}, :303:26
        end
      end
      if (_GEN_33 | ~_GEN_31) begin	// src/main/scala/scarf/control/PipelineController.scala:174:41, :200:17, :313:53, :314:53
        costVolMmcuDoneSeen <= _GEN_23 & _GEN_24;	// src/main/scala/scarf/control/PipelineController.scala:68:36, :71:28, :132:26, :174:{14,41}, :175:25, :178:17, :179:26, :180:25, :183:17, :188:{26,48}
        costVolBilinearDoneSeen <= _GEN_23 & _GEN_25;	// src/main/scala/scarf/control/PipelineController.scala:69:40, :71:28, :132:26, :174:{14,41}, :176:29, :178:17, :179:26, :181:29, :183:17, :189:{27,53}
      end
      else begin	// src/main/scala/scarf/control/PipelineController.scala:174:41, :200:17
        costVolMmcuDoneSeen <= _GEN_35 & _GEN_24;	// src/main/scala/scarf/control/PipelineController.scala:68:36, :132:26, :174:{14,41}, :175:25, :179:26, :180:25, :188:{26,48}, :314:53, :318:31
        costVolBilinearDoneSeen <= _GEN_35 & _GEN_25;	// src/main/scala/scarf/control/PipelineController.scala:69:40, :132:26, :174:{14,41}, :175:25, :176:29, :179:26, :180:25, :181:29, :188:26, :189:{27,53}, :314:53, :318:31, :319:35
      end
      costVolBilinearLaunchPending <= ~_GEN_33 & _GEN_31 & ~_GEN_30 | _GEN & ~_GEN_20;	// src/main/scala/scarf/control/PipelineController.scala:70:45, :132:26, :166:26, :167:23, :169:33, :174:{14,41}, :177:34, :178:17, :179:26, :200:17, :313:53, :314:{32,53}, :320:40
      if (_GEN_33 | ~_GEN_31 | _GEN_30) begin	// src/main/scala/scarf/control/PipelineController.scala:174:41, :200:17, :313:53, :314:{32,53}
        if (~_GEN_23)	// src/main/scala/scarf/control/PipelineController.scala:71:28, :132:26, :174:{14,41}, :178:17, :179:26, :183:17
          costVolPass <= 8'h0;	// src/main/scala/scarf/control/PipelineController.scala:71:28
      end
      else	// src/main/scala/scarf/control/PipelineController.scala:174:41, :200:17
        costVolPass <= _costVolPass_T;	// src/main/scala/scarf/control/PipelineController.scala:71:28, :314:26
      if (_GEN_8 | ~(_GEN_7 & io_saesClassifyDone)) begin	// src/main/scala/scarf/control/PipelineController.scala:107:27, :154:24, :200:17, :275:33, :276:20
      end
      else	// src/main/scala/scarf/control/PipelineController.scala:107:27, :200:17
        saesResult <= io_saesLevel;	// src/main/scala/scarf/control/PipelineController.scala:107:27
      tilePayloadAwaiting <=
        _GEN_0
        & (~_GEN_20 | ~(tilePayloadAwaiting & io_tilePayloadReady) & tilePayloadAwaiting);	// src/main/scala/scarf/control/PipelineController.scala:115:36, :132:26, :166:26, :167:23, :169:33, :192:{14,44}, :193:25, :194:26, :195:25, :196:{34,58}, :197:25
      mmcuLaunchPending <=
        _GEN_34
          ? _GEN_21
          : _GEN_3
              ? mmcuCompletion & ~_GEN_26 | _GEN_21
              : _GEN_4
                  ? mmcuCompletion & ~_GEN_27 | _GEN_21
                  : _GEN_5
                      ? mmcuCompletion & ~_GEN_28 | _GEN_21
                      : ~_GEN_32 & _GEN_31 & ~_GEN_30 | _GEN_21;	// src/main/scala/scarf/control/PipelineController.scala:119:34, :142:56, :163:24, :164:23, :166:26, :174:41, :200:17, :219:28, :221:{23,53}, :225:29, :233:28, :235:{22,60}, :242:29, :250:28, :252:{26,59}, :255:29, :313:53, :314:{32,53}, :320:40
      if (_GEN_34)	// src/main/scala/scarf/control/PipelineController.scala:163:24, :200:17
        mmcuAwaitingDone <= _GEN_22;	// src/main/scala/scarf/control/PipelineController.scala:120:33, :163:24, :165:22, :166:26
      else if (_GEN_3)	// src/main/scala/scarf/control/PipelineController.scala:200:17
        mmcuAwaitingDone <= (~mmcuCompletion | _GEN_26) & _GEN_22;	// src/main/scala/scarf/control/PipelineController.scala:120:33, :142:56, :163:24, :165:22, :166:26, :219:28, :221:{23,53}
      else if (_GEN_4)	// src/main/scala/scarf/control/PipelineController.scala:200:17
        mmcuAwaitingDone <= (~mmcuCompletion | _GEN_27) & _GEN_22;	// src/main/scala/scarf/control/PipelineController.scala:120:33, :142:56, :163:24, :165:22, :166:26, :219:28, :221:53, :233:28, :235:{22,60}
      else if (_GEN_5)	// src/main/scala/scarf/control/PipelineController.scala:200:17
        mmcuAwaitingDone <= (~mmcuCompletion | _GEN_28) & _GEN_22;	// src/main/scala/scarf/control/PipelineController.scala:120:33, :142:56, :163:24, :165:22, :166:26, :219:28, :221:53, :250:28, :252:{26,59}
      else	// src/main/scala/scarf/control/PipelineController.scala:200:17
        mmcuAwaitingDone <= (_GEN_32 | ~_GEN_31 | _GEN_30) & _GEN_22;	// src/main/scala/scarf/control/PipelineController.scala:120:33, :163:24, :165:22, :166:26, :174:41, :200:17, :313:53, :314:{32,53}
      prevState <= state;	// src/main/scala/scarf/control/PipelineController.scala:63:22, :131:26
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/control/PipelineController.scala:17:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/control/PipelineController.scala:17:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/control/PipelineController.scala:17:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// src/main/scala/scarf/control/PipelineController.scala:17:7
    initial begin	// src/main/scala/scarf/control/PipelineController.scala:17:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/control/PipelineController.scala:17:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/control/PipelineController.scala:17:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/control/PipelineController.scala:17:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// src/main/scala/scarf/control/PipelineController.scala:17:7
        end	// src/main/scala/scarf/control/PipelineController.scala:17:7
        state = _RANDOM[2'h0][4:0];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :63:22
        costVolMmcuDoneSeen = _RANDOM[2'h0][5];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :63:22, :68:36
        costVolBilinearDoneSeen = _RANDOM[2'h0][6];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :63:22, :69:40
        costVolBilinearLaunchPending = _RANDOM[2'h0][7];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :63:22, :70:45
        costVolPass = _RANDOM[2'h0][15:8];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :63:22, :71:28
        gaussianBatch = _RANDOM[2'h1];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :75:30
        cnnLayer = _RANDOM[2'h2][7:0];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :104:25
        txLayer = _RANDOM[2'h2][11:8];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :104:25, :105:25
        dinov2Layer = _RANDOM[2'h2][17:12];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :104:25, :106:28
        saesResult = _RANDOM[2'h2][19:18];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :104:25, :107:27
        fsdrTileCandidates = _RANDOM[2'h2][27:20];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :104:25, :111:35
        tilePayloadAwaiting = _RANDOM[2'h2][28];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :104:25, :115:36
        mmcuLaunchPending = _RANDOM[2'h2][29];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :104:25, :119:34
        mmcuAwaitingDone = _RANDOM[2'h2][30];	// src/main/scala/scarf/control/PipelineController.scala:17:7, :104:25, :120:33
        prevState = {_RANDOM[2'h2][31], _RANDOM[2'h3][3:0]};	// src/main/scala/scarf/control/PipelineController.scala:17:7, :104:25, :131:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/control/PipelineController.scala:17:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/control/PipelineController.scala:17:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_done = state == 5'h10;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :63:22, :122:20
  assign io_busy = |state;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :63:22, :123:20
  assign io_mmcuStart = mmcuTaskState & mmcuLaunchPending;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :119:34, :140:36, :150:41
  assign io_bilinearStart = _io_bilinearStart_T & costVolBilinearLaunchPending;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :70:45, :136:11, :151:59
  assign io_gguStart =
    ~(_GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_0 | _GEN_7 | _GEN_9 | _GEN
      | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14) & _GEN_15 & stateEntry;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :132:26, :152:24, :174:{14,41}, :178:17, :179:26, :192:{14,44}, :193:25, :194:26, :200:17
  assign io_tilePayloadStart = ~(_GEN_1 | _GEN_2 | _GEN_6) & _GEN_0 & stateEntry;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :132:26, :153:24, :192:{14,44}, :193:25, :194:26, :200:17
  assign io_workGroupIndex = gaussianBatch;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :75:30
  assign io_saesClassifyStart = ~_GEN_8 & _GEN_7 & stateEntry;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :132:26, :154:24, :200:17
  assign io_fsdrStart =
    ~(_GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_0 | _GEN_7) & _GEN_9 & stateEntry;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :132:26, :155:24, :192:{14,44}, :193:25, :194:26, :200:17
  assign io_costVolCandidates = fsdrTileCandidates;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :111:35
  assign io_saesRetainedDescriptors = casez_tmp;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :157:72
  assign io_state = state;	// src/main/scala/scarf/control/PipelineController.scala:17:7, :63:22
endmodule
