// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module PositionCalc(	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
  input         clock,	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
                reset,	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
  input  [9:0]  io_pixelX,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_pixelY,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
  input  [15:0] io_depth,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
  input  [31:0] io_cx,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_cy,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_extrinsics_0,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_extrinsics_1,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_extrinsics_2,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_extrinsics_6,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_extrinsics_7,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_extrinsics_8,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_extrinsics_9,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_extrinsics_11,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
  input         io_start,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
  output        io_done,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
  output [31:0] io_posX,	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
                io_posZ	// src/main/scala/scarf/ggu/PositionCalc.scala:118:14
);

  wire        _transform_io_done;	// src/main/scala/scarf/ggu/PositionCalc.scala:135:25
  wire        _unproj_io_done;	// src/main/scala/scarf/ggu/PositionCalc.scala:134:25
  wire [31:0] _unproj_io_camX;	// src/main/scala/scarf/ggu/PositionCalc.scala:134:25
  wire [31:0] _unproj_io_camY;	// src/main/scala/scarf/ggu/PositionCalc.scala:134:25
  wire [31:0] _unproj_io_camZ;	// src/main/scala/scarf/ggu/PositionCalc.scala:134:25
  reg  [1:0]  state;	// src/main/scala/scarf/ggu/PositionCalc.scala:138:22
  reg  [1:0]  casez_tmp;	// src/main/scala/scarf/ggu/PositionCalc.scala:163:17, :165:22
  always_comb begin	// src/main/scala/scarf/ggu/PositionCalc.scala:138:22, :163:17, :165:22, :168:28, :171:31, :174:13
    casez (state)	// src/main/scala/scarf/ggu/PositionCalc.scala:138:22, :163:17, :165:22, :168:28, :171:31, :174:13
      2'b00:
        casez_tmp = io_start ? 2'h1 : state;	// src/main/scala/scarf/ggu/PositionCalc.scala:138:22, :147:29, :163:17, :165:{22,30}, :168:28, :171:31, :174:13
      2'b01:
        casez_tmp = _unproj_io_done ? 2'h2 : state;	// src/main/scala/scarf/ggu/PositionCalc.scala:134:25, :138:22, :156:36, :163:17, :165:22, :168:{28,36}, :171:31, :174:13
      2'b10:
        casez_tmp = _transform_io_done ? 2'h3 : state;	// src/main/scala/scarf/ggu/PositionCalc.scala:135:25, :138:22, :158:20, :163:17, :165:22, :168:28, :171:{31,39}, :174:13
      default:
        casez_tmp = 2'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:138:22, :163:17, :165:22, :168:28, :171:31, :174:13
    endcase	// src/main/scala/scarf/ggu/PositionCalc.scala:138:22, :163:17, :165:22, :168:28, :171:31, :174:13
  end // always_comb
  always @(posedge clock) begin	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
    if (reset)	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
      state <= 2'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:138:22
    else	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
      state <= casez_tmp;	// src/main/scala/scarf/ggu/PositionCalc.scala:138:22, :163:17, :165:22
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
    initial begin	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
        state = _RANDOM[/*Zero width*/ 1'b0][1:0];	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7, :138:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  UnprojUnit unproj (	// src/main/scala/scarf/ggu/PositionCalc.scala:134:25
    .clock     (clock),
    .reset     (reset),
    .io_pixelX (io_pixelX),
    .io_pixelY (io_pixelY),
    .io_depth  (io_depth),
    .io_cx     (io_cx),
    .io_cy     (io_cy),
    .io_start  (state == 2'h1),	// src/main/scala/scarf/ggu/PositionCalc.scala:138:22, :147:29
    .io_done   (_unproj_io_done),
    .io_camX   (_unproj_io_camX),
    .io_camY   (_unproj_io_camY),
    .io_camZ   (_unproj_io_camZ)
  );
  TransformUnit transform (	// src/main/scala/scarf/ggu/PositionCalc.scala:135:25
    .clock            (clock),
    .reset            (reset),
    .io_camPos_0      (_unproj_io_camX),	// src/main/scala/scarf/ggu/PositionCalc.scala:134:25
    .io_camPos_1      (_unproj_io_camY),	// src/main/scala/scarf/ggu/PositionCalc.scala:134:25
    .io_camPos_2      (_unproj_io_camZ),	// src/main/scala/scarf/ggu/PositionCalc.scala:134:25
    .io_extrinsics_0  (io_extrinsics_0),
    .io_extrinsics_1  (io_extrinsics_1),
    .io_extrinsics_2  (io_extrinsics_2),
    .io_extrinsics_6  (io_extrinsics_6),
    .io_extrinsics_7  (io_extrinsics_7),
    .io_extrinsics_8  (io_extrinsics_8),
    .io_extrinsics_9  (io_extrinsics_9),
    .io_extrinsics_11 (io_extrinsics_11),
    .io_start         (state == 2'h2),	// src/main/scala/scarf/ggu/PositionCalc.scala:138:22, :156:36
    .io_done          (_transform_io_done),
    .io_worldPos_0    (io_posX),
    .io_worldPos_2    (io_posZ)
  );
  assign io_done = &state;	// src/main/scala/scarf/ggu/PositionCalc.scala:117:7, :138:22, :158:20
endmodule
