// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SAESController(	// src/main/scala/scarf/control/SAESController.scala:12:7
  input         clock,	// src/main/scala/scarf/control/SAESController.scala:12:7
                reset,	// src/main/scala/scarf/control/SAESController.scala:12:7
                io_start,	// src/main/scala/scarf/control/SAESController.scala:13:14
  output        io_done,	// src/main/scala/scarf/control/SAESController.scala:13:14
  input  [15:0] io_config_saesFeatureVarThresh,	// src/main/scala/scarf/control/SAESController.scala:13:14
                io_config_saesDepthStdThresh,	// src/main/scala/scarf/control/SAESController.scala:13:14
  input         io_config_saesEnabled,	// src/main/scala/scarf/control/SAESController.scala:13:14
  input  [15:0] io_probeFeatureVar,	// src/main/scala/scarf/control/SAESController.scala:13:14
                io_probeDepthStd,	// src/main/scala/scarf/control/SAESController.scala:13:14
  input         io_routeValid,	// src/main/scala/scarf/control/SAESController.scala:13:14
  input  [1:0]  io_routeLevel,	// src/main/scala/scarf/control/SAESController.scala:13:14
  input         io_l0MaterializationValid,	// src/main/scala/scarf/control/SAESController.scala:13:14
                io_l1MaterializationValid,	// src/main/scala/scarf/control/SAESController.scala:13:14
  output [1:0]  io_level,	// src/main/scala/scarf/control/SAESController.scala:13:14
                io_decisionCycles	// src/main/scala/scarf/control/SAESController.scala:13:14
);

  reg  [1:0] state;	// src/main/scala/scarf/control/SAESController.scala:40:22
  reg  [1:0] resultLevel;	// src/main/scala/scarf/control/SAESController.scala:41:28
  reg  [1:0] decisionCycles;	// src/main/scala/scarf/control/SAESController.scala:42:31
  wire       _GEN =
    io_probeFeatureVar < io_config_saesFeatureVarThresh & io_l0MaterializationValid;	// src/main/scala/scarf/control/SAESController.scala:62:{28,61}
  reg  [1:0] casez_tmp;	// src/main/scala/scarf/control/SAESController.scala:48:17, :50:22
  always_comb begin	// src/main/scala/scarf/control/SAESController.scala:42:31, :48:17, :50:22, :57:22, :72:22
    casez (state)	// src/main/scala/scarf/control/SAESController.scala:40:22, :42:31, :48:17, :50:22, :57:22, :72:22
      2'b00:
        casez_tmp = io_start ? 2'h1 : decisionCycles;	// src/main/scala/scarf/control/SAESController.scala:42:31, :48:17, :50:22, :51:21, :53:24, :57:22, :72:22
      2'b01:
        casez_tmp = decisionCycles + 2'h1;	// src/main/scala/scarf/control/SAESController.scala:42:31, :48:17, :50:22, :51:21, :57:{22,40}, :72:22
      2'b10:
        casez_tmp = decisionCycles + 2'h1;	// src/main/scala/scarf/control/SAESController.scala:42:31, :48:17, :50:22, :51:21, :57:22, :72:{22,40}
      default:
        casez_tmp = decisionCycles;	// src/main/scala/scarf/control/SAESController.scala:42:31, :48:17, :50:22, :57:22, :72:22
    endcase	// src/main/scala/scarf/control/SAESController.scala:40:22, :42:31, :48:17, :50:22, :57:22, :72:22
  end // always_comb
  reg  [1:0] casez_tmp_0;	// src/main/scala/scarf/control/SAESController.scala:48:17, :50:22
  always_comb begin	// src/main/scala/scarf/control/SAESController.scala:41:28, :48:17, :50:22, :58:27, :76:9
    casez (state)	// src/main/scala/scarf/control/SAESController.scala:40:22, :41:28, :48:17, :50:22, :58:27, :76:9
      2'b00:
        casez_tmp_0 = io_start ? 2'h0 : resultLevel;	// src/main/scala/scarf/control/SAESController.scala:40:22, :41:28, :48:17, :50:22, :52:21, :58:27, :76:9
      2'b01:
        casez_tmp_0 = io_routeValid ? io_routeLevel : _GEN ? 2'h1 : resultLevel;	// src/main/scala/scarf/control/SAESController.scala:41:28, :48:17, :50:22, :51:21, :58:27, :59:21, :62:61, :64:9, :65:21, :76:9
      2'b10:
        casez_tmp_0 =
          {io_probeDepthStd < io_config_saesDepthStdThresh & io_l1MaterializationValid,
           1'h0};	// src/main/scala/scarf/control/SAESController.scala:12:7, :41:28, :48:17, :50:22, :58:27, :74:{26,57}, :76:9, :77:21, :79:21
      default:
        casez_tmp_0 = resultLevel;	// src/main/scala/scarf/control/SAESController.scala:41:28, :48:17, :50:22, :58:27, :76:9
    endcase	// src/main/scala/scarf/control/SAESController.scala:40:22, :41:28, :48:17, :50:22, :58:27, :76:9
  end // always_comb
  reg  [1:0] casez_tmp_1;	// src/main/scala/scarf/control/SAESController.scala:48:17, :50:22
  always_comb begin	// src/main/scala/scarf/control/SAESController.scala:40:22, :48:17, :50:22, :58:27, :81:13, :84:13
    casez (state)	// src/main/scala/scarf/control/SAESController.scala:40:22, :48:17, :50:22, :58:27, :81:13, :84:13
      2'b00:
        casez_tmp_1 = io_start ? {~io_config_saesEnabled, 1'h1} : state;	// src/main/scala/scarf/control/SAESController.scala:12:7, :40:22, :48:17, :50:22, :51:{15,21}, :58:27, :81:13, :84:13
      2'b01:
        casez_tmp_1 = {1'h1, io_routeValid | _GEN};	// src/main/scala/scarf/control/SAESController.scala:12:7, :40:22, :48:17, :50:22, :58:27, :60:15, :62:61, :64:9, :66:15, :68:15, :81:13, :84:13
      2'b10:
        casez_tmp_1 = 2'h3;	// src/main/scala/scarf/control/SAESController.scala:40:22, :44:20, :48:17, :50:22, :58:27, :81:13, :84:13
      default:
        casez_tmp_1 = 2'h0;	// src/main/scala/scarf/control/SAESController.scala:40:22, :48:17, :50:22, :58:27, :81:13, :84:13
    endcase	// src/main/scala/scarf/control/SAESController.scala:40:22, :48:17, :50:22, :58:27, :81:13, :84:13
  end // always_comb
  always @(posedge clock) begin	// src/main/scala/scarf/control/SAESController.scala:12:7
    if (reset) begin	// src/main/scala/scarf/control/SAESController.scala:12:7
      state <= 2'h0;	// src/main/scala/scarf/control/SAESController.scala:40:22
      resultLevel <= 2'h0;	// src/main/scala/scarf/control/SAESController.scala:40:22, :41:28
      decisionCycles <= 2'h0;	// src/main/scala/scarf/control/SAESController.scala:40:22, :42:31
    end
    else begin	// src/main/scala/scarf/control/SAESController.scala:12:7
      state <= casez_tmp_1;	// src/main/scala/scarf/control/SAESController.scala:40:22, :48:17, :50:22
      resultLevel <= casez_tmp_0;	// src/main/scala/scarf/control/SAESController.scala:41:28, :48:17, :50:22
      decisionCycles <= casez_tmp;	// src/main/scala/scarf/control/SAESController.scala:42:31, :48:17, :50:22
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/control/SAESController.scala:12:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/control/SAESController.scala:12:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/control/SAESController.scala:12:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/scarf/control/SAESController.scala:12:7
    initial begin	// src/main/scala/scarf/control/SAESController.scala:12:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/control/SAESController.scala:12:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/control/SAESController.scala:12:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/control/SAESController.scala:12:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/scarf/control/SAESController.scala:12:7
        state = _RANDOM[/*Zero width*/ 1'b0][1:0];	// src/main/scala/scarf/control/SAESController.scala:12:7, :40:22
        resultLevel = _RANDOM[/*Zero width*/ 1'b0][3:2];	// src/main/scala/scarf/control/SAESController.scala:12:7, :40:22, :41:28
        decisionCycles = _RANDOM[/*Zero width*/ 1'b0][5:4];	// src/main/scala/scarf/control/SAESController.scala:12:7, :40:22, :42:31
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/control/SAESController.scala:12:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/control/SAESController.scala:12:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_done = &state;	// src/main/scala/scarf/control/SAESController.scala:12:7, :40:22, :44:20
  assign io_level = resultLevel;	// src/main/scala/scarf/control/SAESController.scala:12:7, :41:28
  assign io_decisionCycles = (&state) ? decisionCycles : 2'h0;	// src/main/scala/scarf/control/SAESController.scala:12:7, :40:22, :42:31, :44:20, :46:27
endmodule
