// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SHOPGenerator(	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
  input         clock,	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
                reset,	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
  input  [2:0]  io_shDegree,	// src/main/scala/scarf/ggu/SHOPGenerator.scala:23:14
  input         io_start,	// src/main/scala/scarf/ggu/SHOPGenerator.scala:23:14
  output        io_done,	// src/main/scala/scarf/ggu/SHOPGenerator.scala:23:14
  output [15:0] io_opacityOut	// src/main/scala/scarf/ggu/SHOPGenerator.scala:23:14
);

  reg  [2:0]  state;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22
  reg  [3:0]  bandIdx;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:41:25
  reg  [15:0] opacReg;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:50:24
  reg  [2:0]  casez_tmp;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:56:17, :58:22
  always_comb begin	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :58:22, :69:13, :83:13, :118:32, :127:13, :131:13
    casez (state)	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :58:22, :69:13, :83:13, :118:32, :127:13, :131:13
      3'b000:
        casez_tmp = io_start ? 3'h1 : state;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :58:22, :59:17, :69:13, :83:13, :118:32, :127:13, :131:13
      3'b001:
        casez_tmp = 3'h2;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :58:22, :69:13, :83:13, :118:32, :127:13, :131:13
      3'b010:
        casez_tmp = 3'h3;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :58:22, :69:13, :83:13, :118:32, :127:13, :131:13
      3'b011:
        casez_tmp = bandIdx >= {1'h0, io_shDegree == 3'h4 ? 3'h4 : 3'h2} ? 3'h4 : state;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :41:25, :56:17, :58:22, :69:13, :83:13, :102:45, :116:26, :117:{24,37}, :118:{20,32}, :119:15, :127:13, :131:13
      3'b100:
        casez_tmp = 3'h5;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :52:26, :56:17, :58:22, :69:13, :83:13, :118:32, :127:13, :131:13
      3'b101:
        casez_tmp = 3'h0;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :58:22, :69:13, :83:13, :118:32, :127:13, :131:13
      3'b110:
        casez_tmp = state;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :58:22, :69:13, :83:13, :118:32, :127:13, :131:13
      default:
        casez_tmp = state;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :58:22, :69:13, :83:13, :118:32, :127:13, :131:13
    endcase	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :58:22, :69:13, :83:13, :118:32, :127:13, :131:13
  end // always_comb
  wire        _GEN = state == 3'h0;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17
  wire        _GEN_0 = state == 3'h1;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :59:17
  wire        _GEN_1 = state == 3'h2;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :69:13
  wire        _GEN_2 = state == 3'h3;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :83:13
  always @(posedge clock) begin	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
    if (reset) begin	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
      state <= 3'h0;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22
      bandIdx <= 4'h0;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:41:25
      opacReg <= 16'h0;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:40:33, :50:24
    end
    else begin	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
      state <= casez_tmp;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :56:17, :58:22
      if (_GEN) begin	// src/main/scala/scarf/ggu/SHOPGenerator.scala:56:17
        if (io_start)	// src/main/scala/scarf/ggu/SHOPGenerator.scala:23:14
          bandIdx <= 4'h0;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:41:25
      end
      else if (~_GEN_0) begin	// src/main/scala/scarf/ggu/SHOPGenerator.scala:56:17
        if (_GEN_1)	// src/main/scala/scarf/ggu/SHOPGenerator.scala:56:17
          bandIdx <= 4'h2;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:41:25, :84:15
        else if (_GEN_2)	// src/main/scala/scarf/ggu/SHOPGenerator.scala:56:17
          bandIdx <= bandIdx + 4'h1;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:41:25, :116:26
      end
      if (_GEN | _GEN_0 | _GEN_1 | _GEN_2 | state != 3'h4) begin	// src/main/scala/scarf/ggu/SHOPGenerator.scala:38:22, :50:24, :56:17, :102:45
      end
      else	// src/main/scala/scarf/ggu/SHOPGenerator.scala:50:24, :56:17
        opacReg <= 16'h0;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:40:33, :50:24
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:47];	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
    initial begin	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
        for (logic [5:0] i = 6'h0; i < 6'h30; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
        end	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
        state = _RANDOM[6'h0][2:0];	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7, :38:22
        bandIdx = _RANDOM[6'h25][22:19];	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7, :41:25
        opacReg = {_RANDOM[6'h2E][31:23], _RANDOM[6'h2F][6:0]};	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7, :50:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_done = state == 3'h5;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7, :38:22, :52:26
  assign io_opacityOut = opacReg;	// src/main/scala/scarf/ggu/SHOPGenerator.scala:22:7, :50:24
endmodule
