// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module UnprojUnit(	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
  input         clock,	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
                reset,	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
  input  [9:0]  io_pixelX,	// src/main/scala/scarf/ggu/PositionCalc.scala:19:14
                io_pixelY,	// src/main/scala/scarf/ggu/PositionCalc.scala:19:14
  input  [15:0] io_depth,	// src/main/scala/scarf/ggu/PositionCalc.scala:19:14
  input  [31:0] io_cx,	// src/main/scala/scarf/ggu/PositionCalc.scala:19:14
                io_cy,	// src/main/scala/scarf/ggu/PositionCalc.scala:19:14
  input         io_start,	// src/main/scala/scarf/ggu/PositionCalc.scala:19:14
  output        io_done,	// src/main/scala/scarf/ggu/PositionCalc.scala:19:14
  output [31:0] io_camX,	// src/main/scala/scarf/ggu/PositionCalc.scala:19:14
                io_camY,	// src/main/scala/scarf/ggu/PositionCalc.scala:19:14
                io_camZ	// src/main/scala/scarf/ggu/PositionCalc.scala:19:14
);

  reg  [1:0]  state;	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22
  reg  [31:0] rayX;	// src/main/scala/scarf/ggu/PositionCalc.scala:38:21
  reg  [31:0] rayY;	// src/main/scala/scarf/ggu/PositionCalc.scala:39:21
  reg  [31:0] rayZ;	// src/main/scala/scarf/ggu/PositionCalc.scala:40:21
  reg  [31:0] camXR;	// src/main/scala/scarf/ggu/PositionCalc.scala:41:22
  reg  [31:0] camYR;	// src/main/scala/scarf/ggu/PositionCalc.scala:42:22
  reg  [31:0] camZR;	// src/main/scala/scarf/ggu/PositionCalc.scala:43:22
  reg  [1:0]  casez_tmp;	// src/main/scala/scarf/ggu/PositionCalc.scala:50:17, :52:22
  always_comb begin	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :50:17, :52:22, :59:13, :66:13, :69:13
    casez (state)	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :50:17, :52:22, :59:13, :66:13, :69:13
      2'b00:
        casez_tmp = io_start ? 2'h1 : state;	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :50:17, :52:{22,30}, :59:13, :66:13, :69:13
      2'b01:
        casez_tmp = 2'h2;	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :50:17, :52:22, :59:13, :66:13, :69:13
      2'b10:
        casez_tmp = 2'h3;	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :45:20, :50:17, :52:22, :59:13, :66:13, :69:13
      default:
        casez_tmp = 2'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :50:17, :52:22, :59:13, :66:13, :69:13
    endcase	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :50:17, :52:22, :59:13, :66:13, :69:13
  end // always_comb
  wire [31:0] _GEN = {16'h0, io_depth};	// src/main/scala/scarf/ggu/PositionCalc.scala:63:22
  wire        _GEN_0 = state == 2'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :50:17
  wire        _GEN_1 = state == 2'h1;	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :50:17, :52:30
  always @(posedge clock) begin	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
    if (reset) begin	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
      state <= 2'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22
      rayX <= 32'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:38:21
      rayY <= 32'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:38:21, :39:21
      rayZ <= 32'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:38:21, :40:21
      camXR <= 32'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:38:21, :41:22
      camYR <= 32'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:38:21, :42:22
      camZR <= 32'h0;	// src/main/scala/scarf/ggu/PositionCalc.scala:38:21, :43:22
    end
    else begin	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
      state <= casez_tmp;	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :50:17, :52:22
      if (_GEN_0 | ~_GEN_1) begin	// src/main/scala/scarf/ggu/PositionCalc.scala:38:21, :40:21, :50:17
      end
      else begin	// src/main/scala/scarf/ggu/PositionCalc.scala:40:21, :50:17
        rayX <= {22'h0, io_pixelX} - io_cx;	// src/main/scala/scarf/ggu/PositionCalc.scala:38:21, :56:{28,51}
        rayY <= {22'h0, io_pixelY} - io_cy;	// src/main/scala/scarf/ggu/PositionCalc.scala:39:21, :56:{28,51}, :57:{28,51}
        rayZ <= 32'h8000;	// src/main/scala/scarf/ggu/PositionCalc.scala:40:21, :58:12
      end
      if (_GEN_0 | _GEN_1 | state != 2'h2) begin	// src/main/scala/scarf/ggu/PositionCalc.scala:36:22, :41:22, :43:22, :50:17, :59:13
      end
      else begin	// src/main/scala/scarf/ggu/PositionCalc.scala:43:22, :50:17
        camXR <= rayX * _GEN;	// src/main/scala/scarf/ggu/PositionCalc.scala:38:21, :41:22, :63:22
        camYR <= rayY * _GEN;	// src/main/scala/scarf/ggu/PositionCalc.scala:39:21, :42:22, :63:22, :64:22
        camZR <= rayZ * _GEN;	// src/main/scala/scarf/ggu/PositionCalc.scala:40:21, :43:22, :63:22, :65:22
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:6];	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
    initial begin	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
        end	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
        state = _RANDOM[3'h0][1:0];	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :36:22
        rayX = {_RANDOM[3'h0][31:2], _RANDOM[3'h1][1:0]};	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :36:22, :38:21
        rayY = {_RANDOM[3'h1][31:2], _RANDOM[3'h2][1:0]};	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :38:21, :39:21
        rayZ = {_RANDOM[3'h2][31:2], _RANDOM[3'h3][1:0]};	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :39:21, :40:21
        camXR = {_RANDOM[3'h3][31:2], _RANDOM[3'h4][1:0]};	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :40:21, :41:22
        camYR = {_RANDOM[3'h4][31:2], _RANDOM[3'h5][1:0]};	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :41:22, :42:22
        camZR = {_RANDOM[3'h5][31:2], _RANDOM[3'h6][1:0]};	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :42:22, :43:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_done = &state;	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :36:22, :45:20
  assign io_camX = camXR;	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :41:22
  assign io_camY = camYR;	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :42:22
  assign io_camZ = camZR;	// src/main/scala/scarf/ggu/PositionCalc.scala:18:7, :43:22
endmodule
