// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module VectorALU(	// src/main/scala/scarf/compute/VectorALU.scala:32:7
  input         clock,	// src/main/scala/scarf/compute/VectorALU.scala:32:7
                reset,	// src/main/scala/scarf/compute/VectorALU.scala:32:7
  input  [15:0] io_a_0,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
                io_b_0,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
  input         io_enable,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
  output [15:0] io_result_0,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
  output        io_valid,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
  input         io_smStart,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
  input  [15:0] io_smLogitIn,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
                io_smCandidateIn,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
  input         io_smInValid,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
  input  [7:0]  io_smNumElements,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
  output [31:0] io_smDepthOut,	// src/main/scala/scarf/compute/VectorALU.scala:36:14
  output        io_smOutValid	// src/main/scala/scarf/compute/VectorALU.scala:36:14
);

  reg  [15:0] REG_0;	// src/main/scala/scarf/compute/VectorALU.scala:106:23
  reg         io_valid_REG;	// src/main/scala/scarf/compute/VectorALU.scala:108:23
  reg  [1:0]  smState;	// src/main/scala/scarf/compute/VectorALU.scala:111:26
  reg  [31:0] expSum;	// src/main/scala/scarf/compute/VectorALU.scala:112:26
  reg  [31:0] depthAcc;	// src/main/scala/scarf/compute/VectorALU.scala:113:26
  reg  [7:0]  smCount;	// src/main/scala/scarf/compute/VectorALU.scala:114:26
  wire        _GEN = smState == 2'h0;	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :123:19, :157:15
  wire        _GEN_0 = smState == 2'h1;	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :123:19, :126:18
  wire        _GEN_1 = smCount == io_smNumElements - 8'h1 & io_smInValid;	// src/main/scala/scarf/compute/VectorALU.scala:114:26, :137:{20,41,47}
  wire        _GEN_2 = smState == 2'h2;	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :123:19, :138:17
  reg  [1:0]  casez_tmp;	// src/main/scala/scarf/compute/VectorALU.scala:123:19, :125:24
  always_comb begin	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :123:19, :125:24, :137:64, :151:64, :157:15
    casez (smState)	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :123:19, :125:24, :137:64, :151:64, :157:15
      2'b00:
        casez_tmp = io_smStart ? 2'h1 : smState;	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :123:19, :125:24, :126:18, :137:64, :151:64, :157:15
      2'b01:
        casez_tmp = _GEN_1 ? 2'h2 : smState;	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :123:19, :125:24, :137:{47,64}, :138:17, :151:64, :157:15
      2'b10:
        casez_tmp = _GEN_1 ? 2'h3 : smState;	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :121:28, :123:19, :125:24, :137:{47,64}, :151:64, :152:17, :157:15
      default:
        casez_tmp = 2'h0;	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :123:19, :125:24, :137:64, :151:64, :157:15
    endcase	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :123:19, :125:24, :137:64, :151:64, :157:15
  end // always_comb
  wire [15:0] _expVal_T = io_smLogitIn + 16'h4000;	// src/main/scala/scarf/compute/VectorALU.scala:116:29
  wire        _GEN_3 = _GEN_2 & io_smInValid;	// src/main/scala/scarf/compute/VectorALU.scala:113:26, :123:19, :143:26, :146:18
  always @(posedge clock) begin	// src/main/scala/scarf/compute/VectorALU.scala:32:7
    REG_0 <= io_a_0 + io_b_0;	// src/main/scala/scarf/compute/VectorALU.scala:70:34, :106:23
    io_valid_REG <= io_enable;	// src/main/scala/scarf/compute/VectorALU.scala:108:23
    if (reset) begin	// src/main/scala/scarf/compute/VectorALU.scala:32:7
      smState <= 2'h0;	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :157:15
      expSum <= 32'h0;	// src/main/scala/scarf/compute/VectorALU.scala:112:26
      depthAcc <= 32'h0;	// src/main/scala/scarf/compute/VectorALU.scala:112:26, :113:26
      smCount <= 8'h0;	// src/main/scala/scarf/compute/VectorALU.scala:114:26
    end
    else begin	// src/main/scala/scarf/compute/VectorALU.scala:32:7
      smState <= casez_tmp;	// src/main/scala/scarf/compute/VectorALU.scala:111:26, :123:19, :125:24
      if (_GEN) begin	// src/main/scala/scarf/compute/VectorALU.scala:123:19
        if (io_smStart) begin	// src/main/scala/scarf/compute/VectorALU.scala:36:14
          expSum <= 32'h0;	// src/main/scala/scarf/compute/VectorALU.scala:112:26
          depthAcc <= 32'h0;	// src/main/scala/scarf/compute/VectorALU.scala:112:26, :113:26
          smCount <= 8'h0;	// src/main/scala/scarf/compute/VectorALU.scala:114:26
        end
      end
      else begin	// src/main/scala/scarf/compute/VectorALU.scala:123:19
        if (_GEN_0 & io_smInValid)	// src/main/scala/scarf/compute/VectorALU.scala:112:26, :123:19, :133:26, :134:17
          expSum <= expSum + {16'h0, _expVal_T};	// src/main/scala/scarf/compute/VectorALU.scala:112:26, :116:29, :134:27, :144:28
        if (_GEN_0 | ~_GEN_3) begin	// src/main/scala/scarf/compute/VectorALU.scala:113:26, :123:19, :143:26, :146:18
        end
        else	// src/main/scala/scarf/compute/VectorALU.scala:113:26, :123:19
          depthAcc <=
            depthAcc + {_expVal_T, 16'h0} / (expSum + 32'h1) * {16'h0, io_smCandidateIn};	// src/main/scala/scarf/compute/VectorALU.scala:112:26, :113:26, :116:29, :144:{28,35,45}, :145:33, :146:30
        if (_GEN_0) begin	// src/main/scala/scarf/compute/VectorALU.scala:123:19
          if (_GEN_1)	// src/main/scala/scarf/compute/VectorALU.scala:137:47
            smCount <= 8'h0;	// src/main/scala/scarf/compute/VectorALU.scala:114:26
          else if (io_smInValid)	// src/main/scala/scarf/compute/VectorALU.scala:36:14
            smCount <= smCount + 8'h1;	// src/main/scala/scarf/compute/VectorALU.scala:114:26, :135:28
        end
        else if (_GEN_3)	// src/main/scala/scarf/compute/VectorALU.scala:113:26, :123:19, :143:26, :146:18
          smCount <= smCount + 8'h1;	// src/main/scala/scarf/compute/VectorALU.scala:114:26, :135:28, :149:28
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/scarf/compute/VectorALU.scala:32:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/compute/VectorALU.scala:32:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/scarf/compute/VectorALU.scala:32:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:35];	// src/main/scala/scarf/compute/VectorALU.scala:32:7
    initial begin	// src/main/scala/scarf/compute/VectorALU.scala:32:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/scarf/compute/VectorALU.scala:32:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/scarf/compute/VectorALU.scala:32:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/scarf/compute/VectorALU.scala:32:7
        for (logic [5:0] i = 6'h0; i < 6'h24; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/scarf/compute/VectorALU.scala:32:7
        end	// src/main/scala/scarf/compute/VectorALU.scala:32:7
        REG_0 = _RANDOM[6'h0][15:0];	// src/main/scala/scarf/compute/VectorALU.scala:32:7, :106:23
        io_valid_REG = _RANDOM[6'h21][0];	// src/main/scala/scarf/compute/VectorALU.scala:32:7, :108:23
        smState = _RANDOM[6'h21][2:1];	// src/main/scala/scarf/compute/VectorALU.scala:32:7, :108:23, :111:26
        expSum = {_RANDOM[6'h21][31:3], _RANDOM[6'h22][2:0]};	// src/main/scala/scarf/compute/VectorALU.scala:32:7, :108:23, :112:26
        depthAcc = {_RANDOM[6'h22][31:3], _RANDOM[6'h23][2:0]};	// src/main/scala/scarf/compute/VectorALU.scala:32:7, :112:26, :113:26
        smCount = _RANDOM[6'h23][10:3];	// src/main/scala/scarf/compute/VectorALU.scala:32:7, :113:26, :114:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/compute/VectorALU.scala:32:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/scarf/compute/VectorALU.scala:32:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_result_0 = REG_0;	// src/main/scala/scarf/compute/VectorALU.scala:32:7, :106:23
  assign io_valid = io_valid_REG;	// src/main/scala/scarf/compute/VectorALU.scala:32:7, :108:23
  assign io_smDepthOut = depthAcc;	// src/main/scala/scarf/compute/VectorALU.scala:32:7, :113:26
  assign io_smOutValid = ~(_GEN | _GEN_0) & (_GEN_2 ? io_smInValid : (&smState));	// src/main/scala/scarf/compute/VectorALU.scala:32:7, :111:26, :120:17, :123:19, :143:26
endmodule
