#!/usr/bin/env python3
"""Export the seed-42 FP16 LSH projection as a Chisel ROM."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from fsdr.lsh_hasher import LSHHasher
from fsdr.types import FSDRConfig


def export(scala_output: Path, manifest_output: Path) -> dict:
    config = FSDRConfig(feature_dim=128, lsh_dim=16, seed=42)
    projection = LSHHasher(config).get_projection_matrix().cpu().numpy()
    bits = projection.view(np.uint16)
    digest = hashlib.sha256(bits.astype("<u2", copy=False).tobytes()).hexdigest()
    rows = []
    for row in bits:
        values = ", ".join(f"0x{int(value):04x}" for value in row)
        rows.append(f"    Seq({values})")
    scala = "\n".join(
        (
            "package scarf.fsdr",
            "",
            "/** Generated by hardware/rtl/export_lsh_projection.py. */",
            "object LSHProjectionROM {",
            "  val Seed: Int = 42",
            "  val Rows: Int = 16",
            "  val Columns: Int = 128",
            f'  val Sha256: String = "{digest}"',
            "  val fp16Bits: Seq[Seq[Int]] = Seq(",
            ",\n".join(rows),
            "  )",
            "}",
            "",
        )
    )
    scala_output.parent.mkdir(parents=True, exist_ok=True)
    scala_output.write_text(scala, encoding="ascii")
    try:
        scala_source = scala_output.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        scala_source = scala_output.name
    manifest = {
        "schema_version": "1.0",
        "kind": "lsh_projection_rom",
        "seed": 42,
        "rows": 16,
        "columns": 128,
        "operand_storage": "IEEE-754 binary16",
        "mac_decode": "exact signed Q1.24 for normalized FP16 operands",
        "matrix_bytes": "row-major little-endian uint16",
        "sha256": digest,
        "scala_source": scala_source,
    }
    manifest_output.parent.mkdir(parents=True, exist_ok=True)
    manifest_output.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--scala-output",
        type=Path,
        default=ROOT / "chisel/src/main/scala/scarf/fsdr/LSHProjectionROM.scala",
    )
    parser.add_argument(
        "--manifest-output",
        type=Path,
        default=ROOT / "artifact/lsh_projection.json",
    )
    args = parser.parse_args()
    record = export(args.scala_output.resolve(), args.manifest_output.resolve())
    print(record["sha256"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
