#!/usr/bin/env python3
"""Create a non-claim format template for real SCARF evidence exports.

The command writes instructions, field-complete JSON templates, empty raw-file
placeholders, and deterministic interface fixtures. It never creates
measurements, calibration candidates, model results, or claim-status records.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


MODELS = ("transplat", "mvsplat", "depthsplat")
DATASETS = ("re10k", "acid", "dl3dv")
HEX40 = "<fill-40-hex-git-commit>"
HEX64 = "<fill-64-hex-sha256>"


README = """# SCARF claim evidence input

This directory is an input staging area, not generated evidence.  Populate it
with files copied from the actual calibration run, RTL/gate-level simulator,
CUDA/Orin measurement, and model evaluations.  Do not hand-edit numbers into
result records.

Required deliverables:

1. `calibration/manifest.json`, `calibration/candidates.json`, and the raw
   `calibration/traces/calibration_train/` and
   `calibration/traces/calibration_holdout/` records.  The resulting release
   config must be generated by `scripts/calibrate_mechanisms.py`; retain its
   two identical outputs as `calibration/mechanism_config.json` and
   `calibration/calibration-result.json`, and install the former at
   `artifact/mechanism_config.json` with `status: calibrated`.
2. `timing-backend/manifest.json`, the emitted source RTL, and one raw trace
   for every sample in the selected full/reviewer profile.  Use
   `python scripts/claim_timing_backend.py timing-backend/manifest.json`.
3. `quality/<model>_<dataset>/results.json`,
   `mechanisms/<model>_<dataset>/results.json`, and
   `speedup/<model>_<dataset>/results.json`, including sample lineage and raw
   Orin records where required.
4. `environments/classic.json`, `environments/depthsplat.json`, and
   `environments/orin.json`, each emitted by `scripts/check_environment.py`.
   The environment digest in every result must match its corresponding file.

The files generated here are field-complete templates only. Replace every
`null`, `<fill-...>`, empty sample list, empty raw log, and empty binary with
output from the commands above. Do not hand-edit values to make a validator
pass, and keep this directory outside the release tree.

`sample_00000` is the exemplar for every selected sample. Expand it to the
protocol counts (full: 6474/1595/140 for re10k/acid/dl3dv; reviewer:
512/512/140) while preserving zero-padded five-digit names.

Environment captures are generated with:

```bash
python scripts/check_environment.py --profile classic --output environments/classic.json
python scripts/check_environment.py --profile depthsplat --output environments/depthsplat.json
python scripts/check_environment.py --profile orin --output environments/orin.json
```

Run the audit before staging an archive:

```bash
python scripts/claim_readiness.py --root . --output-root outputs/ae --profile full
python scripts/validate_ae.py --input outputs/ae --require-key-results
python scripts/stage_reference_results.py --input outputs/ae
```

Once the platform replaces every template with real exports, import and check
the complete tree with `scripts/import_claim_evidence.py`. The importer is the
single gate before installing `artifact/mechanism_config.json` and staging
reference evidence.

Anything marked `pending_validation`, `synthetic_fixture`, `diagnostic`, or
`claim_eligible: false` is rejected by the formal claim path.

`FILE_MANIFEST.json` is the machine-readable inventory of every required file
class and the exact full/reviewer sample counts. It intentionally describes
sample paths as patterns; a target run must materialize one file per index.
"""


FORMAT_SPEC = """# SCARF claim evidence format

This directory is a format-only template. It contains no measurements, model
outputs, calibration candidates, timing traces, or Orin observations. Replace
every null and angle-bracket placeholder with records produced by the release
commands. Do not make a copy of this template part of a release.

The nine pair keys are the Cartesian product of models
`transplat`, `mvsplat`, `depthsplat` and datasets `re10k`, `acid`, `dl3dv`.
`sample_00000` is an exemplar: expand the same file shape through the selected
protocol count (full profile: re10k 6474, acid 1595, dl3dv 140; reviewer
profile: re10k 512, acid 512, dl3dv 140).

Required file classes:

calibration/manifest.json is the prepared DL3DV protocol. It must be the
dl3dv_calibration_protocol record from data/prepare_dl3dv_calibration_inputs.py,
with 24 calibration_train scenes and 8 disjoint calibration_holdout scenes.
The raw records below `calibration/traces/` follow the exact
`calibration_sample_trace` shape emitted by `scripts/demo.py --calibration-trace`.
`calibration/plan.json` records the sweep plan, while
`calibration/train-candidates.json` is the train-only split record. These are
kept beside the final `calibration/candidates.json` because they are needed to
reopen the calibration provenance.

calibration/candidates.json is the split-aware output of
scripts/calibration_sweep.py; it must contain the registered train candidates,
one committed train selection, and one exact holdout candidate. The final
artifact/mechanism_config.json is generated by scripts/calibrate_mechanisms.py,
not hand-edited. Keep byte-for-byte copies at
calibration/mechanism_config.json and calibration/calibration-result.json so
the calibration output and installed release config can be audited together.

timing-backend/manifest.json must use source-bound-timing-backend-v1. Its source
path is relative to the manifest directory (the manifest normally lives below
`outputs/timing-backend/`), and samples must contain one entry for every
model/dataset/sample index in the selected profile. Each entry has a normalized
trace path, a SHA256, all four timing variants, and positive S1-S4 stage cycles.
The raw trace naming pattern is:
timing-backend/timing-trace/<model>/<dataset>/sample_<index:05d>.json.
For this external template, a schema-only path check (which is expected to
fail on null hashes/cycles) is invoked with
`--root <template>/timing-backend`; a real release uses the checked-out
release root as the loader root.

For each of the nine pairs, quality, mechanisms, and speedup contain
samples/sample_<index:05d>/results.json plus the pair-level results.json. The
pair-level file is the schema_version 2.1 dataset aggregate emitted by
scripts/aggregate_results.py. Its provenance binds source, submodules,
environment, checkpoint, dataset tree, calibration config, selection, and the
execution trace set. Both sample and aggregate records carry the
`execution-trace-inputs-v2`/`execution-trace-set-v2` bindings; these hashes are
computed by the runner and must never be guessed. speedup additionally
contains the Orin raw measurement files listed below.

`pair-execution.json`, `progress.jsonl`, and `timing-trace/aggregate.json` are
retained for each pair as part of the execution lineage. A claim runner also
stages a complete `timing-backend/` copy below each sample directory.

For every speedup sample, create:

speedup/<pair>/samples/sample_<index:05d>/orin-evidence/measurement.json
speedup/<pair>/samples/sample_<index:05d>/orin-evidence/cuda-events.json
speedup/<pair>/orin-profile/tegrastats.log
speedup/<pair>/orin-profile/nsight.nsys-rep
speedup/<pair>/orin-profile/pair-measurement.json

The measurement JSON is an orin_nx_measurement record with five raw CUDA event
values, their median, the Orin environment contract, selection hashes, thermal
evidence, and hashes for the inference result, tegrastats, Nsight, and
CUDA-event files. The pair aggregate binds every measurement path and hash.

validation.json is written only by
python scripts/validate_ae.py --input outputs/ae --require-key-results. Do not
create a passing validation file by hand. All files in this directory remain
non-claim until replaced with real exports and validated.

`FILE_MANIFEST.json` is the machine-readable inventory of every required file
class and profile count. `sample_00000` files are schema exemplars; expand each
pattern to every selected sample index before running validation.

`FIELD_REFERENCE.md` explains the field-level meaning and provenance of each
record family. It is a companion to the JSON templates, not a claim artifact.
"""


FIELD_REFERENCE = """# SCARF evidence field reference

This is a format guide for the external input template. It does not contain
experimental values. Every digest must be computed from the exact file named by
its adjacent `path` field; never replace a digest with a guessed value.

## Placeholder rules

- `null` means the runner must fill a runtime or measured value.
- `<fill-40-hex-git-commit>` means a lower-case 40-character Git commit.
- `<fill-64-hex-sha256>` means a lower-case SHA256 of the referenced bytes.
- Empty arrays are deliberately incomplete and must be expanded by the run.
- `pending_validation`, `format_only`, `claim_eligible: false`, and
  `synthetic_fixture` are template markers. They must not occur in a claim
  result or in `artifact/reference_results`.

## Calibration

`calibration/manifest.json` is the `dl3dv_calibration_protocol` emitted by
`data/prepare_dl3dv_calibration_inputs.py`. Its two split records must name 24
`calibration_train` and 8 disjoint `calibration_holdout` scenes. Each
representation (`native`, `re10k`) records its prepared input root, index file,
tree/manifest/provenance hashes, selection hash, and sample count. `target_rgb_included`
must remain false for target-free calibration.

`calibration/traces/<split>/<model>_dl3dv/samples/sample_<index>/results.json`
is a `calibration_sample_trace` from `scripts/demo.py --calibration-trace`.
The outer identity is `model`, `dataset`, `sample_index`, `execution_index`,
`scene`, context/target indices, and `seed`. `trace` binds one neural forward,
feature/depth/Gaussian/camera tensor shapes and hashes, candidate scope, and
calibration input hashes. `candidates` contains the complete registered
parameter tuple (`gamma_depth`, `beta_x`, `beta_f`, `beta_d`), quality losses,
fidelity metrics, work/compression reductions, FSDR/SAES event counts, and the
candidate hash. Train uses the global grid; holdout uses only the selected train
tuple.

`calibration/candidates.json` is the split-aware aggregate consumed by
`scripts/calibrate_mechanisms.py`. It binds the calibration manifest, train and
holdout scene/selection/pair/trace/candidate hashes, the selected train
candidate, and the validated holdout candidate. `plan.json`,
`train-candidates.json`, `train-selection.json`, and `holdout-request.json`
preserve the sweep and split decisions needed to audit that aggregate.

`calibration/mechanism_config.json` and `calibration/calibration-result.json`
have the exact shape emitted by `scripts/calibrate_mechanisms.py`. The final
installed copy is `artifact/mechanism_config.json`. It contains the schema
version, `status`, one global `selected` tuple, fixed paper parameters, the
seed-42 LSH ROM binding, the immutable SAES execution identity, the registered
search grid, and `calibration` provenance. A claim-ready file has
`status: calibrated`, `evaluation_disjoint: true`, complete train/holdout
hashes, and a holdout tuple hash equal to the selected tuple.

## Timing backend

`timing-backend/manifest.json` has exactly `schema_version`, `backend`,
`clock_mhz`, and `samples`. `backend.source` identifies the source RTL path
and its SHA256. Each sample entry identifies a model/dataset/index, points to
one raw trace below `timing-backend/timing-trace/`, and contains all four
variants (`asic`, `asic_fsdr`, `asic_saes`, `asic_fsdr_saes`) plus positive
combined `s1`-`s4` cycle counts. The manifest must contain the exact protocol
sample set for the selected profile.

Each raw timing trace has `schema_version: source-bound-timing-trace-v2`, the
model/dataset/index, `cycle_accurate: true`, source RTL SHA256, clock, and one
event for each stage with start/end cycles and acceptance state. The loader
recomputes every trace hash and rejects diagnostic or synthetic traces.

## Workflow results

Every one of the nine `<model>_<dataset>` directories under `quality`,
`mechanisms`, and `speedup` has a sample result and a dataset aggregate. Both
use result schema `2.1`. `provenance` binds source commit/tree, submodules,
command, runtime assets, environment digest, checkpoint/load coverage, dataset
tree/representation, deterministic selection, the frozen mechanism config,
calibration split provenance, and SAES route identity. `quality` contains
baseline/SCARF PSNR/SSIM/LPIPS and per-target-view records. `performance`
contains baseline/SCARF cycles, speedup, component/stage cycles, claim timing,
and the source-bound trace. `events` contains the FSDR and SAES accounting
ledger; `ablation` contains all four timing variants and quality deltas;
`fsdr_saes` records the combined mechanism metrics. `validation` records
reproducibility and must be true/false only in real output.

Sample records carry `execution-trace-inputs-v2` and one trace SHA256. Aggregate
records carry `execution-trace-set-v2`, the sorted sample selection, all sample
evidence paths/hashes, and the aggregate timing trace hash. The claim runner
also stages `timing-trace/<model>/<dataset>/<sample>.json` and a complete
`timing-backend/` bundle below every sample directory.

`pair-execution.json` is the exact `run_pair.py` completion record: `kind`,
sample/executed/resumed/complete counts, and the `source_index` summary
(`source_entry_count`, `null_entry_count`, `sample_count`, source-index SHA256,
and sample-selection SHA256). `progress.jsonl` contains one timestamped JSON
object per pair/sample event; its event shapes are listed in
`progress-event-examples.json`.

## Orin evidence

For every speedup sample, `orin-evidence/measurement.json` is an
`orin_nx_measurement` with the Orin contract and runtime identity, selection
hashes, five positive raw CUDA-event encoder times, their exact median, thermal
limits/samples, and hashes for inference result, CUDA event JSON, tegrastats,
and Nsight files. `cuda-events.json` repeats the five values and median.

The pair-level `orin-profile/pair-measurement.json` is an
`orin_nx_pair_measurement` with the frozen selection hash and one path/hash
entry for every sample measurement. `orin-profile/tegrastats.log` is the raw
text capture containing temperature samples; `orin-profile/nsight.nsys-rep`
is the raw Nsight Systems binary. The measurement loader verifies all hashes
and rejects missing, synthetic, or over-temperature captures.

## Environment and validation

`environments/classic.json`, `depthsplat.json`, and `orin.json` are emitted by
`scripts/check_environment.py`. They contain the profile contract, host
identity, complete runtime details, and UTC generation time. Result provenance
must use the digest computed from the matching environment record.

`validation.json` is written only by `scripts/validate_ae.py --require-key-results`.
It contains the validation profile, `require_key_results: true`, every check
object with actual/target/pass details, and a passed/total summary. A real
claim-ready file has `status: PASS`; this template intentionally does not.

## Expansion counts

Use five-digit zero-padded sample directories. For each model/dataset pair,
the full profile has 6474 Re10K, 1595 ACID, or 140 DL3DV samples; the reviewer
profile has 512, 512, or 140. The same index set must appear in the three
workflow result trees, timing manifest/traces, execution trace sets, and Orin
measurement list. Calibration remains 24 train plus 8 holdout samples per
model-specific DL3DV representation.
"""


def _write_json(path: Path, record: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _calibration_manifest_template() -> dict:
    def representation(split_name: str, name: str) -> dict:
        return {
            "calibration_input_root": f"inputs/{split_name}/{name}",
            "calibration_input_tree_sha256": None,
            "calibration_input_manifest_sha256": None,
            "calibration_input_provenance_sha256": None,
            "target_rgb_included": False,
            "index_file": f"{split_name}-{name}.json",
            "index_sha256": None,
            "selection_sha256": None,
            "sample_count": 24 if split_name == "calibration_train" else 8,
            "target_shape": [270, 480] if name == "native" else [360, 640],
        }

    def split(split_name: str) -> dict:
        return {
            "scene_count": 24 if split_name == "calibration_train" else 8,
            "scene_set_sha256": None,
            "representations": {
                "native": representation(split_name, "native"),
                "re10k": representation(split_name, "re10k"),
            },
        }

    return {
        "schema_version": "1.0",
        "kind": "dl3dv_calibration_protocol",
        "status": "pending_validation",
        "evaluation_disjoint": None,
        "source": {
            "dataset_tree_sha256": None,
            "dataset_manifest_sha256": None,
            "prepared_source_sha256": None,
        },
        "download_plan_sha256": None,
        "archive_preparation_sha256": None,
        "calibration_scene_count": 24,
        "holdout_scene_count": 8,
        "datasets": {
            "dl3dv": {
                "splits": {
                    "calibration_train": split("calibration_train"),
                    "calibration_holdout": split("calibration_holdout"),
                }
            }
        },
        "calibration_manifest_sha256": None,
    }


def _calibration_candidates_template() -> dict:
    return {
        "schema_version": "2.0",
        "kind": "split_calibration_candidate_records",
        "calibration_protocol": "dl3dv_train_holdout_v1",
        "evaluation_disjoint": None,
        "train_holdout_scene_disjoint": None,
        "calibration_manifest_sha256": None,
        "status": "pending_validation",
        "train_selection": None,
        "splits": {
            "calibration_train": _calibration_split_result_template(
                "calibration_train"
            ),
            "calibration_holdout": _calibration_split_result_template(
                "calibration_holdout"
            ),
        },
    }


def _timing_sample_template(model: str, dataset: str) -> dict:
    return {
        "model": model,
        "dataset": dataset,
        "sample_index": 0,
        "trace": {
            "path": f"timing-trace/{model}/{dataset}/sample_00000.json",
            "sha256": None,
        },
        "variants": {
            name: {"total_cycles": None}
            for name in ("asic", "asic_fsdr", "asic_saes", "asic_fsdr_saes")
        },
        "combined_stage_cycles": {
            stage: None for stage in ("s1", "s2", "s3", "s4")
        },
    }


def _timing_manifest_template() -> dict:
    return {
        "schema_version": "source-bound-timing-backend-v1",
        "backend": {
            "kind": "source_rtl",
            "source": {"path": "rtl/ScarfTop.sv", "sha256": None},
        },
        "clock_mhz": None,
        "samples": [
            _timing_sample_template(model, dataset)
            for model in MODELS
            for dataset in DATASETS
        ],
    }


def _timing_trace_template(model: str | None = None, dataset: str | None = None) -> dict:
    return {
        "schema_version": "source-bound-timing-trace-v2",
        "model": model,
        "dataset": dataset,
        "sample_index": 0 if model is not None and dataset is not None else None,
        "cycle_accurate": None,
        "source_rtl_sha256": None,
        "clock_mhz": None,
        "events": [
            {
                "stage": stage,
                "start_cycle": None,
                "end_cycle": None,
                "accepted": None,
            }
            for stage in ("s1", "s2", "s3", "s4")
        ],
    }


def _calibration_candidate_template() -> dict:
    """Return one candidate row shape emitted by calibration_replay."""
    return {
        "parameters": {
            "gamma_depth": None,
            "beta_x": None,
            "beta_f": None,
            "beta_d": None,
        },
        "quality": {
            "psnr_loss_db": None,
            "ssim_loss": None,
            "lpips_increase": None,
        },
        "fidelity": {
            "psnr_db": None,
            "ssim": None,
            "lpips": None,
            "psnr_floor_db": None,
        },
        "work_reduction": None,
        "compression": None,
        "events": {
            "fsdr": {
                "total_pixels": None,
                "cache_hits": None,
                "guided": None,
                "guided_in_window": None,
                "guided_top1_covered": None,
                "guided_top1_missed": None,
                "full_depth_evaluations": None,
                "executed_depth_evaluations": None,
                "depth_evaluations_available": None,
                "discrete_candidate_evidence": None,
                "guided_rate": None,
                "in_window_rate": None,
                "top1_coverage": None,
            },
            "saes": {
                "total_tiles_processed": None,
                "level0_tiles": None,
                "level1_tiles": None,
                "full_tiles": None,
                "effective_gaussians": None,
                "full_s2_evaluations": None,
                "executed_s2_evaluations": None,
                "s2_evaluations_available": None,
                "s2_s3_saving": {"s2": None, "s3": None},
            },
        },
        "candidate_sha256": None,
    }


def _mechanism_config_template() -> dict:
    """Return the complete shape emitted by calibrate_mechanisms.py.

    The selected tuple and all evidence digests stay empty on purpose.  The
    SAES route identity and registered grid are executable contracts, so they
    are included verbatim to prevent a platform run from inventing a second
    configuration shape.
    """
    from scripts.calibration_contract import PARAMETER_GRID
    from scripts.mechanism_config import FIXED
    from scripts.saes_execution_identity import build_saes_execution_identity

    empty_split = {
        "selection_sha256": HEX64,
        "scene_set_sha256": HEX64,
        "pair_bindings_sha256": HEX64,
        "trace_set_sha256": HEX64,
        "candidate_set_sha256": HEX64,
    }
    return {
        "schema_version": "1.0",
        "status": "pending_validation",
        "global_configuration": True,
        "projection": {
            "kind": "random_hyperplane_lsh",
            "seed": 42,
            "rom": "artifact/lsh_projection.json",
            "rom_sha256": HEX64,
        },
        "fixed": dict(FIXED),
        "saes_execution_identity": build_saes_execution_identity(),
        "search_space": {
            name: [float(value) for value in values]
            for name, values in PARAMETER_GRID.items()
        },
        "selected": {
            "gamma_depth": None,
            "beta_x": None,
            "beta_f": None,
            "beta_d": None,
        },
        "calibration": {
            "manifest_sha256": HEX64,
            "candidate_records_sha256": HEX64,
            "evaluation_disjoint": None,
            "protocol": "dl3dv_train_holdout_v1",
            "train_holdout_scene_disjoint": None,
            "train": {
                **empty_split,
                "selected_candidate_sha256": HEX64,
            },
            "holdout": {
                **empty_split,
                "validated_parameters_sha256": HEX64,
                "validated_candidate_sha256": HEX64,
            },
            "selection_rule": "quality constraints, maximum event work reduction",
        },
    }


def _calibration_trace_template(model: str, dataset: str, split: str) -> dict:
    """Return the exact outer shape written by demo.py --calibration-trace."""
    committed = split == "calibration_holdout"
    return {
        "schema_version": "1.0",
        "kind": "calibration_sample_trace",
        "sample_index": 0,
        "execution_index": 0,
        "scene": None,
        "context_indices": [],
        "target_indices": [],
        "model": model,
        "dataset": dataset,
        "seed": None,
        "trace": {
            "neural_forward_passes": None,
            "target_rgb_accessed": None,
            "feature_tensor": {"shape": [], "dtype": None, "sha256": None},
            "depth_tensor": {"shape": [], "dtype": None, "sha256": None},
            "gaussian_means": {"shape": [], "dtype": None, "sha256": None},
            "camera_geometry": {
                "extrinsics": {"shape": [], "dtype": None, "sha256": None},
                "intrinsics": {"shape": [], "dtype": None, "sha256": None},
                "ray_depth_mode": None,
            },
            "candidate_count": None,
            "candidate_scope": (
                "exact_committed_train_tuple"
                if committed
                else "registered_global_grid"
            ),
            "candidate_parameters_sha256": None,
            "calibration_input": {
                "tree_sha256": None,
                "manifest_sha256": None,
                "input_provenance_sha256": None,
                "selection_sha256": None,
                "index_sha256": None,
                "index_selection_sha256": None,
                "target_rgb_accessed": None,
                "target_rgb_included": None,
                "selected_scene_count": None,
            },
        },
        "calibration_scope": (
            "exact_committed_train_tuple"
            if committed
            else "registered_global_grid"
        ),
        "committed_parameters": (
            {
                "gamma_depth": None,
                "beta_x": None,
                "beta_f": None,
                "beta_d": None,
            }
            if committed
            else None
        ),
        "candidates": [_calibration_candidate_template()],
    }


def _environment_template(profile: str) -> dict:
    """Return the shape emitted by check_environment.py --output."""
    if profile in {"classic", "depthsplat"}:
        contract = {
            "python": "3.10",
            "torch": "2.1.2" if profile == "classic" else "2.4.0",
            "torchvision": "0.16.2" if profile == "classic" else "0.19.0",
            "cuda": "12.1",
        }
        details = {
            "python": None,
            "implementation": None,
            "torch": None,
            "torchvision": None,
            "torch_cuda": None,
            "nvcc": None,
            "c_compiler": None,
            "cuda_available": None,
            "lock_sha256": HEX64,
            "pip_freeze_sha256": HEX64,
            "pip_freeze": [],
        }
    else:
        contract = {
            "device": "Jetson Orin NX",
            "power_mode": "MAXN",
            "clocks": "recorded",
        }
        details = {
            "contract": {
                "schema_version": "1.0",
                "status": "runtime_autodetect",
                "device_model_contains": "Jetson Orin NX",
                "power_mode_contains": "MAXN",
                "require_jetson_clocks": True,
                "maximum_allowed_temperature_c": 80.0,
                "timing_repetitions": 5,
            },
            "contract_sha256": HEX64,
            "device_model": None,
            "jetpack": None,
            "l4t_release": None,
            "nvpmodel": None,
            "jetson_clocks": None,
            "nvcc": None,
            "python": None,
            "torch": None,
            "torch_cuda": None,
        }
    return {
        "schema_version": "1.0",
        "profile": profile,
        "contract": contract,
        "host": {"platform": None, "machine": None},
        "details": details,
        "generated_at": None,
    }


def _events_template() -> dict:
    """Return the complete v2.1 event ledger shape."""
    return {
        "fsdr": {
            "total_pixels": None,
            "cache_hits": None,
            "guided_pixels": None,
            "hamming_hits": None,
            "local_valid_hits": None,
            "local_invalid_fallbacks": None,
            "guided_top1_covered": None,
            "guided_top1_missed": None,
            "discrete_top1_available": None,
            "full_depth_evaluations": None,
            "executed_depth_evaluations": None,
            "depth_evaluations_available": None,
            "feature_buffer_bytes_baseline": None,
            "feature_buffer_bytes_actual": None,
            "feature_buffer_bytes_available": None,
            "source": None,
        },
        "saes": {
            "total_tiles": None,
            "level0_tiles": None,
            "level1_tiles": None,
            "full_tiles": None,
            "tile_path_available": None,
            "baseline_gaussians": None,
            "actual_gaussians": None,
            "gaussian_counts_available": None,
            "full_s2_evaluations": None,
            "executed_s2_evaluations": None,
            "s2_evaluations_available": None,
            "l0_representatives": None,
            "l1_lightweight_anchors": None,
            "full_stage3_gaussians": None,
            "assignment_weight_sum_error_max": None,
            "opacity_transmittance_error_max": None,
            "covariance_psd_violations": None,
            "hardware_accounting": None,
            "execution_dependency": None,
            "s2_s3_saving": {"s2": None, "s3": None},
            "source": None,
        },
    }


def _fsdr_saes_template() -> dict:
    return {
        "fsdr": {
            "guided_rate": None,
            "in_window_rate": None,
            "top1_coverage": None,
        },
        "saes": {
            "level0_ratio": None,
            "level1_ratio": None,
            "modification_ratio": None,
            "saes_execution_identity": None,
            "route_sha256": HEX64,
        },
        "preservation": {
            "saes_low_var_agree": None,
            "saes_low_var_tiles": None,
            "saes_early_tiles": None,
            "saes_low_var_mean_similarity": None,
            "saes_low_var_threshold": None,
        },
    }


def _ablation_template() -> dict:
    fields = {
        "depth_saving": None,
        "gauss_saving": None,
        "gauss_head_nn": None,
        "ggu_post": None,
        "saes_control": None,
        "hw_scale_compute": None,
        "hw_scale_memory": None,
        "quality": {
            "psnr": None,
            "ssim": None,
            "lpips": None,
            "loss_db": None,
            "loss_pct": None,
        },
        "total_cycles": None,
        "cycle_source": "source_bound_verified_timing_trace_v1",
    }
    return {name: dict(fields) for name in ("asic", "asic_fsdr", "asic_saes", "asic_fsdr_saes")}


def _execution_trace_performance_template(
    timing_path: str = "timing-trace/aggregate.json",
) -> dict:
    return {
        "cycle_source": "source_bound_verified_timing_trace_v1",
        "scarf_cycles": None,
        "components": {
            "feature": None,
            "depth": None,
            "gaussian": None,
            "ggu": None,
        },
        "stages": {
            stage: {
                "cycles": None,
                "useful_mmcu_slots": None,
                "scheduled_mmcu_slots": None,
                "mmcu_slots_available": None,
                "source": "source_bound_verified_timing_trace_v1",
            }
            for stage in ("s1", "s2", "s3", "s4")
        },
        "ablation": _ablation_template(),
        "events": _events_template(),
        "mechanism_metrics": _fsdr_saes_template(),
        "energy": {"available": False, "source": "not_measured"},
        "claim_timing": {
            "schema_version": "source-bound-claim-timing-v1",
            "timing_class": "rtl_cycle_equivalent_source_bound",
            "rtl_cycle_equivalent": True,
            "clock_mhz": None,
            "trace": {"path": timing_path, "sha256": HEX64},
            "input_binding_sha256": HEX64,
            "variants": {
                name: {"total_cycles": None}
                for name in ("asic", "asic_fsdr", "asic_saes", "asic_fsdr_saes")
            },
            "combined_stage_cycles": {
                stage: None for stage in ("s1", "s2", "s3", "s4")
            },
        },
    }


def _execution_trace_inputs_template(
    model: str, dataset: str, *, sample: bool
) -> dict:
    return {
        "source": {
            "source_tree_sha256": HEX64,
            "submodules": {
                "transplat": HEX40,
                "mvsplat": HEX40,
                "depthsplat": HEX40,
            },
        },
        "mechanism_config_sha256": HEX64,
        "saes_execution_identity": None,
        "saes_execution_route_sha256": HEX64,
        "model": model,
        "dataset": {
            "name": dataset,
            "representation": None,
            "manifest_sha256": HEX64,
            "tree_sha256": HEX64,
        },
        "checkpoint": {
            "sha256": HEX64,
            "load": {
                "matched_tensors": None,
                "matched_checkpoint_numel_fraction": None,
            },
        },
        "execution": {
            "seed": None,
            "environment_digest_sha256": HEX64,
            "runtime_assets": {"<fill-asset-name>": {"sha256": HEX64}},
        },
        "selection": (
            {
                "sample_index": 0,
                "execution_index": 0,
                "scene": None,
                "context_indices": [],
                "target_indices": [],
            }
            if sample
            else {
                "sample_count": None,
                "sample_indices": [],
                "execution_indices": [],
                "sample_selection_sha256": HEX64,
            }
        ),
        "route_evidence": _execution_trace_performance_template(
            "timing-trace/{}/{}/sample_00000.json".format(model, dataset)
            if sample
            else "timing-trace/aggregate.json"
        ),
    }


def _aggregate_template(
    model: str,
    dataset: str,
    *,
    include_orin: bool,
    sample: bool = False,
) -> dict:
    provenance = {
        "git_commit": HEX40,
        "git_dirty": None,
        "source_identity": "git",
        "source_tree_sha256": HEX64,
        "submodules": {
            "transplat": HEX40,
            "mvsplat": HEX40,
            "depthsplat": HEX40,
        },
        "model": model,
        "command": ["<fill-python>", "scripts/demo.py"],
        "runtime_assets": {"<fill-asset-name>": {"sha256": HEX64}},
        "device": {
            "type": None,
            "name": None,
            "measured_encoder_time_ms": None,
            "encoder_timing_samples_ms": [],
            "encoder_timing_repetitions": 5,
            "encoder_timing_source": None,
            "reported_clock_mhz": None,
            "scarf_clock_mhz": None,
        },
        "dataset": {
            "name": dataset,
            "representation": None,
            "manifest": None,
            "sha256": HEX64,
            "tree_sha256": HEX64,
            "functional_fixture": False,
            "paper_result_eligible": None,
        },
        "checkpoint": {
            "path": None,
            "sha256": HEX64,
            "load": {
                "matched_tensors": None,
                "matched_checkpoint_numel_fraction": None,
            },
        },
        "environment": {"profile": None, "digest_sha256": HEX64},
        "seed": None,
        "mechanism_config_sha256": HEX64,
        "calibration_provenance": {
            "status": "pending_validation",
            "evaluation_disjoint": None,
            "train_holdout_scene_disjoint": None,
            "protocol": "dl3dv_train_holdout_v1",
            "manifest_sha256": HEX64,
            "candidate_records_sha256": HEX64,
            "expected_results_accessed": None,
            "global_configuration": None,
            "train": {
                "selection_sha256": HEX64,
                "scene_set_sha256": HEX64,
                "pair_bindings_sha256": HEX64,
                "trace_set_sha256": HEX64,
                "candidate_set_sha256": HEX64,
                "selected_candidate_sha256": HEX64,
            },
            "holdout": {
                "selection_sha256": HEX64,
                "scene_set_sha256": HEX64,
                "pair_bindings_sha256": HEX64,
                "trace_set_sha256": HEX64,
                "candidate_set_sha256": HEX64,
                "validated_parameters_sha256": HEX64,
                "validated_candidate_sha256": HEX64,
            },
        },
        "saes_execution_identity": None,
        "saes_execution_route_sha256": HEX64,
        "execution_contract": {
            "run_class": "claim",
            "saes_materialization": "representative",
        },
        "evaluation": {
            "kind": "sample" if sample else "dataset_aggregate",
            "sample_count": None if not sample else None,
            "sample_indices": [] if not sample else None,
            "execution_indices": [] if not sample else None,
            "sample_selection": [] if not sample else None,
            "sample_selection_sha256": HEX64,
            "sample_results": [] if not sample else None,
            "aggregation": "arithmetic mean over deterministic sample indices",
        },
        "timing_backend": {
            "schema_version": "source-bound-timing-backend-v1",
            "kind": "source_rtl",
            "source": {"path": "timing-backend/<source>.sv", "sha256": HEX64},
            "manifest": {"path": "timing-backend/manifest.json", "sha256": HEX64},
        },
    }
    if sample:
        provenance["evaluation"].update(
            {
                "sample_index": 0,
                "execution_index": 0,
                "candidate_count": None,
                "scene": None,
                "context_indices": [],
                "target_indices": [],
                "target_view_count": None,
                "target_view_aggregation": "arithmetic mean over selected target views",
            }
        )
        provenance["evaluation"].pop("sample_count", None)
        provenance["evaluation"].pop("sample_indices", None)
        provenance["evaluation"].pop("execution_indices", None)
        provenance["evaluation"].pop("sample_selection", None)
        provenance["evaluation"].pop("sample_selection_sha256", None)
        provenance["evaluation"].pop("sample_results", None)
        provenance["evaluation"].pop("aggregation", None)
    timing_path = (
        f"timing-trace/{model}/{dataset}/sample_00000.json"
        if sample
        else "timing-trace/aggregate.json"
    )
    provenance["timing_backend"]["source"]["path"] = "timing-backend/rtl/ScarfTop.sv"
    provenance["timing_backend"]["manifest"]["path"] = "timing-backend/manifest.json"
    if sample:
        provenance["execution_trace"] = {
            "schema_version": "execution-trace-inputs-v2",
            "inputs": _execution_trace_inputs_template(model, dataset, sample=True),
        }
        provenance["execution_trace_sha256"] = HEX64
    record = {
        "schema_version": "2.1",
        "evidence_class": "deterministic_execution",
        "provenance": provenance,
        "quality": {
            "baseline": {"psnr_db": None, "ssim": None, "lpips": None},
            "scarf": {"psnr_db": None, "ssim": None, "lpips": None},
            "change": {
                "psnr_signed_pct": None,
                "psnr_degradation_pct": None,
                "psnr_absolute_pct": None,
            },
            "views": [] if not sample else [
                {
                    "target_index": None,
                    "baseline": {"psnr_db": None, "ssim": None, "lpips": None},
                    "scarf": {"psnr_db": None, "ssim": None, "lpips": None},
                }
            ],
            **({"execution_trace_sha256": HEX64} if sample else {"execution_trace_set_sha256": HEX64}),
        },
        "performance": {
            "baseline_cycles": None,
            "scarf_cycles": None,
            "speedup": None,
            "baseline_source": "orin_nx_cuda_events"
            if include_orin
            else "source_bound_timing_backend",
            "cycle_source": "source_bound_verified_timing_trace_v1",
            "components": {
                "feature": None,
                "depth": None,
                "gaussian": None,
                "ggu": None,
            },
            "stages": {
                stage: {
                    "cycles": None,
                    "useful_mmcu_slots": None,
                    "scheduled_mmcu_slots": None,
                    "mmcu_slots_available": None,
                    "source": "source_bound_verified_timing_trace_v1",
                }
                for stage in ("s1", "s2", "s3", "s4")
            },
            **({"execution_trace_sha256": HEX64} if sample else {"execution_trace_set_sha256": HEX64}),
            "claim_timing": {
                "schema_version": "source-bound-claim-timing-v1",
                "timing_class": "rtl_cycle_equivalent_source_bound",
                "rtl_cycle_equivalent": True,
                "clock_mhz": None,
                "trace": {"path": timing_path, "sha256": HEX64},
                "input_binding_sha256": HEX64,
                "variants": {
                    name: {"total_cycles": None}
                    for name in (
                        "asic",
                        "asic_fsdr",
                        "asic_saes",
                        "asic_fsdr_saes",
                    )
                },
                "combined_stage_cycles": {
                    stage: None for stage in ("s1", "s2", "s3", "s4")
                },
            },
        },
        "ablation": _ablation_template(),
        "fsdr_saes": _fsdr_saes_template(),
        "events": _events_template(),
        "energy": {"available": False, "source": "not_measured"},
        "hardware": {"physical_ppa_included": False},
        "validation": {
            "reproducible": None,
            "reference_fallback_used": False,
            "dataset_aggregate": not sample,
            "complete_sample_set": None,
        },
    }
    if not sample:
        sample_evidence = {
            "path": "samples/sample_00000/results.json",
            "sha256": HEX64,
            "sample_index": 0,
            "execution_trace_sha256": HEX64,
        }
        if include_orin:
            sample_evidence["orin_measurement"] = {
                "path": "samples/sample_00000/orin-evidence/measurement.json",
                "sha256": HEX64,
            }
        record["provenance"]["evaluation"]["sample_results"] = [sample_evidence]
    if include_orin and not sample:
        record["provenance"]["evaluation"].update(
            {
                "execution_trace_set_schema_version": "execution-trace-set-v2",
                "execution_trace_set": [
                    {
                        "sample_index": 0,
                        "execution_index": 0,
                        "execution_trace_sha256": HEX64,
                        "orin_measurement_sha256": HEX64,
                    }
                ],
                "execution_trace_performance_evidence": _execution_trace_performance_template(),
                "execution_trace_set_sha256": HEX64,
            }
        )
    elif not sample:
        record["provenance"]["evaluation"].update(
            {
                "execution_trace_set_schema_version": "execution-trace-set-v2",
                "execution_trace_set": [
                    {
                        "sample_index": 0,
                        "execution_index": 0,
                        "execution_trace_sha256": HEX64,
                    }
                ],
                "execution_trace_performance_evidence": _execution_trace_performance_template(),
                "execution_trace_set_sha256": HEX64,
            }
        )
    return record


def _sample_result_template(model: str, dataset: str, *, include_orin: bool) -> dict:
    record = _aggregate_template(
        model, dataset, include_orin=include_orin, sample=True
    )
    record["validation"] = {
        "reproducible": None,
        "reference_fallback_used": False,
    }
    return record


def _orin_measurement_template() -> dict:
    return {
        "schema_version": "1.0",
        "kind": "orin_nx_measurement",
        "status": "pending_validation",
        "baseline_source": "orin_nx_cuda_events",
        "started_at": None,
        "elapsed_seconds": None,
        "command": ["<fill-python>", "scripts/demo.py"],
        "environment": {
            "contract": {
                "schema_version": "1.0",
                "status": "runtime_autodetect",
                "device_model_contains": "Jetson Orin NX",
                "power_mode_contains": "MAXN",
                "require_jetson_clocks": True,
                "maximum_allowed_temperature_c": 80.0,
                "timing_repetitions": 5,
            },
            "device_model": None,
            "jetpack": None,
            "l4t_release": None,
            "nvpmodel": None,
            "jetson_clocks": None,
            "nvcc": None,
            "python": None,
            "torch": None,
            "torch_cuda": None,
        },
        "selection": {
            "sample_selection_sha256": HEX64,
            "dataset_tree_sha256": HEX64,
            "checkpoint_sha256": HEX64,
            "sample_index": None,
            "execution_index": None,
            "scene": None,
            "context_indices": [],
            "target_indices": [],
        },
        "cuda_event_encoder_samples_ms": [],
        "cuda_event_encoder_median_ms": None,
        "cuda_event_repetitions": 5,
        "thermal": {
            "sample_lines": None,
            "maximum_temperature_c": None,
            "minimum_temperature_c": None,
        },
        "artifacts": {
            name: {"path": None, "sha256": HEX64}
            for name in ("inference_result", "tegrastats", "nsight_systems", "cuda_events")
        },
    }


def _validation_template() -> dict:
    return {
        "schema_version": "1.0",
        "status": "pending_validation",
        "validation_profile": "evaluator-final",
        "require_key_results": True,
        "checks": [],
        "summary": {"passed": None, "total": None},
    }


def _pair_measurement_template() -> dict:
    return {
        "schema_version": "1.0",
        "kind": "orin_nx_pair_measurement",
        "status": "pending_validation",
        "sample_count": None,
        "sample_selection_sha256": HEX64,
        "measurements": [
            {
                "sample_index": 0,
                "path": "samples/sample_00000/orin-evidence/measurement.json",
                "sha256": HEX64,
            }
        ],
    }


def _pair_execution_template(workflow: str, model: str, dataset: str) -> dict:
    return {
        "schema_version": "1.0",
        "kind": "pair_execution",
        "sample_count": None,
        "executed": None,
        "resumed": None,
        "complete": None,
        "source_index": {
            "source_entry_count": None,
            "null_entry_count": None,
            "sample_count": None,
            "source_index_sha256": HEX64,
            "sample_selection_sha256": HEX64,
        },
    }


def _file_manifest_template() -> dict:
    """Describe every materialized path without expanding tens of thousands of files."""
    pairs = [f"{model}_{dataset}" for model in MODELS for dataset in DATASETS]
    return {
        "schema_version": "scarf-claim-evidence-file-manifest-v1",
        "status": "pending_validation",
        "claim_eligible": False,
        "template_root": "external-only",
        "sample_index_format": "sample_<index:05d>",
        "profiles": {
            "full": {"re10k": 6474, "acid": 1595, "dl3dv": 140},
            "reviewer": {"re10k": 512, "acid": 512, "dl3dv": 140},
        },
        "models": list(MODELS),
        "datasets": list(DATASETS),
        "pairs": pairs,
        "required_files": {
            "calibration": [
                "calibration/manifest.json",
                "calibration/candidates.json",
                "calibration/plan.json",
                "calibration/train-candidates.json",
                "calibration/train-selection.json",
                "calibration/holdout-request.json",
                "calibration/candidate-template.json",
                "calibration/mechanism_config.json",
                "calibration/calibration-result.json",
                "calibration/traces/<split>/<model>_dl3dv/samples/<sample>/results.json",
            ],
            "timing_backend": [
                "timing-backend/manifest.json",
                "timing-backend/rtl/ScarfTop.sv",
                "timing-backend/timing-trace/<model>/<dataset>/<sample>.json",
            ],
            "workflow_pair": [
                "<workflow>/<pair>/results.json",
                "<workflow>/<pair>/samples/<sample>/results.json",
                "<workflow>/<pair>/samples/<sample>/timing-trace/<model>/<dataset>/<sample>.json",
                "<workflow>/<pair>/samples/<sample>/timing-backend/manifest.json",
                "<workflow>/<pair>/samples/<sample>/timing-backend/rtl/ScarfTop.sv",
                "<workflow>/<pair>/samples/<sample>/timing-backend/timing-trace/<model>/<dataset>/<sample>.json",
                "<workflow>/<pair>/pair-execution.json",
                "<workflow>/<pair>/progress.jsonl",
                "<workflow>/<pair>/timing-trace/aggregate.json",
            ],
            "orin_speedup": [
                "speedup/<pair>/samples/<sample>/orin-evidence/measurement.json",
                "speedup/<pair>/samples/<sample>/orin-evidence/cuda-events.json",
                "speedup/<pair>/orin-profile/tegrastats.log",
                "speedup/<pair>/orin-profile/nsight.nsys-rep",
                "speedup/<pair>/orin-profile/pair-measurement.json",
            ],
            "environment_and_validation": [
                "environments/classic.json",
                "environments/depthsplat.json",
                "environments/orin.json",
                "validation.json",
                "progress-event-examples.json",
                "FIELD_REFERENCE.md",
            ],
            "documentation_and_fixtures": [
                "README.md",
                "FORMAT_SPEC.md",
                "FIELD_REFERENCE.md",
                "FILE_MANIFEST.json",
                "input-manifest.json",
                "validation-fixtures/calibration/calibration-fixture.json",
                "validation-fixtures/calibration/selection.json",
                "validation-fixtures/timing/manifest.json",
                "validation-fixtures/timing/rtl/ScarfTop_validation_fixture.sv",
                "validation-fixtures/timing/timing-trace/mvsplat/re10k/sample_00000.json",
            ],
        },
        "counts": {
            "calibration_train_traces_per_pair": 24,
            "calibration_holdout_traces_per_pair": 8,
            "timing_traces_per_pair": {
                "full": {"re10k": 6474, "acid": 1595, "dl3dv": 140},
                "reviewer": {"re10k": 512, "acid": 512, "dl3dv": 140},
            },
            "result_samples_per_pair": {
                "full": {"re10k": 6474, "acid": 1595, "dl3dv": 140},
                "reviewer": {"re10k": 512, "acid": 512, "dl3dv": 140},
            },
        },
        "expansion_rule": (
            "For each workflow and pair, materialize one sample result for every "
            "index 00000 through count-1. The timing manifest and raw timing trace "
            "must cover the same model/dataset/index set."
        ),
    }


def _progress_examples_template() -> dict:
    """Show the JSON object shapes appended by run_pair.py to progress.jsonl."""
    return {
        "schema_version": "run-pair-progress-format-v1",
        "status": "format_only",
        "events": [
            {
                "timestamp": "<fill-iso8601-utc>",
                "event": "pair_start",
                "sample_count": None,
                "pending": None,
                "resumed": None,
                "git_commit": HEX40,
                "git_dirty": None,
            },
            {
                "timestamp": "<fill-iso8601-utc>",
                "event": "sample_start",
                "selection": {
                    "sample_index": None,
                    "scene": None,
                    "context_indices": [],
                    "target_indices": [],
                },
            },
            {
                "timestamp": "<fill-iso8601-utc>",
                "event": "sample_complete",
                "selection": {
                    "sample_index": None,
                    "scene": None,
                    "context_indices": [],
                    "target_indices": [],
                },
                "executed": None,
                "remaining": None,
            },
            {
                "timestamp": "<fill-iso8601-utc>",
                "event": "sample_error",
                "selection": {
                    "sample_index": None,
                    "scene": None,
                    "context_indices": [],
                    "target_indices": [],
                },
                "error_type": "<fill-exception-class>",
                "error": "<fill-error-message>",
            },
            {
                "timestamp": "<fill-iso8601-utc>",
                "event": "pair_complete",
                "schema_version": "1.0",
                "kind": "pair_execution",
                "sample_count": None,
                "executed": None,
                "resumed": None,
                "complete": None,
                "source_index": {
                    "source_entry_count": None,
                    "null_entry_count": None,
                    "sample_count": None,
                    "source_index_sha256": HEX64,
                    "sample_selection_sha256": HEX64,
                },
            },
        ],
    }


def _calibration_plan_template() -> dict:
    return {
        "schema_version": "2.0",
        "kind": "split_calibration_sweep_plan",
        "calibration_protocol": "dl3dv_train_holdout_v1",
        "manifest": "manifest.json",
        "calibration_manifest_sha256": HEX64,
        "evaluation_disjoint": None,
        "train_holdout_scene_disjoint": None,
        "splits": {
            "calibration_train": {
                "split": "calibration_train",
                "sample_count": 24,
                "selection_sha256": HEX64,
                "scene_set_sha256": HEX64,
                "required_pairs": [
                    "transplat/dl3dv",
                    "mvsplat/dl3dv",
                    "depthsplat/dl3dv",
                ],
                "pairs": [],
                "execution_mode": "registered_global_grid",
            },
            "calibration_holdout": {
                "split": "calibration_holdout",
                "sample_count": 8,
                "selection_sha256": HEX64,
                "scene_set_sha256": HEX64,
                "required_pairs": [
                    "transplat/dl3dv",
                    "mvsplat/dl3dv",
                    "depthsplat/dl3dv",
                ],
                "pairs": [],
                "execution_mode": "deferred_exact_train_selected_tuple",
            },
        },
    }


def _calibration_split_result_template(split: str) -> dict:
    pairs = [
        {
            "model": model,
            "dataset": "dl3dv",
            "representation": "native" if model == "depthsplat" else "re10k",
            "sample_count": 24 if split == "calibration_train" else 8,
            "selection_sha256": HEX64,
            "scene_set_sha256": HEX64,
            "calibration_input_root": f"inputs/{split}/<representation>",
            "calibration_input_tree_sha256": HEX64,
            "calibration_input_manifest_sha256": HEX64,
            "calibration_input_provenance_sha256": HEX64,
            "index_file": f"{split}-<representation>.json",
            "index_sha256": HEX64,
        }
        for model in MODELS
    ]
    count = 24 if split == "calibration_train" else 8
    trace_files = [
        {
            "pair": f"{model}/dl3dv",
            "path": f"traces/{split}/{model}_dl3dv/samples/sample_00000/results.json",
            "sha256": HEX64,
        }
        for model in MODELS
    ]
    return {
        "split": split,
        "execution_mode": (
            "registered_global_grid"
            if split == "calibration_train"
            else "exact_train_selected_tuple_no_rerank"
        ),
        "sample_count": count,
        "selection_sha256": HEX64,
        "scene_set_sha256": HEX64,
        "required_pairs": [
            "transplat/dl3dv",
            "mvsplat/dl3dv",
            "depthsplat/dl3dv",
        ],
        "pair_bindings": pairs,
        "pair_bindings_sha256": HEX64,
        "trace_count": count * len(MODELS),
        "trace_set_sha256": HEX64,
        "trace_files": trace_files,
        "candidate_count": 576 if split == "calibration_train" else 1,
        "candidate_set_sha256": HEX64,
        "candidates": [_calibration_candidate_template()],
    }


def _reject_release_output(path: Path) -> Path:
    """Keep format templates outside release and generated-evidence roots."""
    resolved = path.resolve()
    forbidden = tuple((ROOT / item).resolve() for item in ("artifact", "outputs", "evidence"))
    if any(resolved == root or root in resolved.parents for root in forbidden):
        raise ValueError(
            "format-only template must be outside artifact/, outputs/, and evidence/"
        )
    return resolved


def _write_format_templates(output: Path) -> None:
    """Materialize all named file classes without creating evidence values."""
    _write_json(output / "calibration/manifest.json", _calibration_manifest_template())
    _write_json(output / "calibration/candidates.json", _calibration_candidates_template())
    _write_json(output / "calibration/plan.json", _calibration_plan_template())
    _write_json(
        output / "calibration/train-candidates.json",
        {
            "schema_version": "2.0",
            "kind": "split_calibration_candidate_records",
            "calibration_protocol": "dl3dv_train_holdout_v1",
            "evaluation_disjoint": None,
            "train_holdout_scene_disjoint": None,
            "calibration_manifest_sha256": HEX64,
            "status": "pending_validation",
            "train_selection": None,
            "splits": {
                "calibration_train": _calibration_split_result_template(
                    "calibration_train"
                )
            },
        },
    )
    _write_json(
        output / "calibration/candidate-template.json", _calibration_candidate_template()
    )
    # These are format copies of the file produced by calibrate_mechanisms.py.
    # They remain pending until the real train/holdout run supplies hashes and
    # the selected tuple; neither copy is installed into the release by init().
    mechanism_config = _mechanism_config_template()
    _write_json(output / "calibration/mechanism_config.json", mechanism_config)
    _write_json(output / "calibration/calibration-result.json", mechanism_config)
    _write_json(
        output / "calibration/train-selection.json",
        {
            "schema_version": "1.0",
            "parameters": {
                "gamma_depth": None,
                "beta_x": None,
                "beta_f": None,
                "beta_d": None,
            },
            "parameters_sha256": None,
            "candidate_sha256": None,
            "selection_rule": "quality constraints, maximum event work reduction",
        },
    )
    _write_json(
        output / "calibration/holdout-request.json",
        {
            "schema_version": "1.0",
            "kind": "calibration_holdout_request",
            "calibration_manifest_sha256": None,
            "train_selection": None,
            "execution_mode": "exact_train_selected_tuple_no_rerank",
        },
    )
    for split in ("calibration_train", "calibration_holdout"):
        split_root = output / "calibration/traces" / split
        split_root.mkdir(parents=True, exist_ok=True)
        (split_root / "README.md").write_text(
            "One results.json per sample for each model/dataset pair.\n"
            "Train uses the complete registered parameter grid; holdout uses\n"
            "only the committed train tuple.\n",
            encoding="utf-8",
        )
        for model in MODELS:
            pair_root = split_root / f"{model}_dl3dv"
            _write_json(
                pair_root / "samples/sample_00000/results.json",
                _calibration_trace_template(model, "dl3dv", split),
            )
    _write_json(output / "timing-backend/manifest.json", _timing_manifest_template())
    (output / "timing-backend/rtl/ScarfTop.sv").parent.mkdir(
        parents=True, exist_ok=True
    )
    (output / "timing-backend/rtl/ScarfTop.sv").write_text(
        "// Replace with the exact source RTL used by the cycle-accurate backend.\n"
        "// This placeholder is not claim evidence.\n"
        "module ScarfTop;\n"
        "endmodule\n",
        encoding="utf-8",
    )
    (output / "timing-backend/timing-trace/README.md").write_text(
        "One source-bound JSON trace per sample: "
        "timing-trace/<model>/<dataset>/sample_<index:05d>.json.\n"
        "Use the adjacent sample_00000.json only as a field template.\n",
        encoding="utf-8",
    )
    for model in MODELS:
        for dataset in DATASETS:
            _write_json(
                output
                / "timing-backend/timing-trace"
                / model
                / dataset
                / "sample_00000.json",
                _timing_trace_template(model, dataset),
            )
            pair = f"{model}_{dataset}"
            for workflow in ("quality", "mechanisms", "speedup"):
                pair_root = output / workflow / pair
                _write_json(
                    pair_root / "results.json",
                    _aggregate_template(model, dataset, include_orin=workflow == "speedup"),
                )
                _write_json(
                    pair_root / "samples/sample_00000/results.json",
                    _sample_result_template(
                        model, dataset, include_orin=workflow == "speedup"
                    ),
                )
                # claim_timing_for_sample() stages these two portable paths
                # below every sample. Keep the exemplar bundle visible so a
                # target export can reproduce the complete nesting exactly.
                sample_root = pair_root / "samples/sample_00000"
                sample_trace = (
                    sample_root
                    / "timing-trace"
                    / model
                    / dataset
                    / "sample_00000.json"
                )
                _write_json(sample_trace, _timing_trace_template(model, dataset))
                sample_backend = sample_root / "timing-backend"
                _write_json(sample_backend / "manifest.json", _timing_manifest_template())
                (sample_backend / "rtl/ScarfTop.sv").parent.mkdir(
                    parents=True, exist_ok=True
                )
                (sample_backend / "rtl/ScarfTop.sv").write_text(
                    "// Replace with the exact source RTL used by the cycle-accurate backend.\n"
                    "// This placeholder is not claim evidence.\n"
                    "module ScarfTop;\n"
                    "endmodule\n",
                    encoding="utf-8",
                )
                _write_json(
                    sample_backend
                    / "timing-trace"
                    / model
                    / dataset
                    / "sample_00000.json",
                    _timing_trace_template(model, dataset),
                )
                _write_json(
                    pair_root / "pair-execution.json",
                    _pair_execution_template(workflow, model, dataset),
                )
                (pair_root / "progress.jsonl").write_text(
                    "# Replace with one JSON progress event per executed sample.\n",
                    encoding="utf-8",
                )
                _write_json(
                    pair_root / "timing-trace/aggregate.json",
                    {
                        "schema_version": "source-bound-claim-timing-v1",
                        "kind": "dataset_aggregate",
                        "samples": [],
                        "aggregate": {
                            "variants": {
                                name: {"total_cycles": None}
                                for name in (
                                    "asic",
                                    "asic_fsdr",
                                    "asic_saes",
                                    "asic_fsdr_saes",
                                )
                            },
                            "combined_stage_cycles": {
                                stage: None for stage in ("s1", "s2", "s3", "s4")
                            },
                        },
                    },
                )
            orin_root = output / "speedup" / pair
            _write_json(
                orin_root / "samples/sample_00000/orin-evidence/measurement.json",
                _orin_measurement_template(),
            )
            _write_json(
                orin_root / "samples/sample_00000/orin-evidence/cuda-events.json",
                {
                    "schema_version": "1.0",
                    "source": "torch.cuda.Event",
                    "samples_ms": [],
                    "median_ms": None,
                },
            )
            _write_json(orin_root / "orin-profile/pair-measurement.json", _pair_measurement_template())
            (orin_root / "orin-profile/tegrastats.log").write_text(
                "# Replace with the raw tegrastats output.\n", encoding="utf-8"
            )
            (orin_root / "orin-profile/nsight.nsys-rep").write_bytes(b"")
    for profile in ("classic", "depthsplat", "orin"):
        _write_json(output / "environments" / f"{profile}.json", _environment_template(profile))
    (output / "environments/README.md").write_text(
        "Environment records are emitted by scripts/check_environment.py.\n"
        "Replace each placeholder with the complete host/profile capture.\n",
        encoding="utf-8",
    )
    _write_json(output / "progress-event-examples.json", _progress_examples_template())
    (output / "FIELD_REFERENCE.md").write_text(FIELD_REFERENCE, encoding="utf-8")
    _write_json(output / "validation.json", _validation_template())
    _write_json(output / "FILE_MANIFEST.json", _file_manifest_template())


def init(output: Path) -> Path:
    output = _reject_release_output(output)
    output.mkdir(parents=True, exist_ok=True)
    for directory in (
        "calibration",
        "timing-backend/timing-trace",
        "quality",
        "mechanisms",
        "speedup",
    ):
        (output / directory).mkdir(parents=True, exist_ok=True)
    for model in MODELS:
        for dataset in DATASETS:
            pair = f"{model}_{dataset}"
            (output / "quality" / pair).mkdir(parents=True, exist_ok=True)
            (output / "mechanisms" / pair).mkdir(parents=True, exist_ok=True)
            (output / "speedup" / pair).mkdir(parents=True, exist_ok=True)
    (output / "README.md").write_text(README, encoding="utf-8")
    (output / "FORMAT_SPEC.md").write_text(FORMAT_SPEC, encoding="utf-8")
    _write_format_templates(output)
    # These fixtures document the exact interfaces while remaining explicitly
    # rejected by the claim loader.  They are useful when wiring a real export.
    from scripts.build_calibration_validation_fixture import build_fixture as build_calibration_fixture
    from scripts.build_claim_timing_validation_fixture import build_fixture as build_timing_fixture

    build_calibration_fixture(output / "validation-fixtures/calibration")
    build_timing_fixture(output / "validation-fixtures/timing")
    (output / "input-manifest.json").write_text(
        json.dumps(
            {
                "schema_version": "scarf-claim-evidence-input-v1",
                "status": "pending_validation",
                "claim_eligible": False,
                "required_pairs": [f"{model}/{dataset}" for model in MODELS for dataset in DATASETS],
                "required_workflows": ["quality", "mechanisms", "speedup"],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    path = init(args.output)
    print(f"initialized non-claim evidence input template: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
