"""Fixed, target-free safety bounds shared by SAES control and identity checks."""

MATERIALIZATION_GUARD_POLICY = "anchor-attribute-consistency-v1"
MATERIALIZATION_GUARD_MIN_COVARIANCE_COSINE = 0.7
MATERIALIZATION_GUARD_MIN_HARMONIC_COSINE = 0.7
MATERIALIZATION_GUARD_MAX_OPACITY_DISTANCE = 0.2

CONTEXT_GUARD_POLICY = "projected-anchor-coverage-occlusion-v3"
CONTEXT_GUARD_MAX_FOOTPRINT_RATIO = 16.0
CONTEXT_GUARD_MAX_RELATIVE_DEPTH_SPAN = 0.25
CONTEXT_GUARD_MAX_CENTER_MAHALANOBIS = 2.0
